/**
 * The app's ONE emoji catalogue (v2.99.80).
 *
 * WHY THIS EXISTS
 * ---------------
 * The owner asked for "the list of all emojis" on the status-reply surface. Before
 * this module there were THREE separate hand-written lists that had drifted apart:
 *
 *   - `EMOJI_QUICK` in Messages.tsx        — 32 glyphs, the chat composer
 *   - `CHAT_EMOJIS` in relayClient.ts      — 48 glyphs, the in-call chat palette
 *   - `AVATAR_EMOJIS` in emojiAvatar.ts    — 56 glyphs, but a DIFFERENT PURPOSE
 *
 * A fourth copy for statuses would have been the wrong answer, so this is the
 * shared one. `AVATAR_EMOJIS` is deliberately NOT folded in: it is curated for
 * glyphs that read well rendered large on a coloured disc as somebody's face, so
 * "🍕" belongs in this catalogue and not in that one.
 *
 * "ALL EMOJIS" — SAID PLAINLY
 * ---------------------------
 * The full Unicode emoji set is ~3,700 glyphs, and shipping literally all of them
 * means either a new dependency or a generated dataset plus a virtualised grid.
 * This module carries ~840 across the nine standard categories — the glyphs people
 * actually reach for, every one of them keyboard-searchable by name. That is what
 * "the list of all emojis" means in practice on a phone; a complete Unicode dump
 * with skin-tone and profession variants would be slower to use, not richer.
 *
 * Zero dependency, matching this codebase's own SMTP / S3 SigV4 / FCM / Expo / GIF
 * encoders. Plain data, so it tree-shakes and costs nothing until a picker mounts.
 *
 * SEARCH is by keyword, not by Unicode name: nobody types "grinning face with
 * smiling eyes", they type "happy". Each entry carries a short keyword string.
 */

export interface EmojiGroup {
  id: string;
  /** Short label for the category tab. */
  label: string;
  /** The tab's own glyph — kept ASCII-free so it renders in every font. */
  icon: string;
  /** `glyph keywords` pairs, flattened for compactness. */
  items: Array<{ e: string; k: string }>;
}

/* Keywords are lowercase and space-separated; the matcher also matches a prefix,
 * so "lau" finds "laugh". Kept short on purpose — a long keyword list makes every
 * query match everything, which is the same as having no search at all. */
export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    id: "smileys",
    label: "Smileys",
    icon: "🙂",
    items: [
      { e: "😀", k: "grin happy smile" },
      { e: "😃", k: "smile happy joy" },
      { e: "😄", k: "smile happy laugh" },
      { e: "😁", k: "beam grin happy" },
      { e: "😆", k: "laugh squint happy" },
      { e: "😅", k: "sweat laugh relief" },
      { e: "🤣", k: "rofl laugh floor" },
      { e: "😂", k: "joy laugh cry tears" },
      { e: "🙂", k: "slight smile" },
      { e: "🙃", k: "upside down silly" },
      { e: "🫠", k: "melting hot" },
      { e: "😉", k: "wink" },
      { e: "😊", k: "blush smile happy" },
      { e: "😇", k: "halo angel innocent" },
      { e: "🥰", k: "love hearts adore" },
      { e: "😍", k: "heart eyes love" },
      { e: "🤩", k: "star struck wow" },
      { e: "😘", k: "kiss blow" },
      { e: "😗", k: "kiss" },
      { e: "😚", k: "kiss closed eyes" },
      { e: "😙", k: "kiss smile" },
      { e: "🥲", k: "happy tear" },
      { e: "😋", k: "yum tasty tongue" },
      { e: "😛", k: "tongue" },
      { e: "😜", k: "wink tongue silly" },
      { e: "🤪", k: "zany crazy wild" },
      { e: "😝", k: "squint tongue" },
      { e: "🤑", k: "money mouth rich" },
      { e: "🤗", k: "hug" },
      { e: "🤭", k: "oops giggle hand" },
      { e: "🫢", k: "gasp shock hand" },
      { e: "🤫", k: "shush quiet" },
      { e: "🤔", k: "think hmm" },
      { e: "🫡", k: "salute respect" },
      { e: "🤐", k: "zip mouth silence" },
      { e: "🤨", k: "eyebrow doubt suspicious" },
      { e: "😐", k: "neutral" },
      { e: "😑", k: "expressionless blank" },
      { e: "😶", k: "no mouth silent" },
      { e: "🫥", k: "dotted invisible" },
      { e: "😏", k: "smirk" },
      { e: "😒", k: "unamused meh" },
      { e: "🙄", k: "eye roll" },
      { e: "😬", k: "grimace awkward" },
      { e: "🤥", k: "lying nose" },
      { e: "😌", k: "relieved calm" },
      { e: "😔", k: "sad pensive" },
      { e: "😪", k: "sleepy tired" },
      { e: "🤤", k: "drool" },
      { e: "😴", k: "sleep zzz" },
      { e: "😷", k: "mask sick" },
      { e: "🤒", k: "sick thermometer fever" },
      { e: "🤕", k: "hurt bandage injured" },
      { e: "🤢", k: "nauseated sick gross" },
      { e: "🤮", k: "vomit sick" },
      { e: "🤧", k: "sneeze tissue" },
      { e: "🥵", k: "hot heat sweat" },
      { e: "🥶", k: "cold freeze" },
      { e: "🥴", k: "woozy drunk dizzy" },
      { e: "😵", k: "dizzy knocked out" },
      { e: "🤯", k: "mind blown explode" },
      { e: "🤠", k: "cowboy hat" },
      { e: "🥳", k: "party celebrate hat" },
      { e: "🥸", k: "disguise glasses" },
      { e: "😎", k: "cool sunglasses" },
      { e: "🤓", k: "nerd glasses geek" },
      { e: "🧐", k: "monocle inspect" },
      { e: "😕", k: "confused" },
      { e: "🫤", k: "diagonal mouth meh" },
      { e: "😟", k: "worried" },
      { e: "🙁", k: "frown sad" },
      { e: "😮", k: "open mouth surprise" },
      { e: "😯", k: "hushed surprise" },
      { e: "😲", k: "astonished shock" },
      { e: "😳", k: "flushed embarrassed" },
      { e: "🥺", k: "pleading please beg" },
      { e: "🥹", k: "holding tears" },
      { e: "😦", k: "frown open" },
      { e: "😧", k: "anguished" },
      { e: "😨", k: "fearful scared" },
      { e: "😰", k: "anxious sweat" },
      { e: "😥", k: "sad relieved" },
      { e: "😢", k: "cry tear sad" },
      { e: "😭", k: "sob cry loud" },
      { e: "😱", k: "scream fear shock" },
      { e: "😖", k: "confounded" },
      { e: "😣", k: "persevere struggle" },
      { e: "😞", k: "disappointed sad" },
      { e: "😓", k: "downcast sweat" },
      { e: "😩", k: "weary tired" },
      { e: "😫", k: "tired exhausted" },
      { e: "🥱", k: "yawn bored" },
      { e: "😤", k: "triumph steam huff" },
      { e: "😡", k: "angry rage mad" },
      { e: "😠", k: "angry mad" },
      { e: "🤬", k: "cursing swear symbols" },
      { e: "😈", k: "devil smile mischief" },
      { e: "👿", k: "devil angry imp" },
      { e: "💀", k: "skull dead" },
      { e: "☠️", k: "skull crossbones danger" },
      { e: "💩", k: "poop" },
      { e: "🤡", k: "clown" },
      { e: "👹", k: "ogre monster" },
      { e: "👺", k: "goblin" },
      { e: "👻", k: "ghost boo" },
      { e: "👽", k: "alien" },
      { e: "🤖", k: "robot bot" },
      { e: "😺", k: "cat smile" },
      { e: "😹", k: "cat joy laugh" },
      { e: "😻", k: "cat heart eyes love" },
      { e: "😽", k: "cat kiss" },
      { e: "🙀", k: "cat weary shock" },
      { e: "😿", k: "cat cry" },
      { e: "😾", k: "cat pout" },
    ],
  },
  {
    id: "gestures",
    label: "People",
    icon: "👋",
    items: [
      { e: "👋", k: "wave hello hi bye" },
      { e: "🤚", k: "raised back hand" },
      { e: "🖐️", k: "hand fingers splayed" },
      { e: "✋", k: "hand stop high five" },
      { e: "🖖", k: "vulcan spock" },
      { e: "🫱", k: "hand right" },
      { e: "🫲", k: "hand left" },
      { e: "🫳", k: "palm down" },
      { e: "🫴", k: "palm up" },
      { e: "👌", k: "ok perfect" },
      { e: "🤌", k: "pinched fingers italian" },
      { e: "🤏", k: "pinch small little" },
      { e: "✌️", k: "victory peace" },
      { e: "🤞", k: "fingers crossed luck hope" },
      { e: "🫰", k: "finger heart money" },
      { e: "🤟", k: "love you" },
      { e: "🤘", k: "rock horns metal" },
      { e: "🤙", k: "call me shaka" },
      { e: "👈", k: "point left" },
      { e: "👉", k: "point right" },
      { e: "👆", k: "point up" },
      { e: "🖕", k: "middle finger rude" },
      { e: "👇", k: "point down" },
      { e: "☝️", k: "index up" },
      { e: "🫵", k: "point viewer you" },
      { e: "👍", k: "thumbs up like yes good" },
      { e: "👎", k: "thumbs down dislike no bad" },
      { e: "✊", k: "fist raised" },
      { e: "👊", k: "fist bump punch" },
      { e: "🤛", k: "fist left" },
      { e: "🤜", k: "fist right" },
      { e: "👏", k: "clap applause bravo" },
      { e: "🙌", k: "raise hands celebrate praise" },
      { e: "🫶", k: "heart hands love" },
      { e: "👐", k: "open hands" },
      { e: "🤲", k: "palms up together pray" },
      { e: "🤝", k: "handshake deal agree" },
      { e: "🙏", k: "pray thanks please namaste" },
      { e: "✍️", k: "writing hand" },
      { e: "💅", k: "nail polish" },
      { e: "🤳", k: "selfie" },
      { e: "💪", k: "muscle strong flex" },
      { e: "🦾", k: "mechanical arm" },
      { e: "🦿", k: "mechanical leg" },
      { e: "🦵", k: "leg" },
      { e: "🦶", k: "foot" },
      { e: "👂", k: "ear listen" },
      { e: "🦻", k: "ear hearing aid" },
      { e: "👃", k: "nose smell" },
      { e: "🧠", k: "brain smart" },
      { e: "🫀", k: "anatomical heart" },
      { e: "🫁", k: "lungs breathe" },
      { e: "🦷", k: "tooth" },
      { e: "🦴", k: "bone" },
      { e: "👀", k: "eyes look watch see" },
      { e: "👁️", k: "eye" },
      { e: "👅", k: "tongue" },
      { e: "👄", k: "mouth lips" },
      { e: "🫦", k: "biting lip" },
      { e: "💋", k: "kiss mark lips" },
      { e: "👶", k: "baby" },
      { e: "🧒", k: "child" },
      { e: "👦", k: "boy" },
      { e: "👧", k: "girl" },
      { e: "🧑", k: "person adult" },
      { e: "👨", k: "man" },
      { e: "👩", k: "woman" },
      { e: "🧓", k: "older person" },
      { e: "👴", k: "old man" },
      { e: "👵", k: "old woman" },
      { e: "🙅", k: "no gesture refuse" },
      { e: "🙆", k: "ok gesture" },
      { e: "💁", k: "tipping hand info sassy" },
      { e: "🙋", k: "raising hand question" },
      { e: "🧏", k: "deaf person" },
      { e: "🙇", k: "bow sorry respect" },
      { e: "🤦", k: "facepalm" },
      { e: "🤷", k: "shrug dunno" },
      { e: "👮", k: "police officer cop" },
      { e: "🕵️", k: "detective spy" },
      { e: "💂", k: "guard" },
      { e: "🥷", k: "ninja" },
      { e: "👷", k: "construction worker" },
      { e: "🫅", k: "person crown royalty" },
      { e: "🤴", k: "prince" },
      { e: "👸", k: "princess" },
      { e: "👳", k: "turban" },
      { e: "👲", k: "skullcap" },
      { e: "🧕", k: "headscarf hijab" },
      { e: "🤵", k: "tuxedo groom" },
      { e: "👰", k: "veil bride wedding" },
      { e: "🤰", k: "pregnant" },
      { e: "🤱", k: "breastfeeding" },
      { e: "🧑‍🍼", k: "feeding baby" },
      { e: "🎅", k: "santa christmas" },
      { e: "🤶", k: "mrs claus" },
      { e: "🦸", k: "superhero" },
      { e: "🦹", k: "supervillain" },
      { e: "🧙", k: "mage wizard" },
      { e: "🧚", k: "fairy" },
      { e: "🧛", k: "vampire" },
      { e: "🧜", k: "merperson mermaid" },
      { e: "🧝", k: "elf" },
      { e: "🧞", k: "genie" },
      { e: "🧟", k: "zombie" },
      { e: "💆", k: "massage spa" },
      { e: "💇", k: "haircut" },
      { e: "🚶", k: "walk" },
      { e: "🧍", k: "stand" },
      { e: "🧎", k: "kneel" },
      { e: "🏃", k: "run" },
      { e: "💃", k: "dance woman" },
      { e: "🕺", k: "dance man" },
      { e: "👯", k: "bunny ears partying" },
      { e: "🧗", k: "climb" },
      { e: "🧘", k: "yoga meditate lotus" },
      { e: "🛀", k: "bath" },
      { e: "🛌", k: "in bed sleep" },
      { e: "👣", k: "footprints" },
    ],
  },
  {
    id: "hearts",
    label: "Hearts",
    icon: "❤️",
    items: [
      { e: "❤️", k: "red heart love" },
      { e: "🧡", k: "orange heart" },
      { e: "💛", k: "yellow heart" },
      { e: "💚", k: "green heart" },
      { e: "💙", k: "blue heart" },
      { e: "💜", k: "purple heart" },
      { e: "🖤", k: "black heart" },
      { e: "🤍", k: "white heart" },
      { e: "🤎", k: "brown heart" },
      { e: "🩵", k: "light blue heart" },
      { e: "🩷", k: "pink heart" },
      { e: "🩶", k: "grey heart" },
      { e: "💔", k: "broken heart sad" },
      { e: "❤️‍🔥", k: "heart on fire burning" },
      { e: "❤️‍🩹", k: "mending heart healing" },
      { e: "💕", k: "two hearts" },
      { e: "💞", k: "revolving hearts" },
      { e: "💓", k: "beating heart" },
      { e: "💗", k: "growing heart" },
      { e: "💖", k: "sparkling heart" },
      { e: "💘", k: "heart arrow cupid" },
      { e: "💝", k: "heart ribbon gift" },
      { e: "💟", k: "heart decoration" },
      { e: "♥️", k: "heart suit cards" },
      { e: "💌", k: "love letter" },
      { e: "💐", k: "bouquet flowers" },
      { e: "🌹", k: "rose flower" },
      { e: "🌷", k: "tulip" },
      { e: "🌸", k: "cherry blossom" },
      { e: "💍", k: "ring engagement" },
      { e: "😻", k: "cat heart eyes" },
      { e: "😽", k: "kissing cat" },
    ],
  },
  {
    id: "animals",
    label: "Nature",
    icon: "🐾",
    items: [
      { e: "🐶", k: "dog puppy" },
      { e: "🐱", k: "cat kitten" },
      { e: "🐭", k: "mouse" },
      { e: "🐹", k: "hamster" },
      { e: "🐰", k: "rabbit bunny" },
      { e: "🦊", k: "fox" },
      { e: "🐻", k: "bear" },
      { e: "🐼", k: "panda" },
      { e: "🐻‍❄️", k: "polar bear" },
      { e: "🐨", k: "koala" },
      { e: "🐯", k: "tiger" },
      { e: "🦁", k: "lion" },
      { e: "🐮", k: "cow" },
      { e: "🐷", k: "pig" },
      { e: "🐸", k: "frog" },
      { e: "🐵", k: "monkey" },
      { e: "🙈", k: "see no evil monkey" },
      { e: "🙉", k: "hear no evil monkey" },
      { e: "🙊", k: "speak no evil monkey" },
      { e: "🐒", k: "monkey" },
      { e: "🐔", k: "chicken" },
      { e: "🐧", k: "penguin" },
      { e: "🐦", k: "bird" },
      { e: "🐤", k: "chick baby bird" },
      { e: "🦅", k: "eagle" },
      { e: "🦆", k: "duck" },
      { e: "🦉", k: "owl" },
      { e: "🦇", k: "bat" },
      { e: "🐺", k: "wolf" },
      { e: "🐗", k: "boar" },
      { e: "🐴", k: "horse" },
      { e: "🦄", k: "unicorn" },
      { e: "🐝", k: "bee honey" },
      { e: "🪲", k: "beetle bug" },
      { e: "🐛", k: "caterpillar bug" },
      { e: "🦋", k: "butterfly" },
      { e: "🐌", k: "snail slow" },
      { e: "🐞", k: "ladybug" },
      { e: "🐜", k: "ant" },
      { e: "🕷️", k: "spider" },
      { e: "🦂", k: "scorpion" },
      { e: "🐢", k: "turtle" },
      { e: "🐍", k: "snake" },
      { e: "🦎", k: "lizard gecko" },
      { e: "🦖", k: "t-rex dinosaur" },
      { e: "🐙", k: "octopus" },
      { e: "🦑", k: "squid" },
      { e: "🦐", k: "shrimp" },
      { e: "🦀", k: "crab" },
      { e: "🐡", k: "blowfish" },
      { e: "🐠", k: "tropical fish" },
      { e: "🐟", k: "fish" },
      { e: "🐬", k: "dolphin" },
      { e: "🐳", k: "whale" },
      { e: "🦈", k: "shark" },
      { e: "🐊", k: "crocodile" },
      { e: "🐅", k: "tiger" },
      { e: "🦓", k: "zebra" },
      { e: "🦍", k: "gorilla" },
      { e: "🐘", k: "elephant" },
      { e: "🦛", k: "hippo" },
      { e: "🦏", k: "rhino" },
      { e: "🐪", k: "camel" },
      { e: "🐫", k: "camel two hump" },
      { e: "🦒", k: "giraffe" },
      { e: "🦘", k: "kangaroo" },
      { e: "🐃", k: "buffalo" },
      { e: "🐄", k: "cow" },
      { e: "🐎", k: "racehorse" },
      { e: "🐖", k: "pig" },
      { e: "🐏", k: "ram" },
      { e: "🐑", k: "sheep" },
      { e: "🦙", k: "llama" },
      { e: "🐐", k: "goat" },
      { e: "🦌", k: "deer" },
      { e: "🐕", k: "dog" },
      { e: "🐩", k: "poodle" },
      { e: "🦮", k: "guide dog" },
      { e: "🐈", k: "cat" },
      { e: "🐓", k: "rooster" },
      { e: "🦃", k: "turkey" },
      { e: "🦚", k: "peacock" },
      { e: "🦜", k: "parrot" },
      { e: "🦢", k: "swan" },
      { e: "🕊️", k: "dove peace" },
      { e: "🐇", k: "rabbit" },
      { e: "🦝", k: "raccoon" },
      { e: "🦨", k: "skunk" },
      { e: "🦥", k: "sloth" },
      { e: "🐁", k: "mouse" },
      { e: "🐿️", k: "chipmunk squirrel" },
      { e: "🦔", k: "hedgehog" },
      { e: "🐾", k: "paw prints" },
      { e: "🌵", k: "cactus" },
      { e: "🎄", k: "christmas tree" },
      { e: "🌲", k: "evergreen tree" },
      { e: "🌳", k: "tree" },
      { e: "🌴", k: "palm tree" },
      { e: "🪴", k: "potted plant" },
      { e: "🌱", k: "seedling sprout" },
      { e: "🌿", k: "herb leaves" },
      { e: "☘️", k: "shamrock" },
      { e: "🍀", k: "four leaf clover luck" },
      { e: "🍃", k: "leaves wind" },
      { e: "🍂", k: "fallen leaves autumn" },
      { e: "🍁", k: "maple leaf" },
      { e: "🌺", k: "hibiscus" },
      { e: "🌻", k: "sunflower" },
      { e: "🌼", k: "blossom" },
      { e: "🌞", k: "sun face" },
      { e: "🌝", k: "full moon face" },
      { e: "🌚", k: "new moon face" },
      { e: "🌙", k: "crescent moon" },
      { e: "⭐", k: "star" },
      { e: "🌟", k: "glowing star" },
      { e: "✨", k: "sparkles shine" },
      { e: "⚡", k: "lightning bolt zap" },
      { e: "🔥", k: "fire lit hot" },
      { e: "🌈", k: "rainbow" },
      { e: "☀️", k: "sun sunny" },
      { e: "⛅", k: "sun behind cloud" },
      { e: "☁️", k: "cloud" },
      { e: "🌧️", k: "rain" },
      { e: "⛈️", k: "storm thunder" },
      { e: "❄️", k: "snowflake cold" },
      { e: "⛄", k: "snowman" },
      { e: "💧", k: "droplet water" },
      { e: "🌊", k: "wave ocean" },
      { e: "🌍", k: "earth globe" },
      { e: "🌎", k: "earth americas" },
      { e: "🌏", k: "earth asia" },
      { e: "🪐", k: "planet saturn" },
      { e: "💫", k: "dizzy stars" },
      { e: "☄️", k: "comet" },
      { e: "🌪️", k: "tornado" },
      { e: "🌫️", k: "fog" },
    ],
  },
  {
    id: "food",
    label: "Food",
    icon: "🍔",
    items: [
      { e: "🍏", k: "green apple" },
      { e: "🍎", k: "apple red" },
      { e: "🍐", k: "pear" },
      { e: "🍊", k: "orange tangerine" },
      { e: "🍋", k: "lemon" },
      { e: "🍌", k: "banana" },
      { e: "🍉", k: "watermelon" },
      { e: "🍇", k: "grapes" },
      { e: "🍓", k: "strawberry" },
      { e: "🫐", k: "blueberries" },
      { e: "🍈", k: "melon" },
      { e: "🍒", k: "cherries" },
      { e: "🍑", k: "peach" },
      { e: "🥭", k: "mango" },
      { e: "🍍", k: "pineapple" },
      { e: "🥥", k: "coconut" },
      { e: "🥝", k: "kiwi" },
      { e: "🍅", k: "tomato" },
      { e: "🍆", k: "eggplant aubergine" },
      { e: "🥑", k: "avocado" },
      { e: "🥦", k: "broccoli" },
      { e: "🥬", k: "leafy greens" },
      { e: "🥒", k: "cucumber" },
      { e: "🌶️", k: "hot pepper chili spicy" },
      { e: "🫑", k: "bell pepper" },
      { e: "🌽", k: "corn" },
      { e: "🥕", k: "carrot" },
      { e: "🫒", k: "olive" },
      { e: "🧄", k: "garlic" },
      { e: "🧅", k: "onion" },
      { e: "🥔", k: "potato" },
      { e: "🍠", k: "sweet potato" },
      { e: "🥐", k: "croissant" },
      { e: "🥯", k: "bagel" },
      { e: "🍞", k: "bread" },
      { e: "🥖", k: "baguette" },
      { e: "🥨", k: "pretzel" },
      { e: "🧀", k: "cheese" },
      { e: "🥚", k: "egg" },
      { e: "🍳", k: "cooking fried egg" },
      { e: "🧈", k: "butter" },
      { e: "🥞", k: "pancakes" },
      { e: "🧇", k: "waffle" },
      { e: "🥓", k: "bacon" },
      { e: "🥩", k: "steak meat" },
      { e: "🍗", k: "chicken leg poultry" },
      { e: "🍖", k: "meat bone" },
      { e: "🌭", k: "hot dog" },
      { e: "🍔", k: "burger hamburger" },
      { e: "🍟", k: "fries chips" },
      { e: "🍕", k: "pizza" },
      { e: "🫓", k: "flatbread" },
      { e: "🥙", k: "wrap shawarma" },
      { e: "🧆", k: "falafel" },
      { e: "🌮", k: "taco" },
      { e: "🌯", k: "burrito" },
      { e: "🥗", k: "salad" },
      { e: "🥘", k: "pan food paella" },
      { e: "🫕", k: "fondue" },
      { e: "🍝", k: "spaghetti pasta" },
      { e: "🍜", k: "ramen noodles" },
      { e: "🍲", k: "stew pot" },
      { e: "🍛", k: "curry rice" },
      { e: "🍣", k: "sushi" },
      { e: "🍱", k: "bento" },
      { e: "🥟", k: "dumpling" },
      { e: "🦪", k: "oyster" },
      { e: "🍤", k: "fried shrimp" },
      { e: "🍚", k: "rice" },
      { e: "🍥", k: "fish cake" },
      { e: "🥠", k: "fortune cookie" },
      { e: "🥮", k: "moon cake" },
      { e: "🍢", k: "oden skewer" },
      { e: "🍡", k: "dango" },
      { e: "🍧", k: "shaved ice" },
      { e: "🍨", k: "ice cream" },
      { e: "🍦", k: "soft ice cream" },
      { e: "🥧", k: "pie" },
      { e: "🧁", k: "cupcake" },
      { e: "🍰", k: "cake slice" },
      { e: "🎂", k: "birthday cake" },
      { e: "🍮", k: "custard flan" },
      { e: "🍭", k: "lollipop" },
      { e: "🍬", k: "candy sweet" },
      { e: "🍫", k: "chocolate" },
      { e: "🍿", k: "popcorn" },
      { e: "🍩", k: "doughnut donut" },
      { e: "🍪", k: "cookie biscuit" },
      { e: "🌰", k: "chestnut" },
      { e: "🥜", k: "peanuts" },
      { e: "🍯", k: "honey" },
      { e: "🥛", k: "milk glass" },
      { e: "🍼", k: "baby bottle" },
      { e: "☕", k: "coffee tea hot" },
      { e: "🫖", k: "teapot" },
      { e: "🍵", k: "green tea" },
      { e: "🧃", k: "juice box" },
      { e: "🥤", k: "cup straw soda" },
      { e: "🧋", k: "bubble tea" },
      { e: "🍶", k: "sake" },
      { e: "🍺", k: "beer" },
      { e: "🍻", k: "beers cheers" },
      { e: "🥂", k: "champagne cheers toast" },
      { e: "🍷", k: "wine" },
      { e: "🥃", k: "whisky" },
      { e: "🍸", k: "cocktail martini" },
      { e: "🍹", k: "tropical drink" },
      { e: "🧉", k: "mate" },
      { e: "🧊", k: "ice cube" },
      { e: "🥄", k: "spoon" },
      { e: "🍴", k: "fork knife" },
      { e: "🍽️", k: "plate cutlery dinner" },
      { e: "🥢", k: "chopsticks" },
      { e: "🧂", k: "salt" },
    ],
  },
  {
    id: "activity",
    label: "Activity",
    icon: "⚽",
    items: [
      { e: "⚽", k: "soccer football" },
      { e: "🏀", k: "basketball" },
      { e: "🏈", k: "american football" },
      { e: "⚾", k: "baseball" },
      { e: "🥎", k: "softball" },
      { e: "🎾", k: "tennis" },
      { e: "🏐", k: "volleyball" },
      { e: "🏉", k: "rugby" },
      { e: "🥏", k: "frisbee" },
      { e: "🎱", k: "pool billiards 8ball" },
      { e: "🪀", k: "yo-yo" },
      { e: "🏓", k: "ping pong table tennis" },
      { e: "🏸", k: "badminton" },
      { e: "🏒", k: "hockey" },
      { e: "🥍", k: "lacrosse" },
      { e: "🏏", k: "cricket" },
      { e: "🥅", k: "goal net" },
      { e: "⛳", k: "golf flag" },
      { e: "🪁", k: "kite" },
      { e: "🏹", k: "bow arrow archery" },
      { e: "🎣", k: "fishing" },
      { e: "🤿", k: "diving mask" },
      { e: "🥊", k: "boxing glove" },
      { e: "🥋", k: "martial arts karate" },
      { e: "🎽", k: "running shirt" },
      { e: "🛹", k: "skateboard" },
      { e: "🛼", k: "roller skate" },
      { e: "🛷", k: "sled" },
      { e: "⛸️", k: "ice skate" },
      { e: "🎿", k: "ski" },
      { e: "⛷️", k: "skier" },
      { e: "🏂", k: "snowboard" },
      { e: "🏋️", k: "weight lifting gym" },
      { e: "🤼", k: "wrestling" },
      { e: "🤸", k: "cartwheel gymnastics" },
      { e: "⛹️", k: "bouncing ball" },
      { e: "🤺", k: "fencing" },
      { e: "🏇", k: "horse racing" },
      { e: "🏊", k: "swim" },
      { e: "🚴", k: "cycling bike" },
      { e: "🚵", k: "mountain biking" },
      { e: "🧗", k: "climbing" },
      { e: "🏆", k: "trophy win" },
      { e: "🥇", k: "gold medal first" },
      { e: "🥈", k: "silver medal second" },
      { e: "🥉", k: "bronze medal third" },
      { e: "🏅", k: "medal" },
      { e: "🎖️", k: "military medal" },
      { e: "🎗️", k: "ribbon" },
      { e: "🎫", k: "ticket" },
      { e: "🎟️", k: "admission ticket" },
      { e: "🎪", k: "circus tent" },
      { e: "🤹", k: "juggling" },
      { e: "🎭", k: "performing arts theatre" },
      { e: "🎨", k: "art palette paint" },
      { e: "🎬", k: "clapper movie film" },
      { e: "🎤", k: "microphone sing" },
      { e: "🎧", k: "headphones" },
      { e: "🎼", k: "musical score" },
      { e: "🎵", k: "music note" },
      { e: "🎶", k: "music notes" },
      { e: "🎹", k: "piano keyboard" },
      { e: "🥁", k: "drum" },
      { e: "🎷", k: "saxophone" },
      { e: "🎺", k: "trumpet" },
      { e: "🎸", k: "guitar" },
      { e: "🪕", k: "banjo" },
      { e: "🎻", k: "violin" },
      { e: "🪗", k: "accordion" },
      { e: "🎲", k: "dice game" },
      { e: "♟️", k: "chess pawn" },
      { e: "🎯", k: "dart bullseye target" },
      { e: "🎳", k: "bowling" },
      { e: "🎮", k: "video game controller" },
      { e: "🕹️", k: "joystick" },
      { e: "🧩", k: "puzzle piece" },
      { e: "🎰", k: "slot machine" },
      { e: "🃏", k: "joker card" },
      { e: "🀄", k: "mahjong" },
      { e: "🎉", k: "party popper celebrate" },
      { e: "🎊", k: "confetti ball" },
      { e: "🎈", k: "balloon" },
      { e: "🎁", k: "gift present" },
      { e: "🎀", k: "ribbon bow" },
      { e: "🪄", k: "magic wand" },
      { e: "🧸", k: "teddy bear" },
      { e: "🎃", k: "jack o lantern halloween" },
      { e: "🎇", k: "sparkler" },
      { e: "🎆", k: "fireworks" },
      { e: "🧨", k: "firecracker" },
      { e: "🪔", k: "diya lamp" },
    ],
  },
  {
    id: "travel",
    label: "Travel",
    icon: "✈️",
    items: [
      { e: "🚗", k: "car" },
      { e: "🚕", k: "taxi" },
      { e: "🚙", k: "suv" },
      { e: "🚌", k: "bus" },
      { e: "🚎", k: "trolleybus" },
      { e: "🏎️", k: "racing car" },
      { e: "🚓", k: "police car" },
      { e: "🚑", k: "ambulance" },
      { e: "🚒", k: "fire engine" },
      { e: "🚐", k: "minibus van" },
      { e: "🛻", k: "pickup truck" },
      { e: "🚚", k: "delivery truck" },
      { e: "🚛", k: "lorry truck" },
      { e: "🚜", k: "tractor" },
      { e: "🦯", k: "white cane" },
      { e: "🦼", k: "motorized wheelchair" },
      { e: "🦽", k: "manual wheelchair" },
      { e: "🛴", k: "scooter kick" },
      { e: "🚲", k: "bicycle bike" },
      { e: "🛵", k: "motor scooter" },
      { e: "🏍️", k: "motorcycle" },
      { e: "🛺", k: "auto rickshaw tuktuk" },
      { e: "🚨", k: "siren light police" },
      { e: "🚔", k: "police car" },
      { e: "🚍", k: "bus oncoming" },
      { e: "🚝", k: "monorail" },
      { e: "🚄", k: "bullet train" },
      { e: "🚅", k: "shinkansen" },
      { e: "🚈", k: "light rail" },
      { e: "🚂", k: "locomotive steam train" },
      { e: "🚆", k: "train" },
      { e: "🚇", k: "metro subway" },
      { e: "🚊", k: "tram" },
      { e: "🚉", k: "station" },
      { e: "✈️", k: "airplane flight fly" },
      { e: "🛫", k: "departure takeoff" },
      { e: "🛬", k: "arrival landing" },
      { e: "🛩️", k: "small plane" },
      { e: "💺", k: "seat" },
      { e: "🚁", k: "helicopter" },
      { e: "🚟", k: "suspension railway" },
      { e: "🚠", k: "cable car" },
      { e: "🛰️", k: "satellite" },
      { e: "🚀", k: "rocket launch" },
      { e: "🛸", k: "flying saucer ufo" },
      { e: "🛶", k: "canoe" },
      { e: "⛵", k: "sailboat" },
      { e: "🛥️", k: "motor boat" },
      { e: "🚤", k: "speedboat" },
      { e: "🛳️", k: "passenger ship" },
      { e: "⛴️", k: "ferry" },
      { e: "🚢", k: "ship" },
      { e: "⚓", k: "anchor" },
      { e: "🪝", k: "hook" },
      { e: "⛽", k: "fuel pump gas" },
      { e: "🚏", k: "bus stop" },
      { e: "🚦", k: "traffic light" },
      { e: "🚧", k: "construction" },
      { e: "🗺️", k: "world map" },
      { e: "🧭", k: "compass" },
      { e: "🗿", k: "moai statue" },
      { e: "🗽", k: "statue of liberty" },
      { e: "🗼", k: "tokyo tower" },
      { e: "🏰", k: "castle" },
      { e: "🏯", k: "japanese castle" },
      { e: "🏟️", k: "stadium" },
      { e: "🎡", k: "ferris wheel" },
      { e: "🎢", k: "roller coaster" },
      { e: "🎠", k: "carousel" },
      { e: "⛲", k: "fountain" },
      { e: "⛱️", k: "beach umbrella" },
      { e: "🏖️", k: "beach" },
      { e: "🏝️", k: "desert island" },
      { e: "🏜️", k: "desert" },
      { e: "🌋", k: "volcano" },
      { e: "⛰️", k: "mountain" },
      { e: "🏔️", k: "snow mountain" },
      { e: "🗻", k: "mount fuji" },
      { e: "🏕️", k: "camping" },
      { e: "⛺", k: "tent" },
      { e: "🏠", k: "house home" },
      { e: "🏡", k: "house garden" },
      { e: "🏘️", k: "houses" },
      { e: "🏢", k: "office building" },
      { e: "🏬", k: "department store" },
      { e: "🏣", k: "post office" },
      { e: "🏤", k: "post office european" },
      { e: "🏥", k: "hospital" },
      { e: "🏦", k: "bank" },
      { e: "🏨", k: "hotel" },
      { e: "🏪", k: "convenience store" },
      { e: "🏫", k: "school" },
      { e: "🏩", k: "love hotel" },
      { e: "💒", k: "wedding chapel" },
      { e: "🕌", k: "mosque" },
      { e: "🕍", k: "synagogue" },
      { e: "⛪", k: "church" },
      { e: "🛕", k: "hindu temple" },
      { e: "🕋", k: "kaaba" },
      { e: "🌁", k: "foggy" },
      { e: "🌃", k: "night stars city" },
      { e: "🏙️", k: "cityscape" },
      { e: "🌄", k: "sunrise mountains" },
      { e: "🌅", k: "sunrise" },
      { e: "🌆", k: "dusk city" },
      { e: "🌇", k: "sunset" },
      { e: "🌉", k: "bridge night" },
      { e: "♨️", k: "hot springs" },
      { e: "🎑", k: "moon viewing" },
      { e: "🧳", k: "luggage suitcase" },
    ],
  },
  {
    id: "objects",
    label: "Objects",
    icon: "💡",
    items: [
      { e: "⌚", k: "watch" },
      { e: "📱", k: "mobile phone" },
      { e: "📲", k: "phone arrow call" },
      { e: "💻", k: "laptop computer" },
      { e: "⌨️", k: "keyboard" },
      { e: "🖥️", k: "desktop computer" },
      { e: "🖨️", k: "printer" },
      { e: "🖱️", k: "mouse computer" },
      { e: "💽", k: "minidisc" },
      { e: "💾", k: "floppy save" },
      { e: "💿", k: "cd" },
      { e: "📀", k: "dvd" },
      { e: "🧮", k: "abacus" },
      { e: "🎥", k: "movie camera" },
      { e: "📽️", k: "film projector" },
      { e: "📺", k: "tv television" },
      { e: "📷", k: "camera photo" },
      { e: "📸", k: "camera flash" },
      { e: "📹", k: "video camera" },
      { e: "📼", k: "videocassette" },
      { e: "🔍", k: "search magnify" },
      { e: "🔎", k: "search magnify right" },
      { e: "🕯️", k: "candle" },
      { e: "💡", k: "light bulb idea" },
      { e: "🔦", k: "flashlight torch" },
      { e: "🏮", k: "lantern" },
      { e: "📔", k: "notebook" },
      { e: "📕", k: "closed book" },
      { e: "📖", k: "open book read" },
      { e: "📚", k: "books" },
      { e: "📓", k: "notebook" },
      { e: "📒", k: "ledger" },
      { e: "📃", k: "page curl" },
      { e: "📄", k: "page document" },
      { e: "📰", k: "newspaper news" },
      { e: "📑", k: "bookmark tabs" },
      { e: "🔖", k: "bookmark" },
      { e: "🏷️", k: "label tag" },
      { e: "💰", k: "money bag" },
      { e: "🪙", k: "coin" },
      { e: "💴", k: "yen" },
      { e: "💵", k: "dollar" },
      { e: "💶", k: "euro" },
      { e: "💷", k: "pound" },
      { e: "💸", k: "money wings" },
      { e: "💳", k: "credit card" },
      { e: "🧾", k: "receipt" },
      { e: "💹", k: "chart up yen" },
      { e: "✉️", k: "envelope email mail" },
      { e: "📧", k: "e-mail" },
      { e: "📨", k: "incoming envelope" },
      { e: "📩", k: "envelope arrow" },
      { e: "📤", k: "outbox" },
      { e: "📥", k: "inbox" },
      { e: "📦", k: "package box" },
      { e: "📫", k: "mailbox" },
      { e: "📮", k: "postbox" },
      { e: "🗳️", k: "ballot box vote" },
      { e: "✏️", k: "pencil write" },
      { e: "✒️", k: "pen nib" },
      { e: "🖋️", k: "fountain pen" },
      { e: "🖊️", k: "pen" },
      { e: "🖌️", k: "paintbrush" },
      { e: "🖍️", k: "crayon" },
      { e: "📝", k: "memo note write" },
      { e: "💼", k: "briefcase work" },
      { e: "📁", k: "folder" },
      { e: "📂", k: "open folder" },
      { e: "🗂️", k: "card index dividers" },
      { e: "📅", k: "calendar date" },
      { e: "📆", k: "tear off calendar" },
      { e: "🗒️", k: "spiral notepad" },
      { e: "🗓️", k: "spiral calendar" },
      { e: "📇", k: "card index" },
      { e: "📈", k: "chart up" },
      { e: "📉", k: "chart down" },
      { e: "📊", k: "bar chart" },
      { e: "📋", k: "clipboard" },
      { e: "📌", k: "pushpin" },
      { e: "📍", k: "round pushpin location" },
      { e: "📎", k: "paperclip attach" },
      { e: "🖇️", k: "linked paperclips" },
      { e: "📏", k: "ruler" },
      { e: "📐", k: "triangular ruler" },
      { e: "✂️", k: "scissors cut" },
      { e: "🗃️", k: "card file box" },
      { e: "🗄️", k: "file cabinet" },
      { e: "🗑️", k: "wastebasket trash delete" },
      { e: "🔒", k: "lock closed" },
      { e: "🔓", k: "lock open unlock" },
      { e: "🔏", k: "lock pen" },
      { e: "🔐", k: "lock key" },
      { e: "🔑", k: "key" },
      { e: "🗝️", k: "old key" },
      { e: "🔨", k: "hammer" },
      { e: "🪓", k: "axe" },
      { e: "⛏️", k: "pick" },
      { e: "🛠️", k: "hammer wrench tools" },
      { e: "🗡️", k: "dagger" },
      { e: "⚔️", k: "crossed swords" },
      { e: "🛡️", k: "shield" },
      { e: "🔧", k: "wrench" },
      { e: "🔩", k: "nut bolt" },
      { e: "⚙️", k: "gear settings" },
      { e: "🗜️", k: "clamp" },
      { e: "⚖️", k: "balance scale justice" },
      { e: "🦯", k: "cane" },
      { e: "🔗", k: "link chain" },
      { e: "⛓️", k: "chains" },
      { e: "🧰", k: "toolbox" },
      { e: "🧲", k: "magnet" },
      { e: "🪜", k: "ladder" },
      { e: "🧪", k: "test tube" },
      { e: "🧫", k: "petri dish" },
      { e: "🧬", k: "dna" },
      { e: "🔬", k: "microscope" },
      { e: "🔭", k: "telescope" },
      { e: "📡", k: "satellite antenna" },
      { e: "💊", k: "pill medicine" },
      { e: "💉", k: "syringe injection" },
      { e: "🩸", k: "blood drop" },
      { e: "🩹", k: "bandage plaster" },
      { e: "🩺", k: "stethoscope" },
      { e: "🚪", k: "door" },
      { e: "🛗", k: "elevator lift" },
      { e: "🪑", k: "chair" },
      { e: "🚽", k: "toilet" },
      { e: "🚿", k: "shower" },
      { e: "🛁", k: "bathtub" },
      { e: "🧴", k: "lotion bottle" },
      { e: "🧷", k: "safety pin" },
      { e: "🧹", k: "broom" },
      { e: "🧺", k: "basket" },
      { e: "🧻", k: "toilet paper roll" },
      { e: "🧼", k: "soap" },
      { e: "🪥", k: "toothbrush" },
      { e: "🧽", k: "sponge" },
      { e: "🧯", k: "fire extinguisher" },
      { e: "🛒", k: "shopping cart trolley" },
      { e: "🚬", k: "cigarette" },
      { e: "⚰️", k: "coffin" },
      { e: "🪦", k: "headstone grave" },
      { e: "🏺", k: "amphora" },
      { e: "👓", k: "glasses" },
      { e: "🕶️", k: "sunglasses" },
      { e: "🥽", k: "goggles" },
      { e: "🥼", k: "lab coat" },
      { e: "🦺", k: "safety vest" },
      { e: "👔", k: "necktie" },
      { e: "👕", k: "t-shirt" },
      { e: "👖", k: "jeans" },
      { e: "🧣", k: "scarf" },
      { e: "🧤", k: "gloves" },
      { e: "🧥", k: "coat" },
      { e: "🧦", k: "socks" },
      { e: "👗", k: "dress" },
      { e: "👘", k: "kimono" },
      { e: "🥻", k: "sari" },
      { e: "🩴", k: "flip flops sandal" },
      { e: "👙", k: "bikini" },
      { e: "👚", k: "blouse" },
      { e: "👛", k: "purse" },
      { e: "👜", k: "handbag" },
      { e: "👝", k: "clutch bag" },
      { e: "🎒", k: "backpack school bag" },
      { e: "👞", k: "mans shoe" },
      { e: "👟", k: "sneaker trainer" },
      { e: "🥾", k: "hiking boot" },
      { e: "👠", k: "high heel" },
      { e: "👡", k: "sandal" },
      { e: "👢", k: "boot" },
      { e: "👑", k: "crown king queen" },
      { e: "👒", k: "womans hat" },
      { e: "🎩", k: "top hat" },
      { e: "🎓", k: "graduation cap" },
      { e: "🧢", k: "billed cap" },
      { e: "⛑️", k: "rescue helmet" },
      { e: "📿", k: "prayer beads" },
      { e: "💎", k: "gem diamond" },
      { e: "🔋", k: "battery" },
      { e: "🪫", k: "low battery" },
      { e: "🔌", k: "plug electric" },
      { e: "🧿", k: "nazar amulet evil eye" },
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    icon: "✅",
    items: [
      { e: "✅", k: "check tick yes done" },
      { e: "☑️", k: "checkbox checked" },
      { e: "✔️", k: "check mark" },
      { e: "❌", k: "cross no wrong" },
      { e: "❎", k: "cross button" },
      { e: "➕", k: "plus add" },
      { e: "➖", k: "minus" },
      { e: "➗", k: "divide" },
      { e: "✖️", k: "multiply" },
      { e: "🟰", k: "equals" },
      { e: "💯", k: "hundred percent perfect" },
      { e: "❗", k: "exclamation" },
      { e: "❓", k: "question" },
      { e: "❔", k: "question white" },
      { e: "❕", k: "exclamation white" },
      { e: "‼️", k: "double exclamation" },
      { e: "⁉️", k: "exclamation question" },
      { e: "⚠️", k: "warning caution" },
      { e: "🚫", k: "prohibited no" },
      { e: "⛔", k: "no entry" },
      { e: "🔞", k: "eighteen no minors" },
      { e: "📵", k: "no phones" },
      { e: "🚭", k: "no smoking" },
      { e: "🔕", k: "mute bell off" },
      { e: "🔔", k: "bell notification" },
      { e: "📢", k: "loudspeaker announce" },
      { e: "📣", k: "megaphone cheer" },
      { e: "🔊", k: "speaker loud volume" },
      { e: "🔉", k: "speaker medium" },
      { e: "🔈", k: "speaker low" },
      { e: "🔇", k: "muted speaker" },
      { e: "📞", k: "telephone receiver call" },
      { e: "☎️", k: "telephone phone" },
      { e: "📴", k: "phone off" },
      { e: "📳", k: "vibration mode" },
      { e: "💬", k: "speech balloon chat message" },
      { e: "💭", k: "thought balloon" },
      { e: "🗯️", k: "anger bubble" },
      { e: "🗨️", k: "left speech bubble" },
      { e: "♻️", k: "recycle" },
      { e: "⚕️", k: "medical" },
      { e: "☢️", k: "radioactive" },
      { e: "☣️", k: "biohazard" },
      { e: "🔱", k: "trident" },
      { e: "⚜️", k: "fleur de lis" },
      { e: "🔰", k: "beginner" },
      { e: "✳️", k: "asterisk" },
      { e: "❇️", k: "sparkle" },
      { e: "🆔", k: "id" },
      { e: "🆕", k: "new" },
      { e: "🆓", k: "free" },
      { e: "🆗", k: "ok button" },
      { e: "🆙", k: "up" },
      { e: "🆒", k: "cool button" },
      { e: "🆖", k: "ng" },
      { e: "🈯", k: "reserved" },
      { e: "🅿️", k: "parking" },
      { e: "♿", k: "wheelchair accessible" },
      { e: "🚹", k: "mens room" },
      { e: "🚺", k: "womens room" },
      { e: "🚻", k: "restroom" },
      { e: "🚼", k: "baby symbol" },
      { e: "🛜", k: "wireless wifi" },
      { e: "🔴", k: "red circle" },
      { e: "🟠", k: "orange circle" },
      { e: "🟡", k: "yellow circle" },
      { e: "🟢", k: "green circle" },
      { e: "🔵", k: "blue circle" },
      { e: "🟣", k: "purple circle" },
      { e: "⚫", k: "black circle" },
      { e: "⚪", k: "white circle" },
      { e: "🟤", k: "brown circle" },
      { e: "🟥", k: "red square" },
      { e: "🟧", k: "orange square" },
      { e: "🟨", k: "yellow square" },
      { e: "🟩", k: "green square" },
      { e: "🟦", k: "blue square" },
      { e: "🟪", k: "purple square" },
      { e: "⬛", k: "black square" },
      { e: "⬜", k: "white square" },
      { e: "🔶", k: "orange diamond" },
      { e: "🔷", k: "blue diamond" },
      { e: "🔸", k: "small orange diamond" },
      { e: "🔹", k: "small blue diamond" },
      { e: "🔺", k: "red triangle up" },
      { e: "🔻", k: "red triangle down" },
      { e: "💠", k: "diamond dot" },
      { e: "🔘", k: "radio button" },
      { e: "⭕", k: "hollow red circle" },
      { e: "🕐", k: "clock one" },
      { e: "⏰", k: "alarm clock" },
      { e: "⏱️", k: "stopwatch" },
      { e: "⏲️", k: "timer" },
      { e: "🕰️", k: "mantelpiece clock" },
      { e: "⌛", k: "hourglass done" },
      { e: "⏳", k: "hourglass" },
      { e: "♈", k: "aries" },
      { e: "♉", k: "taurus" },
      { e: "♊", k: "gemini" },
      { e: "♋", k: "cancer" },
      { e: "♌", k: "leo" },
      { e: "♍", k: "virgo" },
      { e: "♎", k: "libra" },
      { e: "♏", k: "scorpio" },
      { e: "♐", k: "sagittarius" },
      { e: "♑", k: "capricorn" },
      { e: "♒", k: "aquarius" },
      { e: "♓", k: "pisces" },
      { e: "⛎", k: "ophiuchus" },
      { e: "☮️", k: "peace" },
      { e: "☯️", k: "yin yang" },
      { e: "☪️", k: "star crescent islam" },
      { e: "✝️", k: "latin cross" },
      { e: "☦️", k: "orthodox cross" },
      { e: "🕎", k: "menorah" },
      { e: "🔯", k: "six pointed star" },
      { e: "🛐", k: "place of worship" },
      { e: "🎦", k: "cinema" },
      { e: "📶", k: "signal bars" },
      { e: "🔅", k: "dim brightness" },
      { e: "🔆", k: "bright brightness" },
      { e: "🔄", k: "refresh sync arrows" },
      { e: "🔁", k: "repeat loop" },
      { e: "🔂", k: "repeat one" },
      { e: "▶️", k: "play" },
      { e: "⏸️", k: "pause" },
      { e: "⏹️", k: "stop" },
      { e: "⏺️", k: "record" },
      { e: "⏭️", k: "next track skip" },
      { e: "⏮️", k: "previous track" },
      { e: "⏩", k: "fast forward" },
      { e: "⏪", k: "rewind" },
      { e: "🔼", k: "up button" },
      { e: "🔽", k: "down button" },
      { e: "⬆️", k: "up arrow" },
      { e: "⬇️", k: "down arrow" },
      { e: "⬅️", k: "left arrow" },
      { e: "➡️", k: "right arrow" },
      { e: "↗️", k: "up right arrow" },
      { e: "↘️", k: "down right arrow" },
      { e: "↙️", k: "down left arrow" },
      { e: "↖️", k: "up left arrow" },
      { e: "↕️", k: "up down arrow" },
      { e: "↔️", k: "left right arrow" },
      { e: "↩️", k: "right arrow curving left reply" },
      { e: "↪️", k: "left arrow curving right forward" },
      { e: "🔃", k: "clockwise arrows" },
      { e: "#️⃣", k: "hash keycap" },
      { e: "*️⃣", k: "asterisk keycap" },
      { e: "0️⃣", k: "zero" },
      { e: "1️⃣", k: "one" },
      { e: "2️⃣", k: "two" },
      { e: "3️⃣", k: "three" },
      { e: "4️⃣", k: "four" },
      { e: "5️⃣", k: "five" },
      { e: "6️⃣", k: "six" },
      { e: "7️⃣", k: "seven" },
      { e: "8️⃣", k: "eight" },
      { e: "9️⃣", k: "nine" },
      { e: "🔟", k: "ten" },
    ],
  },
  {
    id: "flags",
    label: "Flags",
    icon: "🏳️",
    items: [
      { e: "🏳️", k: "white flag" },
      { e: "🏴", k: "black flag" },
      { e: "🏁", k: "chequered flag finish race" },
      { e: "🚩", k: "triangular flag" },
      { e: "🏳️‍🌈", k: "rainbow flag pride" },
      { e: "🇦🇪", k: "uae emirates" },
      { e: "🇸🇦", k: "saudi arabia" },
      { e: "🇶🇦", k: "qatar" },
      { e: "🇰🇼", k: "kuwait" },
      { e: "🇧🇭", k: "bahrain" },
      { e: "🇴🇲", k: "oman" },
      { e: "🇪🇬", k: "egypt" },
      { e: "🇯🇴", k: "jordan" },
      { e: "🇱🇧", k: "lebanon" },
      { e: "🇸🇾", k: "syria" },
      { e: "🇮🇶", k: "iraq" },
      { e: "🇾🇪", k: "yemen" },
      { e: "🇵🇸", k: "palestine" },
      { e: "🇲🇦", k: "morocco" },
      { e: "🇩🇿", k: "algeria" },
      { e: "🇹🇳", k: "tunisia" },
      { e: "🇱🇾", k: "libya" },
      { e: "🇸🇩", k: "sudan" },
      { e: "🇹🇷", k: "turkey" },
      { e: "🇮🇷", k: "iran" },
      { e: "🇵🇰", k: "pakistan" },
      { e: "🇮🇳", k: "india" },
      { e: "🇧🇩", k: "bangladesh" },
      { e: "🇱🇰", k: "sri lanka" },
      { e: "🇳🇵", k: "nepal" },
      { e: "🇵🇭", k: "philippines" },
      { e: "🇮🇩", k: "indonesia" },
      { e: "🇲🇾", k: "malaysia" },
      { e: "🇸🇬", k: "singapore" },
      { e: "🇹🇭", k: "thailand" },
      { e: "🇻🇳", k: "vietnam" },
      { e: "🇨🇳", k: "china" },
      { e: "🇯🇵", k: "japan" },
      { e: "🇰🇷", k: "south korea" },
      { e: "🇬🇧", k: "united kingdom uk britain" },
      { e: "🇺🇸", k: "united states usa america" },
      { e: "🇨🇦", k: "canada" },
      { e: "🇲🇽", k: "mexico" },
      { e: "🇧🇷", k: "brazil" },
      { e: "🇦🇷", k: "argentina" },
      { e: "🇫🇷", k: "france" },
      { e: "🇩🇪", k: "germany" },
      { e: "🇮🇹", k: "italy" },
      { e: "🇪🇸", k: "spain" },
      { e: "🇵🇹", k: "portugal" },
      { e: "🇳🇱", k: "netherlands" },
      { e: "🇧🇪", k: "belgium" },
      { e: "🇨🇭", k: "switzerland" },
      { e: "🇦🇹", k: "austria" },
      { e: "🇸🇪", k: "sweden" },
      { e: "🇳🇴", k: "norway" },
      { e: "🇩🇰", k: "denmark" },
      { e: "🇫🇮", k: "finland" },
      { e: "🇵🇱", k: "poland" },
      { e: "🇷🇺", k: "russia" },
      { e: "🇺🇦", k: "ukraine" },
      { e: "🇬🇷", k: "greece" },
      { e: "🇷🇴", k: "romania" },
      { e: "🇿🇦", k: "south africa" },
      { e: "🇳🇬", k: "nigeria" },
      { e: "🇰🇪", k: "kenya" },
      { e: "🇪🇹", k: "ethiopia" },
      { e: "🇦🇺", k: "australia" },
      { e: "🇳🇿", k: "new zealand" },
    ],
  },
];

/**
 * The six glyphs offered as one-tap reactions.
 *
 * Deliberately short: a quick-reaction row is for the tap you make without
 * thinking, and a wall of choices defeats that. The full catalogue is one tap
 * further in. Ordered by how often people actually reach for them.
 */
export const REACTION_QUICK = ["❤️", "😂", "😮", "😢", "👍", "🔥"] as const;

/**
 * Every glyph, flat and DEDUPED. Built lazily so an unused import costs nothing.
 *
 * A few glyphs are deliberately cross-listed — 🧗 is both a person and an
 * activity, 😻 is both a smiley and a heart — because somebody looking for a
 * climber will look in either tab. That is right for browsing and wrong for a
 * flat list, where a repeat becomes a duplicate React key.
 */
let flatCache: string[] | null = null;
export function allEmoji(): string[] {
  if (!flatCache) flatCache = Array.from(new Set(EMOJI_GROUPS.flatMap((g) => g.items.map((i) => i.e))));
  return flatCache;
}

/** How many glyphs the catalogue carries — used by tests and the picker's label. */
export function emojiCount(): number {
  return allEmoji().length;
}

/**
 * Keyword search.
 *
 * Matches a whole keyword or a keyword PREFIX ("lau" -> "laugh"), never an
 * infix: an infix match on two-letter queries returns most of the catalogue,
 * which is indistinguishable from no filter. An empty query returns [] rather
 * than everything, so the caller can tell "not searching" from "no results".
 */
export function searchEmoji(query: string, limit = 120): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  // Deduped: a cross-listed glyph (🧗 is under both People and Activity) would
  // otherwise appear twice in one result grid, which is a duplicate React key.
  const seen = new Set<string>();
  const out: string[] = [];
  for (const g of EMOJI_GROUPS) {
    for (const it of g.items) {
      if (seen.has(it.e)) continue;
      // The glyph itself matches, so pasting an emoji into the box finds it.
      if (it.e === q || it.k.split(" ").some((w) => w.startsWith(q))) {
        seen.add(it.e);
        out.push(it.e);
        if (out.length >= limit) return out;
      }
    }
  }
  return out;
}

/**
 * Is this string a SINGLE emoji? Used to decide whether a reply is a one-tap
 * reaction (rendered as one large glyph) or a sentence.
 *
 * Deliberately narrower than `isEmojiOnly` in Messages.tsx, which admits up to
 * ~8 composed glyphs because a whole bubble of "😂😂😂" should still render big.
 * Here the question is "did they tap a reaction button", and that is exactly one.
 *
 * Built through the RegExp CONSTRUCTOR, not a literal: `\p{…}` property escapes
 * need the `u` flag, and a `u`-flagged literal trips TS1501 against this repo's
 * downlevel target (the same workaround `Messages.tsx:172` already uses). The
 * try/catch covers an engine without Unicode property escapes at all.
 */
export function isSingleEmoji(body: string | null | undefined): boolean {
  const s = (body ?? "").trim();
  if (!s || s.length > 24) return false;
  try {
    // ‍ = ZWJ, ️ = variation selector — a flag or "heart on fire" is
    // several code points joined by them, and is still ONE glyph.
    const re = new RegExp(
      "^(?:\\p{Extended_Pictographic}|\\p{Emoji_Component}|\\u200d|\\ufe0f)+$",
      "u"
    );
    if (!re.test(s)) return false;
    // One composed glyph, so segment rather than counting code points.
    const Seg = (Intl as unknown as { Segmenter?: new (l?: string, o?: object) => { segment(s: string): Iterable<unknown> } }).Segmenter;
    if (Seg) return Array.from(new Seg(undefined, { granularity: "grapheme" }).segment(s)).length === 1;
    return true; // no Segmenter: the regex already proved it is emoji-only
  } catch {
    return false;
  }
}
