import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { SESSION_REHYDRATE_JS, SESSION_PERSIST_JS, INJECTED_BEFORE_JS } from "../lib/injected-scripts";

const ROOT = resolve(__dirname, "..");
const read = (p: string) => readFileSync(resolve(ROOT, p), "utf8");

/* ────────────────────────────────────────────────────────────────────────────
 * 1. `call_cancel` dismissed whichever call was ringing, not the one it named.
 *
 * There is ONE notification id (7788), so a second incoming call replaces the
 * first one's notification. A late cancel for the replaced call then silenced
 * the call that was actually ringing: the ring vanishes mid-air and the second
 * caller waits out the timeout for nobody.
 *
 * Kotlin source is generated by an Expo config plugin, so it is checked as
 * source rather than executed — there is no device here.
 * ────────────────────────────────────────────────────────────────────────── */
describe("a cancel names the call it cancels", () => {
  const PLUGIN = read("plugins/with-android-fcm-call.js");
  /** Plugin comments discuss the very shapes asserted against; strip them. */
  const code = PLUGIN.split("\n")
    .filter((l) => !/^\s*(\*|\/\/|\/\*)/.test(l))
    .join("\n");

  it("the cancel handler receives the push data at all", () => {
    // It used to take no arguments, so `callId` was unreachable by construction.
    expect(code).toMatch(/"call_cancel" -> handleCallCancel\(data\)/);
    expect(code).toMatch(/private fun handleCallCancel\(data: Map<String, String>\)/);
    expect(code).not.toMatch(/private fun handleCallCancel\(\)/);
  });

  it("a cancel for a different known call is ignored", () => {
    expect(code).toMatch(
      /if \(target\.isNotEmpty\(\) && ringing\.isNotEmpty\(\) && target != ringing\) return/,
    );
  });

  it("an unnamed cancel still dismisses — a stuck ring is the worse failure", () => {
    // Both sides of the guard require a non-empty value, so an old server that
    // sends no callId, or a cold process with no record, still gets through.
    const guard = code.slice(code.indexOf("private fun handleCallCancel"));
    expect(guard.slice(0, 800)).toMatch(/target\.isNotEmpty\(\) && ringing\.isNotEmpty\(\)/);
  });

  it("the ringing id survives the messaging process being torn down", () => {
    // A static field would be lost between two pushes; the record has to outlive
    // the process or the guard silently degrades to the old behaviour.
    expect(code).toMatch(/private fun setRingingCallId\(id: String\)/);
    expect(code).toMatch(/getSharedPreferences\("relay_push", Context\.MODE_PRIVATE\)/);
    expect(code).toMatch(/putString\("ringing_call_id"/);
  });

  it("the record is set when a call starts ringing and cleared on every exit", () => {
    expect(code).toMatch(/nm\.notify\(NOTIFICATION_ID, notification\)\s*\n\s*setRingingCallId\(callId\)/);
    // Answer/decline from the notification, from the full-screen UI, and the
    // web app ending the call — each has to clear it, or a later cancel for a
    // DIFFERENT call is judged against a dead id and dropped.
    const cleared = code.match(/putString\("ringing_call_id", ""\)/g) ?? [];
    expect(cleared.length).toBeGreaterThanOrEqual(3);
  });

  it("the activity only tears down for the call it is showing", () => {
    const receiver = code.slice(
      code.indexOf("private val cancelReceiver"),
      code.indexOf("override fun onCreate"),
    );
    expect(receiver).toMatch(/target != callId\) return/);
    expect(receiver).toMatch(/stopRinging\(\)/);
  });

  it("the CALL_CANCEL broadcast stays inside the app and names the call", () => {
    // A custom-action broadcast with no package restriction is readable by any
    // app that registers for it, and on pre-33 it can also be SENT by one.
    const sends = code.match(/Intent\("[^"]*\.CALL_CANCEL"\)[\s\S]{0,200}?\}\)?/g) ?? [];
    expect(sends.length).toBeGreaterThanOrEqual(2);
    for (const s of sends) {
      expect(s, s).toMatch(/setPackage\(/);
      expect(s, s).toMatch(/putExtra\(/);
    }
  });
});

/* ────────────────────────────────────────────────────────────────────────────
 * 2. The session was restored AFTER the page had already decided it was gone.
 * ────────────────────────────────────────────────────────────────────────── */

/** Run injected session JS against a storage pair; return the resulting session. */
function runSession(js: string, local: Record<string, string>, session: Record<string, string>) {
  const mkStore = (backing: Record<string, string>) => ({
    getItem: (k: string) => (k in backing ? backing[k] : null),
    setItem: (k: string, v: string) => {
      backing[k] = String(v);
    },
    removeItem: (k: string) => {
      delete backing[k];
    },
    key: (i: number) => Object.keys(backing)[i] ?? null,
    get length() {
      return Object.keys(backing).length;
    },
  });
  const win: any = { addEventListener() {} };
  const doc: any = { addEventListener() {}, visibilityState: "visible" };
  // eslint-disable-next-line @typescript-eslint/no-implied-eval
  new Function("window", "document", "localStorage", "sessionStorage", "setInterval", js)(
    win,
    doc,
    mkStore(local),
    mkStore(session),
    () => 0,
  );
  return { session, local, win };
}

describe("the session is restored before the page reads it", () => {
  const SAVED = JSON.stringify({ relay_token: "tok-1", relay_pin: "4821" });

  it("the early script alone restores the session", () => {
    const { session } = runSession(SESSION_REHYDRATE_JS, { __relay_ss__: SAVED }, {});
    expect(session).toEqual({ relay_token: "tok-1", relay_pin: "4821" });
  });

  it("it never overwrites a value the page already has", () => {
    // Otherwise a sign-out is undone by the last snapshot taken before it.
    const { session } = runSession(SESSION_REHYDRATE_JS, { __relay_ss__: SAVED }, { relay_token: "live" });
    expect(session.relay_token).toBe("live");
    expect(session.relay_pin).toBe("4821");
  });

  it("running it twice changes nothing", () => {
    const local = { __relay_ss__: SAVED };
    const session: Record<string, string> = {};
    runSession(SESSION_REHYDRATE_JS, local, session);
    const after = { ...session };
    runSession(SESSION_REHYDRATE_JS, local, session);
    expect(session).toEqual(after);
  });

  it("survives absent or corrupt storage instead of throwing into the page", () => {
    expect(() => runSession(SESSION_REHYDRATE_JS, {}, {})).not.toThrow();
    expect(() => runSession(SESSION_REHYDRATE_JS, { __relay_ss__: "{not json" }, {})).not.toThrow();
  });

  it("it is what the WebView injects before content loads", () => {
    expect(INJECTED_BEFORE_JS).toBe(SESSION_REHYDRATE_JS);
    const VIEW = read("components/relay-webview.tsx");
    expect(VIEW).toMatch(/injectedJavaScriptBeforeContentLoaded=\{INJECTED_BEFORE_JS\}/);
  });

  it("touches no DOM — there may not be a body yet at that point", () => {
    expect(SESSION_REHYDRATE_JS).not.toMatch(/document\.(body|createElement|querySelector)/);
  });

  it("the late script still restores if the early hook never ran", () => {
    // react-native-webview lands the before-content hook at onPageStarted on
    // Android, which is early but not contractually before the page's scripts.
    const { session } = runSession(SESSION_PERSIST_JS, { __relay_ss__: SAVED }, {});
    expect(session.relay_token).toBe("tok-1");
  });

  it("the late script defers to the early one when it is present", () => {
    const { win } = runSession(SESSION_REHYDRATE_JS, { __relay_ss__: SAVED }, {});
    expect(typeof win.__relayRehydrate).toBe("function");
    expect(SESSION_PERSIST_JS).toMatch(/typeof window\.__relayRehydrate === 'function'/);
  });

  it("the snapshot side still runs at document-end, where the page is live", () => {
    expect(SESSION_PERSIST_JS).toMatch(/setInterval\(snapshot, 5000\)/);
    expect(SESSION_REHYDRATE_JS).not.toMatch(/setInterval/);
  });
});
