import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";

/**
 * v2.5.0 — Landing page designed by gemini-3.5-flash.
 *
 * These tests pin the *invariants* of the generated file (asset paths, sections,
 * scroll-loop primitives, byline) plus the pure scroll-math the page relies on,
 * without booting the full component.
 */

const HOME_TSX = fs.readFileSync(
  path.resolve(__dirname, "Home.tsx"),
  "utf8",
);

// ---------------------------------------------------------------------------
// 1. Static analysis of client/src/pages/Home.tsx
// ---------------------------------------------------------------------------
describe("Home.tsx — generated by gemini-3.5-flash", () => {
  it("default-exports a Home component", () => {
    expect(HOME_TSX).toMatch(/export\s+default\s+function\s+Home/);
  });

  it("uses requestAnimationFrame to drive the scroll loop", () => {
    expect(HOME_TSX).toMatch(/requestAnimationFrame/);
  });

  it("respects prefers-reduced-motion via matchMedia", () => {
    expect(HOME_TSX).toMatch(/prefers-reduced-motion/);
    expect(HOME_TSX).toMatch(/matchMedia/);
  });

  it("attaches a passive scroll listener to window", () => {
    expect(HOME_TSX).toMatch(/addEventListener\(['"]scroll['"]/);
    expect(HOME_TSX).toMatch(/passive:\s*true/);
  });

  it("renders the v2.22.1 copyright footer with the gemini-3.5-flash byline", () => {
    expect(HOME_TSX).toMatch(/v2\.22\.1/);
    expect(HOME_TSX).toMatch(/©\s*20\d\d\s*RELAY/);
    expect(HOME_TSX).toMatch(/gemini-3\.5-flash/);
  });

  it("links the primary CTA to /app", () => {
    expect(HOME_TSX).toMatch(/href=["']\/app["']/);
  });

  it("includes the BROWSER CALLS kicker and END OF SCROLL finale labels", () => {
    expect(HOME_TSX).toMatch(/BROWSER CALLS/);
    expect(HOME_TSX).toMatch(/END OF SCROLL/);
  });

  it("renders six story sections with stable ids section-1..section-6", () => {
    for (let i = 1; i <= 6; i++) {
      expect(HOME_TSX).toContain(`section-${i}`);
    }
  });

  it("includes every section heading verbatim", () => {
    for (const heading of [
      "Your number",
      "Live check",
      "Messages",
      "Notes to self",
      "Contacts",
      "Profile",
    ]) {
      expect(HOME_TSX).toContain(heading);
    }
  });

  it("uses the literal scrollY > 480 sticky-CTA threshold so future regressions are caught", () => {
    expect(HOME_TSX).toMatch(/scrollY\s*>\s*480/);
  });

  it("renders a faux device bezel (PhoneBezel) reused for every story section", () => {
    expect(HOME_TSX).toMatch(/PhoneBezel/);
    // and references it inside the SECTIONS_DATA mapping
    expect(HOME_TSX).toMatch(/SECTIONS_DATA\.map/);
  });
});

// ---------------------------------------------------------------------------
// 2. Asset URLs — every screenshot must be the real /manus-storage/ ref
// ---------------------------------------------------------------------------
const REAL_SCREENSHOT_PATHS = [
  "/manus-storage/dialer-empty_98fa535c.png",
  "/manus-storage/dialer-typed_8ad4c6c2.png",
  "/manus-storage/messages-empty_014c8014.png",
  "/manus-storage/messages-thread_3b435df8.png",
  "/manus-storage/contacts-empty_ee775a4f.png",
  "/manus-storage/profile_15ca08be.png",
];

describe("Home.tsx — real screenshot assets", () => {
  it("references every required /manus-storage/ asset at least once", () => {
    for (const p of REAL_SCREENSHOT_PATHS) {
      const occurrences = HOME_TSX.split(p).length - 1;
      expect(occurrences).toBeGreaterThanOrEqual(1);
    }
  });

  it("six unique paths, one per real app screen", () => {
    expect(new Set(REAL_SCREENSHOT_PATHS).size).toBe(6);
  });

  it("never falls back to remote http(s) image hosts", () => {
    expect(HOME_TSX).not.toMatch(/src=["']https?:\/\//);
  });

  it("does not import images from the local filesystem", () => {
    expect(HOME_TSX).not.toMatch(/import\s+\w+\s+from\s+['"]\.\.?\/.+\.(png|jpe?g|webp|svg)['"]/);
  });
});

// ---------------------------------------------------------------------------
// 3. Pure scroll-math — mirrors gemini-3.5-flash's update loop.
//
// Section motion is parameterised by `t`, the section's distance from the
// viewport center, normalised by half-viewport and clamped to [-1.5, 1.5].
//
//   t                    = clamp((sectionCenter - vh/2) / (vh/2), -1.5, 1.5)
//   phone.translateY(px) = t * 40
//   phone.rotate(deg)    = t * -3
//   text.opacity         = max(0, 1 - |t| * 1.3)
//   text.translateY(px)  = t * 15
//   halo.scale           = 1 + (1 - min(1, |t|)) * 0.25
//   halo.opacity         = max(0, 0.12 - |t| * 0.08)
// ---------------------------------------------------------------------------
function clamp(v: number, lo: number, hi: number) {
  return Math.max(lo, Math.min(hi, v));
}

function tFromCenter(sectionCenter: number, vh: number): number {
  return clamp((sectionCenter - vh / 2) / (vh / 2), -1.5, 1.5);
}

const phoneTranslateY = (t: number) => t * 40;
const phoneRotate = (t: number) => t * -3;
const textOpacity = (t: number) => Math.max(0, 1 - Math.abs(t) * 1.3);
const textTranslateY = (t: number) => t * 15;
const haloScale = (t: number) => 1 + (1 - Math.min(1, Math.abs(t))) * 0.25;
const haloOpacity = (t: number) => Math.max(0, 0.12 - Math.abs(t) * 0.08);

describe("Home — t mapping (gemini-3.5-flash scroll formula)", () => {
  const VH = 800;

  it("t is 0 when the section center sits at viewport center", () => {
    expect(tFromCenter(VH / 2, VH)).toBe(0);
  });

  it("t is clamped to [-1.5, 1.5] regardless of distance", () => {
    expect(tFromCenter(VH * 5, VH)).toBe(1.5);
    expect(tFromCenter(-VH * 5, VH)).toBe(-1.5);
  });

  it("t increases as the section center moves below the viewport center", () => {
    expect(tFromCenter(VH * 0.6, VH)).toBeGreaterThan(0);
    expect(tFromCenter(VH * 0.8, VH)).toBeGreaterThan(tFromCenter(VH * 0.6, VH));
  });

  it("t decreases as the section center scrolls above the viewport center", () => {
    expect(tFromCenter(VH * 0.4, VH)).toBeLessThan(0);
    expect(tFromCenter(VH * 0.2, VH)).toBeLessThan(tFromCenter(VH * 0.4, VH));
  });
});

describe("Home — phone parallax + tilt", () => {
  it("phone is centred (no transform) at t=0", () => {
    expect(Math.abs(phoneTranslateY(0))).toBe(0);
    expect(Math.abs(phoneRotate(0))).toBe(0);
  });

  it("phone translates 60 px and tilts -4.5° at the clamped extremes", () => {
    expect(phoneTranslateY(1.5)).toBeCloseTo(60, 6);
    expect(phoneRotate(-1.5)).toBeCloseTo(4.5, 6);
  });

  it("phone parallax is monotonic in t", () => {
    const ts = [-1.5, -1, 0, 1, 1.5];
    const ys = ts.map(phoneTranslateY);
    for (let i = 1; i < ys.length; i++) {
      expect(ys[i]).toBeGreaterThan(ys[i - 1]);
    }
  });
});

describe("Home — text fade-in", () => {
  it("text is fully visible at t=0", () => {
    expect(textOpacity(0)).toBe(1);
    expect(textTranslateY(0)).toBe(0);
  });

  it("text is invisible once |t| reaches 1/1.3 ≈ 0.7692", () => {
    expect(textOpacity(1 / 1.3)).toBeCloseTo(0, 6);
    expect(textOpacity(1)).toBe(0);
    expect(textOpacity(1.5)).toBe(0);
  });

  it("text opacity is symmetric around 0", () => {
    expect(textOpacity(-0.4)).toBeCloseTo(textOpacity(0.4), 12);
  });
});

describe("Home — halo scale + opacity", () => {
  it("halo is largest and brightest exactly when section is centered", () => {
    expect(haloScale(0)).toBe(1.25);
    expect(haloOpacity(0)).toBe(0.12);
  });

  it("halo opacity falls to 0 at |t| ≥ 1.5", () => {
    expect(haloOpacity(1.5)).toBe(0);
    expect(haloOpacity(2)).toBe(0);
  });

  it("halo scale never exceeds 1.25 and never falls below 1", () => {
    for (const t of [-1.5, -1, -0.5, 0, 0.5, 1, 1.5]) {
      const s = haloScale(t);
      expect(s).toBeGreaterThanOrEqual(1);
      expect(s).toBeLessThanOrEqual(1.25 + 1e-9);
    }
  });
});

// ---------------------------------------------------------------------------
// 4. Sticky CTA threshold logic
// ---------------------------------------------------------------------------
describe("Home — sticky CTA threshold", () => {
  it("hides at and below 480 px of scroll, shows beyond", () => {
    const shouldShow = (y: number) => y > 480;
    expect(shouldShow(0)).toBe(false);
    expect(shouldShow(479)).toBe(false);
    expect(shouldShow(480)).toBe(false);
    expect(shouldShow(481)).toBe(true);
    expect(shouldShow(2000)).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// 5. Section alternation
// ---------------------------------------------------------------------------
describe("Home — section alternation", () => {
  it("isEven (idx % 2 === 0) yields true,false,true,false,true,false for six sections", () => {
    const isEven = (i: number) => i % 2 === 0;
    expect([0, 1, 2, 3, 4, 5].map(isEven)).toEqual([
      true,
      false,
      true,
      false,
      true,
      false,
    ]);
  });
});
