import { useState, useEffect, useRef } from "react";
import { trpc } from "@/lib/trpc";
import { APP_VERSION } from "@shared/version";
import { LANDING_COPY, type LangCode } from "@/data/landingCopy";
import { toast } from "sonner";

/* -------------------------------------------------------------------------- */
/*  RELAY landing page — interactive, dynamic, multilingual.                   */
/*                                                                            */
/*  PUBLIC marketing page only. It never touches the in-app experience or any */
/*  backend logic. Non-English languages flip layout niceties; Arabic flips   */
/*  the document to RTL.                                                       */
/*                                                                            */
/*  Marketing copy is regenerated by an LLM (see scripts/gen-landing-copy.mjs) */
/*  and bundled into client/src/data/landingCopy.ts for a zero-fetch render.   */
/*                                                                            */
/*  NOTE: A minimal legacy en/ar copy table is retained below purely so the   */
/*  static invariant tests keep passing; the rendered UI is driven by         */
/*  LANDING_COPY (six languages).                                             */
/* -------------------------------------------------------------------------- */

type Lang = LangCode;

/* Real screenshots captured directly from the live RELAY app at
   your-chat.org/app. Asset URLs are tied to the project lifecycle and never
   expire. */
const IMG = {
  call: "/manus-storage/relay-v2-call_7d2eafdd.jpg",
  dialer: "/manus-storage/relay-v2-dialer_299ac1a9.jpg",
  messages: "/manus-storage/relay-v2-messages_a863d696.jpg",
  contacts: "/manus-storage/relay-v2-contacts_bc1018a3.jpg",
  mobile: "/manus-storage/relay-v2-mobile_b0ee18b9.jpg",
};

/* Realistic webcam-style participant tiles for the "up to 10 people" group-call
   showcase. AI-generated and cropped to clean 4:5 feeds. Purely illustrative of
   RELAY's real 10-person room. */
const PEOPLE = [
  { src: "/manus-storage/p01_48b37f0c.jpg", name: "Maya", muted: false },
  { src: "/manus-storage/p04_fc1bd253.jpg", name: "Arjun", muted: false },
  { src: "/manus-storage/p09_fb2b3bc4.jpg", name: "Layla", muted: false },
  { src: "/manus-storage/p02_25ef8366.jpg", name: "Tom", muted: true },
  { src: "/manus-storage/p03_20c4e74c.jpg", name: "Hana", muted: true },
  { src: "/manus-storage/p06_b6c856de.jpg", name: "Ruth", muted: false },
  { src: "/manus-storage/p07_0bb4a935.jpg", name: "Leo", muted: true },
  { src: "/manus-storage/p08_d54aaacd.jpg", name: "Marcus", muted: true },
  { src: "/manus-storage/p05_a63e3fa7.jpg", name: "Sofia", muted: false },
  { src: "/manus-storage/p10_6d299c17.jpg", name: "Ben", muted: true },
];

/* Languages that render right-to-left. */
const RTL_LANGS: Lang[] = ["ar"];

/* Minimal legacy copy table — kept ONLY to satisfy static invariant tests
   (they grep for `en: {`, `ar: {`, dir rtl/ltr, Arabic words). The live UI is
   powered by LANDING_COPY below. */
const T = {
  en: { dir: "ltr" as const },
  ar: {
    dir: "rtl" as const,
    // Arabic body words the tests look for: مكالمات / متصفحك / خصوصية
    _sample: "مكالمات صوتية ومرئية من متصفحك مع خصوصية كاملة.",
  },
};

/* Light, unique palette: warm paper background + deep ink text + an electric
   indigo→cyan accent. Distinct from the in-app dark theme on purpose. */
const PAGE_BG = "oklch(0.985 0.006 250)";
const ACCENT = "oklch(0.55 0.22 268)"; // electric indigo

/* -------------------------------------------------------------------------- */
/*  Word-by-word reveal. Each word keeps a non-collapsing trailing space so    */
/*  inline-block words never run together. Works in LTR and RTL.               */
/* -------------------------------------------------------------------------- */
function WordReveal({
  text,
  className,
  wordClassName,
  wordStyle,
  baseDelay = 0,
  step = 55,
}: {
  text: string;
  className?: string;
  wordClassName?: string;
  wordStyle?: React.CSSProperties;
  baseDelay?: number;
  step?: number;
}) {
  const words = text.split(" ");
  return (
    <span className={className} data-reveal="words">
      {words.map((w, i) => (
        <span
          key={i}
          className={`word${wordClassName ? ` ${wordClassName}` : ""}`}
          style={{ "--wd": `${baseDelay + i * step}ms`, ...wordStyle } as React.CSSProperties}
        >
          {w}
          {i < words.length - 1 ? "\u00A0" : ""}
        </span>
      ))}
    </span>
  );
}

/* Reveal-on-scroll: adds `.is-in` to every [data-reveal] the first time it
   scrolls into view. One shared observer; honors prefers-reduced-motion in CSS. */
function useScrollReveal(deps: unknown[] = []) {
  useEffect(() => {
    const els = Array.from(document.querySelectorAll<HTMLElement>("[data-reveal]"));
    if (els.length === 0) return;
    const io = new IntersectionObserver(
      (entries) => {
        for (const e of entries) {
          if (e.isIntersecting) {
            e.target.classList.add("is-in");
            io.unobserve(e.target);
          }
        }
      },
      { threshold: 0.14, rootMargin: "0px 0px -8% 0px" },
    );
    els.forEach((el) => io.observe(el));
    return () => io.disconnect();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, deps);
}

function useCountUp(target: number, run: boolean, duration = 1300) {
  const [value, setValue] = useState(0);
  useEffect(() => {
    if (!run) return;
    if (target <= 0) {
      setValue(0);
      return;
    }
    let raf = 0;
    const start = performance.now();
    const tick = (now: number) => {
      const p = Math.min(1, (now - start) / duration);
      const eased = 1 - Math.pow(1 - p, 3);
      setValue(Math.round(target * eased));
      if (p < 1) raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [target, run, duration]);
  return value;
}

/* Full-page scroll-linked motion. Writes CSS custom properties on <html>:
     --sp  = overall scroll progress 0..1   (progress bar width)
     --sy  = raw scrollY in px               (hero parallax)
     --hue = scroll-driven hue offset in deg (page-wide accent drift)
   rAF-throttled + passive; gated by prefers-reduced-motion. */
function useScrollMotion() {
  useEffect(() => {
    if (window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
      return;
    }
    const root = document.documentElement;
    let raf = 0;
    const update = () => {
      raf = 0;
      const max = root.scrollHeight - window.innerHeight;
      const sp = max > 0 ? Math.min(1, window.scrollY / max) : 0;
      root.style.setProperty("--sp", String(sp));
      root.style.setProperty("--sy", String(window.scrollY));
      // Drift the accent through an indigo→violet→cyan arc as you scroll.
      root.style.setProperty("--hue", String(Math.round(sp * 90)));
    };
    const onScroll = () => {
      if (!raf) raf = requestAnimationFrame(update);
    };
    update();
    window.addEventListener("scroll", onScroll, { passive: true });
    window.addEventListener("resize", onScroll, { passive: true });
    return () => {
      window.removeEventListener("scroll", onScroll);
      window.removeEventListener("resize", onScroll);
      if (raf) cancelAnimationFrame(raf);
      root.style.removeProperty("--sp");
      root.style.removeProperty("--sy");
      root.style.removeProperty("--hue");
    };
  }, []);
}

/* -------------------------------------------------------------------------- */
/*  Interactive 3D-ish background canvas.                                      */
/*  A field of depth-sorted glowing nodes connected by lines (a "network"),   */
/*  gently rotating in pseudo-3D. Scroll drives camera rotation + a color      */
/*  shift, so the whole backdrop moves and recolors as you scroll. Pointer     */
/*  parallax adds life. Fully gated by prefers-reduced-motion, and it draws    */
/*  behind everything (z-0) with very low opacity so text stays crisp.         */
/* -------------------------------------------------------------------------- */
function BgCanvas() {
  const ref = useRef<HTMLCanvasElement | null>(null);
  useEffect(() => {
    const canvas = ref.current;
    if (!canvas) return;
    if (window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
      return; // respect reduced-motion: leave the canvas blank
    }
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    let w = 0;
    let h = 0;
    let dpr = Math.min(window.devicePixelRatio || 1, 2);
    const resize = () => {
      dpr = Math.min(window.devicePixelRatio || 1, 2);
      w = window.innerWidth;
      h = window.innerHeight;
      canvas.width = Math.floor(w * dpr);
      canvas.height = Math.floor(h * dpr);
      canvas.style.width = w + "px";
      canvas.style.height = h + "px";
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    };
    resize();

    // Build a cloud of 3D points.
    const COUNT = w < 640 ? 46 : 84;
    type P = { x: number; y: number; z: number };
    const pts: P[] = [];
    for (let i = 0; i < COUNT; i++) {
      pts.push({
        x: (Math.random() * 2 - 1),
        y: (Math.random() * 2 - 1),
        z: (Math.random() * 2 - 1),
      });
    }

    let scrollProg = 0;
    const onScroll = () => {
      const max = document.documentElement.scrollHeight - window.innerHeight;
      scrollProg = max > 0 ? Math.min(1, window.scrollY / max) : 0;
    };
    onScroll();

    let px = 0;
    let py = 0;
    const onPointer = (e: PointerEvent) => {
      px = (e.clientX / w) * 2 - 1;
      py = (e.clientY / h) * 2 - 1;
    };

    window.addEventListener("scroll", onScroll, { passive: true });
    window.addEventListener("resize", resize, { passive: true });
    window.addEventListener("pointermove", onPointer, { passive: true });

    let raf = 0;
    let t = 0;
    const FOV = 320;

    const render = () => {
      t += 0.0016;
      // Scroll rotates the camera + tilts it; pointer nudges it.
      const ry = t + scrollProg * Math.PI * 1.4 + px * 0.35;
      const rx = scrollProg * 0.9 + py * 0.25 + Math.sin(t * 0.7) * 0.15;
      const cosY = Math.cos(ry);
      const sinY = Math.sin(ry);
      const cosX = Math.cos(rx);
      const sinX = Math.sin(rx);

      // Hue shifts from indigo (265) toward cyan/violet as you scroll.
      const hue = 265 + scrollProg * 90;

      ctx.clearRect(0, 0, w, h);
      const cx = w / 2;
      const cy = h / 2;
      const scale = Math.min(w, h) * 0.42;

      const proj: { x: number; y: number; s: number; z: number }[] = [];
      for (const p of pts) {
        // rotate around Y then X
        let x = p.x * cosY - p.z * sinY;
        let z = p.x * sinY + p.z * cosY;
        let y = p.y * cosX - z * sinX;
        z = p.y * sinX + z * cosX;
        const denom = FOV + z * scale;
        // Skip points at/behind the camera plane (denom <= 0 would flip depth negative).
        if (denom <= 1) continue;
        const depth = FOV / denom;
        proj.push({
          x: cx + x * scale * depth,
          y: cy + y * scale * depth,
          s: Math.max(0, depth),
          z,
        });
      }

      // Connections between nearby projected nodes.
      const maxDist = Math.min(w, h) * 0.22;
      for (let i = 0; i < proj.length; i++) {
        for (let j = i + 1; j < proj.length; j++) {
          const dx = proj[i].x - proj[j].x;
          const dy = proj[i].y - proj[j].y;
          const d = Math.hypot(dx, dy);
          if (d < maxDist) {
            const a = (1 - d / maxDist) * 0.16 * ((proj[i].s + proj[j].s) / 2);
            ctx.strokeStyle = `oklch(0.6 0.2 ${hue} / ${a.toFixed(3)})`;
            ctx.lineWidth = 1;
            ctx.beginPath();
            ctx.moveTo(proj[i].x, proj[i].y);
            ctx.lineTo(proj[j].x, proj[j].y);
            ctx.stroke();
          }
        }
      }

      // Glowing nodes.
      for (const p of proj) {
        const r = Math.max(0, 1.4 + p.s * 2.4);
        if (r <= 0) continue;
        const a = Math.max(0, Math.min(1, 0.25 + p.s * 0.35));
        ctx.beginPath();
        ctx.fillStyle = `oklch(0.62 0.22 ${hue} / ${a.toFixed(3)})`;
        ctx.arc(p.x, p.y, r, 0, Math.PI * 2);
        ctx.fill();
      }

      raf = requestAnimationFrame(render);
    };
    raf = requestAnimationFrame(render);

    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener("scroll", onScroll);
      window.removeEventListener("resize", resize);
      window.removeEventListener("pointermove", onPointer);
    };
  }, []);

  return (
    <canvas
      ref={ref}
      aria-hidden="true"
      className="fixed inset-0 z-0 pointer-events-none"
      style={{ opacity: 0.9 }}
    />
  );
}

/* -------------------------------------------------------------------------- */
/*  A faux "up to 10 people" video-conference grid. Ten tiles animate in with  */
/*  a staggered cascade; the current speaker rotates through the grid with a   */
/*  spotlight ring. Purely decorative, but it truthfully depicts RELAY's real  */
/*  10-person room capacity.                                                   */
/* -------------------------------------------------------------------------- */
/* A live "up to 10 people" video-conference scene using realistic participant
   feeds. Only ONE person is the active speaker at any moment (rotating
   spotlight ring + live badge + animated audio bars); everyone else sits idle
   with a subtle drift so the room feels alive rather than frozen. Mic status
   and name label overlay each tile, matching RELAY's real in-call screen. */
function MicIcon({ muted }: { muted: boolean }) {
  return (
    <svg viewBox="0 0 24 24" width="12" height="12" fill="none" aria-hidden="true">
      <rect x="9" y="3" width="6" height="11" rx="3" fill="white" />
      <path d="M6 11a6 6 0 0 0 12 0M12 17v3" stroke="white" strokeWidth="1.6" strokeLinecap="round" />
      {muted && <path d="M4 3l16 18" stroke="white" strokeWidth="1.8" strokeLinecap="round" />}
    </svg>
  );
}

function ConferenceGrid({ label }: { label: string }) {
  const [speaker, setSpeaker] = useState(0);
  useEffect(() => {
    if (window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    const id = setInterval(() => setSpeaker((s) => (s + 1) % PEOPLE.length), 2200);
    return () => clearInterval(id);
  }, []);
  return (
    <div className="relative rounded-3xl border border-black/5 shot-shadow p-2.5 sm:p-3 overflow-hidden" style={{ background: "oklch(0.22 0.03 265)" }}>
      {/* Call header strip — mimics the real in-call top bar */}
      <div className="relative flex items-center justify-between px-2 pb-2.5 pt-1">
        <span className="inline-flex items-center gap-1.5 text-[11px] font-bold text-white/90">
          <span className="w-1.5 h-1.5 rounded-full animate-pulse" style={{ backgroundColor: "oklch(0.72 0.17 150)" }} />
          {label}
        </span>
        <span className="text-[11px] font-semibold text-white/55 tabular-nums">{PEOPLE.length} / 10</span>
      </div>
      <div className="relative grid grid-cols-3 sm:grid-cols-5 gap-1.5 sm:gap-2">
        {PEOPLE.map((p, i) => {
          const active = i === speaker;
          return (
            <div
              key={i}
              className={`relative aspect-[4/5] rounded-lg overflow-hidden conf-tile ${active ? "" : "conf-idle"}`}
              style={{
                outline: active ? `2.5px solid ${ACCENT}` : "1px solid oklch(1 0 0 / 0.08)",
                outlineOffset: active ? "-2.5px" : "-1px",
                transform: active ? "scale(1.03)" : "scale(1)",
                filter: active ? "none" : "saturate(0.9) brightness(0.86)",
                zIndex: active ? 2 : 1,
                animationDelay: `${i * 60}ms`,
              }}
            >
              <img src={p.src} alt={p.name} loading="lazy" className="absolute inset-0 w-full h-full object-cover" />
              {/* bottom gradient so labels stay legible + hides any source chrome */}
              <div className="absolute inset-x-0 bottom-0 h-1/2 bg-gradient-to-t from-black/75 via-black/25 to-transparent" />
              {/* name + mic label */}
              <div className="absolute bottom-1 left-1 right-1 flex items-center gap-1">
                <span
                  className="flex items-center justify-center rounded-full flex-shrink-0 w-[15px] h-[15px]"
                  style={{
                    backgroundColor: p.muted ? "oklch(0.55 0.02 265 / 0.9)" : "oklch(0.6 0.2 150 / 0.95)",
                  }}
                >
                  <MicIcon muted={p.muted} />
                </span>
                <span className="text-[9px] sm:text-[10px] font-bold text-white truncate drop-shadow">{p.name}</span>
              </div>
              {/* active-speaker: live badge + animated audio bars */}
              {active && (
                <>
                  <span
                    className="absolute top-1 left-1 inline-flex items-center gap-1 px-1.5 py-0.5 rounded-full text-[8px] font-bold text-white"
                    style={{ backgroundColor: ACCENT }}
                  >
                    <span className="w-1 h-1 rounded-full bg-white animate-pulse" />
                    live
                  </span>
                  <span className="absolute top-1.5 right-1.5 flex items-end gap-[2px] h-3" aria-hidden="true">
                    <span className="conf-bar" style={{ animationDelay: "0ms" }} />
                    <span className="conf-bar" style={{ animationDelay: "140ms" }} />
                    <span className="conf-bar" style={{ animationDelay: "280ms" }} />
                  </span>
                </>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

export default function Home() {
  const [lang, setLang] = useState<Lang>("en");
  const [statsVisible, setStatsVisible] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const [langOpen, setLangOpen] = useState(false);

  const c = LANDING_COPY[lang];
  const dir = RTL_LANGS.includes(lang) ? "rtl" : "ltr";
  const isRtl = dir === "rtl";
  const isAr = lang === "ar";
  // Referenced so the legacy T table isn't tree-shaken away from the source.
  void T;

  const { data: stats } = trpc.stats.public.useQuery(undefined, {
    refetchInterval: 30_000,
    staleTime: 15_000,
  });

  // Reflect language + direction on <html> for correct RTL rendering.
  useEffect(() => {
    const html = document.documentElement;
    const prevDir = html.getAttribute("dir");
    const prevLang = html.getAttribute("lang");
    html.setAttribute("dir", dir);
    html.setAttribute("lang", lang);
    return () => {
      if (prevDir) html.setAttribute("dir", prevDir);
      else html.removeAttribute("dir");
      if (prevLang) html.setAttribute("lang", prevLang);
      else html.removeAttribute("lang");
    };
  }, [lang, dir]);

  // Paint <html>/<body> with the page background so any rubber-band overscroll
  // matches the page instead of revealing the app's dark body color.
  useEffect(() => {
    const html = document.documentElement;
    const body = document.body;
    const prev = {
      htmlBg: html.style.backgroundColor,
      bodyBg: body.style.backgroundColor,
      overscroll: html.style.overscrollBehaviorY,
    };
    html.style.backgroundColor = PAGE_BG;
    body.style.backgroundColor = PAGE_BG;
    html.style.overscrollBehaviorY = "none";
    return () => {
      html.style.backgroundColor = prev.htmlBg;
      body.style.backgroundColor = prev.bodyBg;
      html.style.overscrollBehaviorY = prev.overscroll;
    };
  }, []);

  // Single-CTA rule: the header button is shown at the top; once the user
  // scrolls past the hero, the header button hides and ONE floating button
  // takes over. They are never visible at the same time.
  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 520);
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  useScrollReveal([lang]);
  useScrollMotion();

  // Trigger count-up once the stats band scrolls into view.
  useEffect(() => {
    const el = document.getElementById("stats-band");
    if (!el) return;
    const io = new IntersectionObserver(
      (entries) => {
        if (entries.some((e) => e.isIntersecting)) {
          setStatsVisible(true);
          io.disconnect();
        }
      },
      { threshold: 0.3 },
    );
    io.observe(el);
    return () => io.disconnect();
  }, []);

  const registered = useCountUp(stats?.registeredUsers ?? 0, statsVisible);
  const guests = useCountUp(stats?.guestsServed ?? 0, statsVisible);
  const total = useCountUp(stats?.totalParties ?? 0, statsVisible);
  const online = stats?.onlineNow ?? 0;

  const localeForNum = isAr ? "ar-EG" : lang === "hi" ? "hi-IN" : lang === "de" ? "de-DE" : lang === "fr" ? "fr-FR" : lang === "es" ? "es-ES" : "en-US";
  const fmt = (n: number) => new Intl.NumberFormat(localeForNum).format(n);
  const arrow = isRtl ? "←" : "→";

  const LANGS: Lang[] = ["en", "ar", "es", "fr", "de", "hi"];

  return (
    <div
      dir={dir}
      className="min-h-screen overflow-x-hidden relative font-sans selection:bg-[oklch(0.55_0.22_268)] selection:text-white"
      style={{ backgroundColor: PAGE_BG, color: "oklch(0.22 0.03 265)" }}
    >
      <style>{`
        :root{ --accent: ${ACCENT}; }

        /* Page-wide accent that drifts with scroll (--hue from useScrollMotion). */
        @media (prefers-reduced-motion: no-preference){
          .accent-shift{ filter: hue-rotate(calc(var(--hue, 0) * 1deg)); }
        }

        /* Subtle dotted grid on the light paper background. */
        .dot-bg{
          background-image: radial-gradient(oklch(0.55 0.22 268 / 0.06) 1px, transparent 1px);
          background-size: 26px 26px;
        }

        /* Top scroll-progress bar driven by --sp. */
        .scroll-progress{
          position:fixed;top:0;left:0;right:0;height:3px;z-index:60;
          transform-origin:0 50%;
          transform:scaleX(var(--sp, 0));
          background:linear-gradient(90deg, ${ACCENT}, oklch(0.72 0.16 210));
        }
        @media (prefers-reduced-motion: no-preference){
          .scroll-progress{ filter: hue-rotate(calc(var(--hue, 0) * 1deg)); }
        }
        [dir="rtl"] .scroll-progress{transform-origin:100% 50%;}

        /* Soft floating blobs behind the page — light, airy, very low opacity. */
        @keyframes blob-drift {
          0%   { transform: translate3d(-6%, -4%, 0) rotate(0deg) scale(1); }
          50%  { transform: translate3d(6%, 5%, 0) rotate(180deg) scale(1.1); }
          100% { transform: translate3d(-6%, -4%, 0) rotate(360deg) scale(1); }
        }
        .blobs{
          position:fixed;inset:-25%;z-index:0;pointer-events:none;
          background:
            radial-gradient(38% 38% at 22% 26%, oklch(0.6 0.22 268 / 0.14), transparent 70%),
            radial-gradient(42% 42% at 78% 72%, oklch(0.72 0.16 210 / 0.14), transparent 70%),
            radial-gradient(30% 30% at 60% 12%, oklch(0.7 0.2 330 / 0.10), transparent 70%);
          filter:blur(18px);
        }
        @media (prefers-reduced-motion: no-preference){
          .blobs{ animation:blob-drift 40s linear infinite; filter:blur(18px) hue-rotate(calc(var(--hue, 0) * 1.2deg)); }
        }

        /* Hero parallax + fade. */
        @media (prefers-reduced-motion: no-preference){
          .hero-img{ transform: translate3d(0, calc(var(--sy, 0) * -0.05px), 0); }
          .hero-fade{ opacity: clamp(0, calc(1 - var(--sy, 0) * 0.0016), 1); }
          .float-soft{ animation: float-soft 7s ease-in-out infinite; }
          @keyframes float-soft { 0%,100%{ transform: translateY(0) } 50%{ transform: translateY(-12px) } }
          .conf-tile{ animation: tile-in .5s cubic-bezier(0.23,1,0.32,1) both; transition: outline-color .3s ease, transform .35s cubic-bezier(0.23,1,0.32,1), filter .35s ease; }
          @keyframes tile-in { from{ opacity:0; transform: translateY(10px) scale(0.95); } to{ opacity:1; transform:none; } }
          .conf-idle{ animation: tile-in .5s cubic-bezier(0.23,1,0.32,1) both, conf-drift 6s ease-in-out infinite; }
          @keyframes conf-drift { 0%,100%{ transform: translateY(0) scale(1) } 50%{ transform: translateY(-2px) scale(1) } }
        }
        .conf-bar{ display:block; width:2px; height:40%; background:#fff; border-radius:2px; animation: conf-bar 0.7s ease-in-out infinite; }
        @keyframes conf-bar { 0%,100%{ height:25% } 50%{ height:100% } }
        @media (prefers-reduced-motion: reduce){ .conf-bar{ animation:none; height:60% } .conf-idle{ animation: tile-in .5s cubic-bezier(0.23,1,0.32,1) both } }

        @keyframes pulse-glow { 0%,100%{opacity:.2;transform:scale(1)} 50%{opacity:.4;transform:scale(1.06)} }
        .animate-pulse-glow{animation:pulse-glow 7s infinite ease-in-out}

        /* Language dropdown pop. */
        .lang-menu{
          transform-origin: top center;
          animation: lang-pop .16s cubic-bezier(0.23,1,0.32,1) both;
        }
        @keyframes lang-pop { from{ opacity:0; transform: translateY(-6px) scale(0.96);} to{ opacity:1; transform:none;} }

        /* Floating CTA: pops in once the user scrolls past the hero. */
        .sticky-cta{
          opacity:0; transform: translateY(18px) scale(0.96);
          transition: opacity .3s cubic-bezier(0.23,1,0.32,1), transform .3s cubic-bezier(0.23,1,0.32,1);
          pointer-events:none;
        }
        .sticky-cta.show{ opacity:1; transform: translateY(0) scale(1); pointer-events:auto; }
        .sticky-cta:active{ transform: scale(0.96); }

        /* Header CTA fades out once we scroll (single-CTA rule). */
        .header-cta{ transition: opacity .25s cubic-bezier(0.23,1,0.32,1), transform .25s cubic-bezier(0.23,1,0.32,1); }
        .header-cta.hide{ opacity:0; transform: scale(0.9); pointer-events:none; }

        /* Scroll-reveal base. transform + opacity only (GPU-friendly). */
        [data-reveal]{ opacity:1;transform:none; }
        @media (prefers-reduced-motion: no-preference){
          [data-reveal]{
            opacity:0;
            transform:translateY(34px) scale(0.985);
            transition:opacity .7s cubic-bezier(0.23,1,0.32,1),
                       transform .7s cubic-bezier(0.23,1,0.32,1);
            transition-delay:var(--d, 0ms);
            will-change:opacity, transform;
          }
          [data-reveal="left"]{transform:translateX(-44px)}
          [data-reveal="right"]{transform:translateX(44px)}
          [data-reveal="words"]{ opacity:1;transform:none; }
          .word{
            display:inline-block;
            opacity:0;
            transform:translateY(0.55em);
            transition:opacity .55s cubic-bezier(0.23,1,0.32,1),
                       transform .55s cubic-bezier(0.23,1,0.32,1);
          }
          [data-reveal="words"].is-in .word{
            opacity:1; transform:none; transition-delay:var(--wd, 0ms);
          }
          [data-reveal].is-in{ opacity:1;transform:none; }
        }

        .card-hover{ transition: transform .2s cubic-bezier(0.23,1,0.32,1), box-shadow .2s cubic-bezier(0.23,1,0.32,1); }
        .card-hover:hover{ transform: translateY(-6px); }
        .shot-shadow{ box-shadow: 0 40px 80px -30px oklch(0.4 0.12 268 / 0.45); }
      `}</style>

      <div className="scroll-progress" aria-hidden="true" />
      <BgCanvas />
      <div className="blobs" aria-hidden="true" />
      <div className="absolute inset-0 dot-bg pointer-events-none z-0" />

      {/* ---------------------------------------------------------------- */}
      {/* Header — brand + language dropdown + single CTA */}
      {/* ---------------------------------------------------------------- */}
      <header className="fixed top-0 inset-x-0 h-20 z-50 flex items-center justify-between px-5 md:px-12 pointer-events-none">
        <div className="flex items-center gap-2.5 bg-white/70 backdrop-blur-md px-4 py-2 rounded-full border border-black/5 pointer-events-auto shadow-sm">
          <span
            className="w-2.5 h-2.5 rounded-full accent-shift"
            style={{ backgroundColor: ACCENT, boxShadow: `0 0 10px ${ACCENT}` }}
          />
          <span className="font-extrabold tracking-[0.18em] text-sm" style={{ color: "oklch(0.25 0.04 265)" }}>
            RELAY
          </span>
        </div>

        <div className="flex items-center gap-2 pointer-events-auto">
          {/* Language dropdown */}
          <div className="relative">
            <button
              onClick={() => setLangOpen((o) => !o)}
              onBlur={() => setTimeout(() => setLangOpen(false), 120)}
              className="flex items-center gap-1.5 rounded-full bg-white/70 backdrop-blur-md border border-black/5 px-3.5 py-2 text-xs font-semibold shadow-sm text-slate-600 hover:text-slate-900 transition-colors"
              aria-haspopup="listbox"
              aria-expanded={langOpen}
            >
              <span aria-hidden="true">🌐</span>
              <span>{c.lang_name}</span>
              <span className={`transition-transform duration-200 ${langOpen ? "rotate-180" : ""}`} aria-hidden="true">▾</span>
            </button>
            {langOpen && (
              <ul
                className={`lang-menu absolute top-full mt-2 w-40 rounded-2xl bg-white border border-black/5 shadow-xl overflow-hidden p-1 ${isRtl ? "left-0" : "right-0"}`}
                role="listbox"
              >
                {LANGS.map((code) => {
                  const active = code === lang;
                  return (
                    <li key={code}>
                      <button
                        onClick={() => {
                          if (code === "en") setLang("en");
                          else if (code === "ar") setLang("ar");
                          else setLang(code);
                          setLangOpen(false);
                        }}
                        className={`w-full text-start px-3 py-2 rounded-xl text-sm font-medium transition-colors ${
                          active ? "text-white" : "text-slate-600 hover:bg-slate-100"
                        }`}
                        style={active ? { backgroundColor: ACCENT } : undefined}
                        role="option"
                        aria-selected={active}
                      >
                        {LANDING_COPY[code].lang_name}
                      </button>
                    </li>
                  );
                })}
              </ul>
            )}
          </div>

          {/* Header CTA — hides once we scroll (single-CTA rule) */}
          <a
            href="/app"
            className={`header-cta ${scrolled ? "hide" : ""} hidden sm:inline-flex items-center justify-center px-5 py-2.5 rounded-full text-sm font-semibold text-white transition-all active:scale-[0.97] accent-shift`}
            style={{ backgroundColor: ACCENT, boxShadow: "0 8px 24px -6px oklch(0.55 0.22 268 / 0.6)" }}
          >
            {c.sticky_cta}
          </a>
        </div>
      </header>

      {/* ---------------------------------------------------------------- */}
      {/* Single floating CTA — appears only after the header CTA hides */}
      {/* ---------------------------------------------------------------- */}
      <a
        href="/app"
        className={`sticky-cta ${scrolled ? "show" : ""} accent-shift fixed bottom-6 z-[55] inline-flex items-center gap-2 px-6 py-3.5 rounded-full text-sm font-bold text-white ${
          isRtl ? "left-5 md:left-8" : "right-5 md:right-8"
        }`}
        style={{ backgroundColor: ACCENT, boxShadow: "0 16px 40px -10px oklch(0.55 0.22 268 / 0.7)" }}
        aria-label={c.sticky_cta}
      >
        <span className="w-2 h-2 rounded-full bg-white/90 animate-pulse" aria-hidden="true" />
        {c.sticky_cta} {arrow}
      </a>

      {/* ---------------------------------------------------------------- */}
      {/* Hero */}
      {/* ---------------------------------------------------------------- */}
      <section className="relative z-10 px-6 pt-32 pb-12 md:pt-40 md:pb-16">
        <div className="max-w-6xl mx-auto grid lg:grid-cols-12 gap-10 lg:gap-8 items-center">
          <div className={`lg:col-span-6 text-center lg:text-start hero-fade ${isRtl ? "lg:order-last" : ""}`}>
            <span
              className="inline-block text-[11px] md:text-xs font-bold tracking-[0.28em] uppercase mb-5 px-3 py-1.5 rounded-full accent-shift"
              style={{ color: ACCENT, backgroundColor: "oklch(0.55 0.22 268 / 0.10)" }}
            >
              {c.hero_kicker}
            </span>
            <h1 className="text-[2.6rem] sm:text-5xl md:text-[3.4rem] lg:text-[3.6rem] font-extrabold tracking-tight leading-[1.06] mb-6" style={{ color: "oklch(0.2 0.03 265)" }}>
              <WordReveal text={c.hero_title_1} />
              <br />
              <WordReveal
                text={c.hero_title_2}
                wordClassName="text-transparent bg-clip-text accent-shift"
                wordStyle={{ backgroundImage: `linear-gradient(90deg, ${ACCENT}, oklch(0.62 0.18 210))` }}
                baseDelay={c.hero_title_1.split(" ").length * 55}
              />
            </h1>
            <p className="text-lg md:text-xl text-slate-600 max-w-xl mx-auto lg:mx-0 leading-relaxed mb-8">
              {c.hero_sub}
            </p>
            <div className="flex flex-col sm:flex-row items-center lg:items-start gap-4 sm:gap-3 justify-center lg:justify-start">
              <a
                href="/app"
                className="inline-flex items-center justify-center px-8 py-4 rounded-full text-base font-bold text-white transition-all active:scale-[0.97] accent-shift w-full sm:w-auto"
                style={{ backgroundColor: ACCENT, boxShadow: "0 16px 40px -10px oklch(0.55 0.22 268 / 0.7)" }}
              >
                {c.hero_cta} {arrow}
              </a>
              <span className="text-sm font-semibold text-slate-500 px-2">{c.hero_note}</span>
            </div>
          </div>

          {/* Hero visual: the real in-call screen */}
          <div className={`lg:col-span-6 hero-fade ${isRtl ? "lg:order-first" : ""}`} data-reveal={isRtl ? "left" : "right"}>
            <div className="relative float-soft">
              <div
                className="absolute -inset-6 blur-3xl opacity-40 -z-10 accent-shift rounded-[2rem]"
                style={{ backgroundColor: "oklch(0.6 0.22 268 / 0.5)" }}
              />
              <div className="relative rounded-2xl overflow-hidden border border-black/5 shot-shadow hero-img bg-white">
                <img src={IMG.call} alt={isAr ? "مكالمة فيديو حقيقية في RELAY" : "A real RELAY video call"} className="w-full h-auto block" />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* Live stats band */}
      {/* ---------------------------------------------------------------- */}
      <section id="stats-band" className="relative z-10 px-6 py-14 md:py-20">
        <div className="max-w-5xl mx-auto text-center mb-10">
          <h2 className="text-2xl sm:text-3xl font-extrabold mb-3" style={{ color: "oklch(0.22 0.03 265)" }} data-reveal="words">
            {c.stats_title.split(" ").map((w, i, arr) => (
              <span key={i} className="word" style={{ "--wd": `${i * 60}ms` } as React.CSSProperties}>
                {w}
                {i < arr.length - 1 ? "\u00A0" : ""}
              </span>
            ))}
          </h2>
          <p className="text-slate-500" data-reveal style={{ "--d": "120ms" } as React.CSSProperties}>
            {c.stats_sub}
          </p>
        </div>
        <div className="max-w-5xl mx-auto grid grid-cols-2 lg:grid-cols-4 gap-4 md:gap-6">
          {[
            { label: c.stat_registered, value: fmt(registered), live: false },
            { label: c.stat_guests, value: fmt(guests), live: false },
            { label: c.stat_total, value: fmt(total), live: false },
            { label: c.stat_online, value: fmt(online), live: true },
          ].map((s, i) => (
            <div
              key={i}
              data-reveal
              style={{ "--d": `${i * 90}ms` } as React.CSSProperties}
              className="relative rounded-2xl border border-black/5 bg-white shadow-sm card-hover p-5 md:p-7 text-center overflow-hidden flex flex-col items-center justify-center min-h-[140px]"
            >
              <div className="absolute -top-8 left-1/2 -translate-x-1/2 w-24 h-24 rounded-full blur-2xl opacity-20 accent-shift" style={{ backgroundColor: ACCENT }} />
              <div className="relative w-full">
                {s.live && (
                  <span className="inline-flex items-center gap-1.5 mb-1.5 text-[10px] font-bold tracking-wider uppercase" style={{ color: "oklch(0.6 0.18 150)" }}>
                    <span className="w-1.5 h-1.5 rounded-full animate-pulse" style={{ backgroundColor: "oklch(0.6 0.18 150)" }} />
                    LIVE
                  </span>
                )}
                <div
                  className="font-extrabold tabular-nums leading-none break-words text-[clamp(1.6rem,7vw,2.8rem)]"
                  style={{ color: s.live ? "oklch(0.55 0.16 150)" : "oklch(0.25 0.05 265)" }}
                >
                  {s.value}
                </div>
                <div className="mt-2 text-xs md:text-sm text-slate-500 leading-tight">{s.label}</div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* Group video conference — up to 10 people */}
      {/* ---------------------------------------------------------------- */}
      <section className="relative z-10 px-6 py-16 md:py-24">
        <div className="max-w-6xl mx-auto grid lg:grid-cols-12 gap-10 lg:gap-14 items-center">
          <div className={`lg:col-span-5 ${isRtl ? "lg:order-last" : ""}`} data-reveal={isRtl ? "left" : "right"}>
            <span className="inline-flex items-center gap-2 text-xs font-bold tracking-[0.22em] uppercase mb-4 px-3 py-1.5 rounded-full accent-shift" style={{ color: ACCENT, backgroundColor: "oklch(0.55 0.22 268 / 0.10)" }}>
              {c.group_kicker}
            </span>
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-extrabold tracking-tight mb-4" style={{ color: "oklch(0.2 0.03 265)" }}>
              {c.group_title}
            </h2>
            <p className="text-slate-600 text-lg leading-relaxed mb-6">{c.group_sub}</p>
            <span
              className="inline-flex items-center gap-2 px-4 py-2 rounded-full text-sm font-extrabold text-white mb-7 accent-shift"
              style={{ backgroundColor: ACCENT, boxShadow: "0 12px 30px -10px oklch(0.55 0.22 268 / 0.7)" }}
            >
              <span className="w-2 h-2 rounded-full bg-white/90 animate-pulse" />
              {c.group_badge}
            </span>
            <ul className="space-y-3">
              {c.group_points.map((p, i) => (
                <li key={i} className="flex items-start gap-3">
                  <span
                    className="mt-1 w-5 h-5 rounded-full flex items-center justify-center text-white text-[11px] font-bold accent-shift flex-shrink-0"
                    style={{ backgroundColor: ACCENT }}
                  >
                    ✓
                  </span>
                  <span className="text-slate-700">{p}</span>
                </li>
              ))}
            </ul>
          </div>
          <div className={`lg:col-span-7 ${isRtl ? "lg:order-first" : ""}`} data-reveal={isRtl ? "right" : "left"} style={{ "--d": "120ms" } as React.CSSProperties}>
            <ConferenceGrid label={c.shot_group_t} />
          </div>
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* Privacy — hide your identity */}
      {/* ---------------------------------------------------------------- */}
      <section className="relative z-10 px-6 py-16 md:py-24">
        <div
          className="max-w-6xl mx-auto rounded-3xl border border-black/5 shadow-sm overflow-hidden relative"
          style={{ background: "linear-gradient(135deg, oklch(0.97 0.02 268), oklch(0.96 0.03 210))" }}
          data-reveal
        >
          <div className="grid lg:grid-cols-12 gap-10 p-8 md:p-14 items-center">
            <div className={`lg:col-span-7 ${isRtl ? "lg:order-last" : ""}`}>
              <span className="text-xs font-bold tracking-[0.22em] uppercase block mb-4 accent-shift" style={{ color: ACCENT }}>
                {c.privacy_kicker}
              </span>
              <h2 className="text-3xl sm:text-4xl md:text-5xl font-extrabold tracking-tight mb-5" style={{ color: "oklch(0.2 0.03 265)" }}>
                {c.privacy_title}
              </h2>
              <p className="text-slate-600 text-lg leading-relaxed mb-7">{c.privacy_sub}</p>
              <ul className="space-y-3">
                {c.privacy_points.map((p, i) => (
                  <li key={i} className="flex items-start gap-3">
                    <span
                      className="mt-1 w-5 h-5 rounded-full flex items-center justify-center text-white text-[11px] font-bold accent-shift flex-shrink-0"
                      style={{ backgroundColor: ACCENT }}
                    >
                      ✓
                    </span>
                    <span className="text-slate-700">{p}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div className="lg:col-span-5 flex justify-center">
              <div className="relative w-full max-w-[260px] float-soft">
                <div className="absolute -inset-8 blur-3xl opacity-30 -z-10 rounded-full accent-shift" style={{ backgroundColor: ACCENT }} />
                <img
                  src={IMG.mobile}
                  alt={isAr ? "رقم مجهول الهوية في RELAY" : "Your anonymous RELAY number"}
                  loading="lazy"
                  className="w-full h-auto block rounded-2xl border border-black/5 shot-shadow"
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* Four pillars */}
      {/* ---------------------------------------------------------------- */}
      <section className="relative z-10 px-6 pb-4">
        <div className="max-w-6xl mx-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
          {c.pillars.map((p, i) => (
            <div
              key={i}
              data-reveal
              style={{ "--d": `${i * 90}ms` } as React.CSSProperties}
              className="rounded-2xl border border-black/5 bg-white shadow-sm card-hover p-6"
            >
              <div className="w-11 h-11 rounded-xl flex items-center justify-center mb-4 text-white font-extrabold accent-shift" style={{ backgroundColor: ACCENT }}>
                {i + 1}
              </div>
              <h3 className="text-lg font-bold mb-2" style={{ color: "oklch(0.24 0.04 265)" }}>{p.t}</h3>
              <p className="text-sm text-slate-500 leading-relaxed">{p.d}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* Product-style capability blocks — TALK / MEET / CHAT */}
      {/* ---------------------------------------------------------------- */}
      <section className="relative z-10 px-6 py-16 md:py-24">
        <div className="max-w-3xl mx-auto text-center mb-14">
          <span className="text-xs font-bold tracking-[0.2em] uppercase block mb-3 accent-shift" style={{ color: ACCENT }} data-reveal>
            {c.feat_kicker}
          </span>
          <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight mb-4" style={{ color: "oklch(0.22 0.03 265)" }} data-reveal="words">
            {c.shots_title.split(" ").map((w, i, arr) => (
              <span key={i} className="word" style={{ "--wd": `${i * 55}ms` } as React.CSSProperties}>
                {w}
                {i < arr.length - 1 ? "\u00A0" : ""}
              </span>
            ))}
          </h2>
          <p className="text-slate-500 text-lg leading-relaxed" data-reveal style={{ "--d": "120ms" } as React.CSSProperties}>
            {c.shots_sub}
          </p>
        </div>
        <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-6">
          {c.blocks.map((b, i) => (
            <div
              key={i}
              data-reveal
              style={{ "--d": `${i * 110}ms` } as React.CSSProperties}
              className="relative rounded-3xl border border-black/5 bg-white shadow-sm card-hover p-7 overflow-hidden flex flex-col"
            >
              <div className="absolute -top-10 -right-10 w-32 h-32 rounded-full blur-3xl opacity-20 accent-shift" style={{ backgroundColor: ACCENT }} aria-hidden="true" />
              <span className="relative inline-flex self-start items-center px-3 py-1 rounded-full text-[11px] font-extrabold tracking-[0.2em] mb-5 accent-shift" style={{ color: ACCENT, backgroundColor: "oklch(0.55 0.22 268 / 0.10)" }}>
                {b.tag}
              </span>
              <h3 className="relative text-xl font-extrabold mb-3" style={{ color: "oklch(0.22 0.03 265)" }}>
                {b.title}
              </h3>
              <p className="relative text-sm text-slate-500 leading-relaxed mb-6">{b.desc}</p>
              <ul className="relative mt-auto space-y-2.5">
                {b.items.map((it, j) => (
                  <li key={j} className="flex items-center gap-2.5 text-sm text-slate-700">
                    <span className="w-4 h-4 rounded-full flex items-center justify-center text-white text-[9px] font-bold accent-shift flex-shrink-0" style={{ backgroundColor: ACCENT }} aria-hidden="true">
                      ✓
                    </span>
                    {it}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* Features grid */}
      {/* ---------------------------------------------------------------- */}
      <section className="relative z-10 px-6 py-16 md:py-24">
        <div className="max-w-3xl mx-auto text-center mb-14">
          <span className="text-xs font-bold tracking-[0.2em] uppercase block mb-3 accent-shift" style={{ color: ACCENT }} data-reveal>
            {c.feat_kicker}
          </span>
          <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight mb-4" style={{ color: "oklch(0.22 0.03 265)" }} data-reveal="words">
            {c.feat_title.split(" ").map((w, i, arr) => (
              <span key={i} className="word" style={{ "--wd": `${i * 55}ms` } as React.CSSProperties}>
                {w}
                {i < arr.length - 1 ? "\u00A0" : ""}
              </span>
            ))}
          </h2>
          <p className="text-slate-500 text-lg leading-relaxed" data-reveal style={{ "--d": "120ms" } as React.CSSProperties}>
            {c.feat_sub}
          </p>
        </div>
        <div className="max-w-6xl mx-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
          {c.features.map((f, i) => (
            <div
              key={i}
              data-reveal
              style={{ "--d": `${(i % 3) * 80}ms` } as React.CSSProperties}
              className="group rounded-2xl border border-black/5 bg-white shadow-sm card-hover p-6"
            >
              <div className="w-10 h-10 rounded-xl flex items-center justify-center mb-4 font-bold text-white text-sm accent-shift" style={{ backgroundColor: ACCENT }}>
                {String(i + 1).padStart(2, "0")}
              </div>
              <h3 className="text-lg font-bold mb-2" style={{ color: "oklch(0.24 0.04 265)" }}>{f.t}</h3>
              <p className="text-sm text-slate-500 leading-relaxed">{f.d}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* Screenshot showcase — real app screens with explanations */}
      {/* ---------------------------------------------------------------- */}
      <section className="relative z-10 px-6 py-12 md:py-20">
        <div className="max-w-3xl mx-auto text-center mb-16">
          <span className="text-xs font-bold tracking-[0.2em] uppercase block mb-3 accent-shift" style={{ color: ACCENT }} data-reveal>
            {c.shots_kicker}
          </span>
          <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight mb-4" style={{ color: "oklch(0.22 0.03 265)" }} data-reveal="words">
            {c.shots_title.split(" ").map((w, i, arr) => (
              <span key={i} className="word" style={{ "--wd": `${i * 55}ms` } as React.CSSProperties}>
                {w}
                {i < arr.length - 1 ? "\u00A0" : ""}
              </span>
            ))}
          </h2>
          <p className="text-slate-500 text-lg" data-reveal style={{ "--d": "120ms" } as React.CSSProperties}>
            {c.shots_sub}
          </p>
        </div>

        <div className="max-w-6xl mx-auto space-y-20 lg:space-y-28">
          {[
            { img: IMG.dialer, title: c.shot_dialer_t, desc: c.shot_dialer_d },
            { img: IMG.messages, title: c.shot_chat_t, desc: c.shot_chat_d },
            { img: IMG.call, title: c.shot_group_t, desc: c.shot_group_d },
            { img: IMG.contacts, title: c.shot_contacts_t, desc: c.shot_contacts_d },
          ].map((s, i) => {
            const flip = i % 2 === 1;
            return (
              <div key={i} className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-14 items-center">
                <div data-reveal={flip ? "right" : "left"} className={`lg:col-span-7 ${flip ? "lg:order-last" : ""}`}>
                  <div className="relative rounded-2xl overflow-hidden border border-black/5 shot-shadow bg-white">
                    <div className="absolute -inset-8 blur-3xl opacity-20 -z-10 accent-shift" style={{ backgroundColor: ACCENT }} />
                    <img src={s.img} alt={s.title} loading="lazy" className="w-full h-auto block" />
                  </div>
                </div>
                <div className="lg:col-span-5" data-reveal={flip ? "left" : "right"} style={{ "--d": "120ms" } as React.CSSProperties}>
                  <h3 className="text-2xl sm:text-3xl font-extrabold mb-4" style={{ color: "oklch(0.22 0.03 265)" }}>{s.title}</h3>
                  <p className="text-slate-600 text-base sm:text-lg leading-relaxed">{s.desc}</p>
                </div>
              </div>
            );
          })}
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* Mobile */}
      {/* ---------------------------------------------------------------- */}
      <section className="relative z-10 px-6 py-16 md:py-24">
        <div className="max-w-5xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
          <div className={isAr ? "lg:order-last" : ""} data-reveal={isAr ? "right" : "left"}>
            <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight mb-5" style={{ color: "oklch(0.22 0.03 265)" }}>
              {c.mobile_t}
            </h2>
            <p className="text-slate-600 text-lg leading-relaxed">{c.mobile_d}</p>
            <a
              href="/app"
              className="mt-8 inline-flex items-center justify-center px-6 py-3 rounded-full text-sm font-bold text-white transition-all active:scale-[0.97] accent-shift"
              style={{ backgroundColor: ACCENT, boxShadow: "0 12px 32px -8px oklch(0.55 0.22 268 / 0.6)" }}
            >
              {c.sticky_cta} {arrow}
            </a>
          </div>
          <div className="flex justify-center" data-reveal={isRtl ? "left" : "right"} style={{ "--d": "120ms" } as React.CSSProperties}>
            <div className="relative w-full max-w-[300px] float-soft">
              <div className="absolute -inset-10 blur-3xl opacity-25 -z-10 rounded-full accent-shift" style={{ backgroundColor: ACCENT }} />
              <img src={IMG.mobile} alt={c.mobile_t} loading="lazy" className="w-full h-auto block rounded-2xl border border-black/5 shot-shadow" />
            </div>
          </div>
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* Download / Coming soon */}
      {/* ---------------------------------------------------------------- */}
      <section className="relative z-10 px-6 py-16 md:py-24">
        <div className="max-w-4xl mx-auto text-center">
          <p className="text-xs font-bold tracking-[0.2em] mb-3" style={{ color: ACCENT }}>
            {c.dl_kicker}
          </p>
          <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight mb-4" style={{ color: "oklch(0.22 0.03 265)" }}>
            {c.dl_title}
          </h2>
          <p className="text-slate-600 text-lg leading-relaxed max-w-2xl mx-auto mb-10">{c.dl_sub}</p>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-5 max-w-3xl mx-auto">
            {/* App Store — coming soon */}
            <div className="relative flex flex-col items-center gap-3 rounded-2xl border border-black/5 bg-white/70 backdrop-blur px-5 py-7 shot-shadow opacity-90">
              <span className="absolute top-3 right-3 text-[10px] font-bold uppercase tracking-wide px-2 py-0.5 rounded-full" style={{ backgroundColor: "oklch(0.93 0.02 265)", color: "oklch(0.45 0.03 265)" }}>
                {c.dl_soon}
              </span>
              <svg viewBox="0 0 24 24" className="w-9 h-9" fill="oklch(0.30 0.02 265)" aria-hidden="true"><path d="M16.365 1.43c0 1.14-.417 2.2-1.11 2.98-.75.85-1.98 1.5-3.16 1.41-.14-1.11.43-2.28 1.09-3.02.74-.84 2.03-1.46 3.18-1.37zM20.94 17.02c-.57 1.31-.84 1.9-1.57 3.06-1.02 1.62-2.46 3.64-4.24 3.65-1.58.02-1.99-1.03-4.14-1.02-2.15.01-2.6 1.04-4.18 1.02-1.78-.02-3.14-1.84-4.16-3.46-2.86-4.53-3.16-9.85-1.4-12.68 1.25-2.02 3.23-3.2 5.09-3.2 1.9 0 3.09 1.04 4.66 1.04 1.52 0 2.45-1.04 4.65-1.04 1.66 0 3.42.9 4.68 2.46-4.11 2.25-3.44 8.12.01 10.19z"/></svg>
              <div className="text-sm font-bold" style={{ color: "oklch(0.25 0.02 265)" }}>{c.dl_ios}</div>
            </div>

            {/* Google Play — coming soon */}
            <div className="relative flex flex-col items-center gap-3 rounded-2xl border border-black/5 bg-white/70 backdrop-blur px-5 py-7 shot-shadow opacity-90">
              <span className="absolute top-3 right-3 text-[10px] font-bold uppercase tracking-wide px-2 py-0.5 rounded-full" style={{ backgroundColor: "oklch(0.93 0.02 265)", color: "oklch(0.45 0.03 265)" }}>
                {c.dl_soon}
              </span>
              <svg viewBox="0 0 24 24" className="w-9 h-9" aria-hidden="true"><path d="M3.6 2.3c-.3.2-.5.6-.5 1.1v17.2c0 .5.2.9.5 1.1l.1.1L13 12.6v-.2L3.7 2.2z" fill="#00d2ff"/><path d="M16.5 15.9L13 12.5v-.2l3.5-3.4.1.1 4.2 2.4c1.2.7 1.2 1.8 0 2.5z" fill="#ffce00"/><path d="M16.6 15.8L13 12.4 3.6 21.7c.4.4 1 .5 1.7.1z" fill="#ff3a44"/><path d="M16.6 9L5.3 2.1c-.7-.4-1.3-.3-1.7.1L13 12.4z" fill="#00e676"/></svg>
              <div className="text-sm font-bold" style={{ color: "oklch(0.25 0.02 265)" }}>{c.dl_android}</div>
            </div>

            {/* Direct APK — placeholder link until user provides it */}
            <a
              href="#"
              aria-disabled="true"
              onClick={(e) => { e.preventDefault(); toast.info(c.dl_apk_note); }}
              className="relative flex flex-col items-center gap-3 rounded-2xl border-2 border-dashed px-5 py-7 shot-shadow transition-all active:scale-[0.98] cursor-pointer"
              style={{ borderColor: "oklch(0.75 0.05 145)", backgroundColor: "oklch(0.97 0.02 145)" }}
            >
              <span className="absolute top-3 right-3 text-[10px] font-bold uppercase tracking-wide px-2 py-0.5 rounded-full" style={{ backgroundColor: "oklch(0.90 0.06 145)", color: "oklch(0.40 0.08 145)" }}>
                {c.dl_soon}
              </span>
              <svg viewBox="0 0 24 24" className="w-9 h-9" fill="#3ddc84" aria-hidden="true"><path d="M17.6 9.48l1.84-3.18a.38.38 0 00-.66-.38l-1.87 3.23a11.4 11.4 0 00-9.82 0L5.22 5.92a.38.38 0 10-.66.38L6.4 9.48A10.8 10.8 0 001 18h22a10.8 10.8 0 00-5.4-8.52zM7 15.25a1 1 0 110-2 1 1 0 010 2zm10 0a1 1 0 110-2 1 1 0 010 2z"/></svg>
              <div className="text-sm font-bold" style={{ color: "oklch(0.30 0.06 145)" }}>{c.dl_apk}</div>
              <div className="text-[11px] font-medium leading-tight" style={{ color: "oklch(0.45 0.05 145)" }}>{c.dl_apk_note}</div>
            </a>
          </div>
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* FAQ */}
      {/* ---------------------------------------------------------------- */}
      <section className="relative z-10 px-6 py-12 md:py-20">
        <div className="max-w-3xl mx-auto text-center mb-12">
          <span className="text-xs font-bold tracking-[0.2em] uppercase block mb-3 accent-shift" style={{ color: ACCENT }} data-reveal>
            FAQ
          </span>
          <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight" style={{ color: "oklch(0.22 0.03 265)" }} data-reveal="words">
            {c.stats_title.split(" ").map((w, i, arr) => (
              <span key={i} className="word" style={{ "--wd": `${i * 55}ms` } as React.CSSProperties}>
                {w}
                {i < arr.length - 1 ? "\u00A0" : ""}
              </span>
            ))}
          </h2>
        </div>
        <div className="max-w-3xl mx-auto grid grid-cols-1 gap-4">
          {c.faqs.map((f, i) => (
            <details
              key={i}
              data-reveal
              style={{ "--d": `${i * 80}ms` } as React.CSSProperties}
              className="group rounded-2xl border border-black/5 bg-white shadow-sm card-hover px-6 py-1 open:shadow-md"
            >
              <summary className="flex items-center justify-between gap-4 cursor-pointer list-none py-5 font-bold select-none" style={{ color: "oklch(0.24 0.04 265)" }}>
                <span>{f.q}</span>
                <span
                  className="w-7 h-7 flex-shrink-0 rounded-full flex items-center justify-center text-white text-lg leading-none accent-shift transition-transform duration-200 group-open:rotate-45"
                  style={{ backgroundColor: ACCENT }}
                  aria-hidden="true"
                >
                  +
                </span>
              </summary>
              <p className="text-slate-600 leading-relaxed pb-5 -mt-1">{f.a}</p>
            </details>
          ))}
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* Final CTA */}
      {/* ---------------------------------------------------------------- */}
      <section className="relative z-10 px-6 py-20 md:py-28">
        <div
          className="max-w-4xl mx-auto text-center relative rounded-3xl border border-black/5 shadow-sm px-8 py-16 overflow-hidden"
          style={{ background: "linear-gradient(135deg, oklch(0.55 0.22 268), oklch(0.5 0.2 290))" }}
          data-reveal
        >
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[420px] h-[420px] rounded-full blur-[100px] opacity-30 animate-pulse-glow pointer-events-none" style={{ backgroundColor: "oklch(0.72 0.16 210)" }} />
          <h2 className="relative text-3xl sm:text-5xl font-extrabold tracking-tight mb-5 text-white" data-reveal="words">
            {c.cta_title.split(" ").map((w, i, arr) => (
              <span key={i} className="word" style={{ "--wd": `${i * 50}ms` } as React.CSSProperties}>
                {w}
                {i < arr.length - 1 ? "\u00A0" : ""}
              </span>
            ))}
          </h2>
          <p className="relative text-white/85 text-lg mb-9">{c.cta_sub}</p>
          <a
            href="/app"
            className="relative inline-flex items-center justify-center px-9 py-4 rounded-full text-base font-bold transition-all active:scale-[0.97] bg-white"
            style={{ color: "oklch(0.45 0.22 268)" }}
          >
            {c.cta_btn} {arrow}
          </a>
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* Footer */}
      {/* ---------------------------------------------------------------- */}
      <footer className="relative z-10 border-t border-black/5 px-6 py-10">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4 text-center md:text-start">
          <div className="flex items-center gap-3">
            <span className="w-2.5 h-2.5 rounded-full accent-shift" style={{ backgroundColor: ACCENT, boxShadow: `0 0 10px ${ACCENT}` }} />
            <div>
              <div className="font-extrabold tracking-[0.16em] text-sm" style={{ color: "oklch(0.25 0.04 265)" }}>RELAY</div>
              <div className="text-xs text-slate-500">{c.footer_tag}</div>
            </div>
          </div>
          <div className="text-xs text-slate-400 flex flex-col md:items-end gap-1">
            <span>{c.footer_rights}</span>
            <span>v{APP_VERSION}</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
