import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";

/**
 * v2.4.0 — landing page authored by grok-build-0.1.
 *
 * These tests pin the *invariants* of the generated file (asset paths, sections,
 * scroll-loop primitives, byline) plus the pure scroll-math the page relies on,
 * without booting the full component.
 *
 * If you swap to a new grok output, regenerate the snapshot of /manus-storage/
 * URLs at the top of this file and rerun pnpm test.
 */

// ---------------------------------------------------------------------------
// 1. Static analysis of client/src/pages/Home.tsx
// ---------------------------------------------------------------------------
const HOME_TSX = fs.readFileSync(
  path.resolve(__dirname, "Home.tsx"),
  "utf8",
);

describe("Home.tsx — generated by grok-build-0.1", () => {
  it("default-exports a Home component", () => {
    expect(HOME_TSX).toMatch(/export\s+default\s+Home/);
  });

  it("declares Home as a function or React component", () => {
    expect(HOME_TSX).toMatch(/const\s+Home\s*[:=]/);
  });

  it("uses requestAnimationFrame to drive the scroll loop", () => {
    expect(HOME_TSX).toMatch(/requestAnimationFrame/);
  });

  it("respects prefers-reduced-motion via matchMedia", () => {
    expect(HOME_TSX).toMatch(/prefers-reduced-motion/);
    expect(HOME_TSX).toMatch(/matchMedia/);
  });

  it("attaches a passive scroll listener to window", () => {
    expect(HOME_TSX).toMatch(/addEventListener\(['"]scroll['"]/);
    expect(HOME_TSX).toMatch(/passive:\s*true/);
  });

  it("renders the v2.4.0 footer with the grok-build-0.1 byline", () => {
    expect(HOME_TSX).toMatch(/v2\.4\.0/);
    expect(HOME_TSX).toMatch(/grok-build-0\.1/);
  });

  it("links the primary CTA to /app", () => {
    expect(HOME_TSX).toMatch(/href=["']\/app["']/);
  });

  it("includes the BROWSER CALLS kicker and END OF SCROLL finale labels", () => {
    expect(HOME_TSX).toMatch(/BROWSER CALLS/);
    expect(HOME_TSX).toMatch(/END OF SCROLL/);
  });

  it("renders six story sections with stable ids section-1..section-6", () => {
    for (let i = 1; i <= 6; i++) {
      expect(HOME_TSX).toContain(`section-${i}`);
    }
  });

  it("each section heading is present in the source verbatim", () => {
    for (const heading of [
      "Your number",
      "Live check",
      "Messages",
      "Notes to self",
      "Contacts",
      "Profile",
    ]) {
      expect(HOME_TSX).toContain(heading);
    }
  });
});

// ---------------------------------------------------------------------------
// 2. Asset URLs — every screenshot must be the real /manus-storage/ ref
//    captured from the running app, not a stock illustration.
// ---------------------------------------------------------------------------
const REAL_SCREENSHOT_PATHS = [
  "/manus-storage/dialer-empty_98fa535c.png",
  "/manus-storage/dialer-typed_8ad4c6c2.png",
  "/manus-storage/messages-empty_014c8014.png",
  "/manus-storage/messages-thread_3b435df8.png",
  "/manus-storage/contacts-empty_ee775a4f.png",
  "/manus-storage/profile_15ca08be.png",
];

describe("Home.tsx — real screenshot assets", () => {
  it("references every required /manus-storage/ asset exactly once", () => {
    for (const p of REAL_SCREENSHOT_PATHS) {
      const occurrences = HOME_TSX.split(p).length - 1;
      expect(occurrences).toBeGreaterThanOrEqual(1);
    }
  });

  it("six unique paths, one per real app screen", () => {
    expect(new Set(REAL_SCREENSHOT_PATHS).size).toBe(6);
  });

  it("never falls back to remote http(s) image hosts", () => {
    expect(HOME_TSX).not.toMatch(/src=["']https?:\/\//);
  });

  it("does not import images from the local filesystem", () => {
    expect(HOME_TSX).not.toMatch(/import\s+\w+\s+from\s+['"]\.\.?\/.+\.(png|jpe?g|webp|svg)['"]/);
  });
});

// ---------------------------------------------------------------------------
// 3. Pure scroll-math: mirrors grok-build-0.1's update loop.
//
//   parallax = (rect.top - vh * 0.35) * -0.065
//   halo    = (rect.top - vh * 0.20) * -0.12
//   panel   = clamp(((vh * 0.68) - rect.top) / 260, 0, 1)
// ---------------------------------------------------------------------------
function phoneParallax(rectTop: number, vh: number): number {
  return (rectTop - vh * 0.35) * -0.065;
}

function haloOffset(rectTop: number, vh: number): number {
  return (rectTop - vh * 0.2) * -0.12;
}

function panelProgress(rectTop: number, vh: number): number {
  const enter = vh * 0.68;
  return Math.max(0, Math.min(1, (enter - rectTop) / 260));
}

describe("Home — phone parallax mapping (grok-build-0.1 formula)", () => {
  const VH = 800;

  it("translates downward as the section enters from below the viewport", () => {
    // rectTop > vh * 0.35  =>  parallax < 0
    expect(phoneParallax(VH, VH)).toBeLessThan(0);
  });

  it("zeroes out exactly at the equilibrium point rectTop = vh * 0.35", () => {
    expect(phoneParallax(VH * 0.35, VH)).toBeCloseTo(0, 6);
  });

  it("translates upward as the section scrolls above the equilibrium", () => {
    expect(phoneParallax(0, VH)).toBeGreaterThan(0);
    expect(phoneParallax(-VH, VH)).toBeGreaterThan(phoneParallax(0, VH));
  });

  it("is a strictly decreasing function of rectTop", () => {
    const ys = [VH * 1.5, VH, VH * 0.5, 0, -VH * 0.5, -VH].map((t) =>
      phoneParallax(t, VH),
    );
    for (let i = 1; i < ys.length; i++) {
      expect(ys[i]).toBeGreaterThan(ys[i - 1]);
    }
  });
});

describe("Home — halo offset is faster than phone parallax", () => {
  const VH = 800;

  it("halo coefficient (0.12) exceeds phone coefficient (0.065)", () => {
    const phoneDelta = phoneParallax(0, VH) - phoneParallax(VH, VH);
    const haloDelta = haloOffset(0, VH) - haloOffset(VH, VH);
    expect(Math.abs(haloDelta)).toBeGreaterThan(Math.abs(phoneDelta));
  });
});

describe("Home — detail-panel reveal mapping", () => {
  const VH = 800;
  // Reveal starts at rectTop = vh*0.68 (= 544 with vh=800) and finishes
  // when rectTop has fallen another 260 px below that (i.e. rectTop = 284).

  it("invisible before the section reaches 68 % of the viewport", () => {
    expect(panelProgress(VH, VH)).toBe(0);
    expect(panelProgress(VH * 0.69, VH)).toBe(0);
  });

  it("fully revealed once rectTop drops 260 px past the trigger", () => {
    expect(panelProgress(VH * 0.68 - 260, VH)).toBeCloseTo(1, 6);
    expect(panelProgress(0, VH)).toBe(1);
  });

  it("midpoint of the fade lands at half-revealed", () => {
    expect(panelProgress(VH * 0.68 - 130, VH)).toBeCloseTo(0.5, 6);
  });

  it("monotonic: the panel never fades back as the section keeps scrolling", () => {
    const tops = [VH, VH * 0.7, VH * 0.5, VH * 0.3, 0, -VH * 0.5];
    const ps = tops.map((t) => panelProgress(t, VH));
    for (let i = 1; i < ps.length; i++) {
      expect(ps[i]).toBeGreaterThanOrEqual(ps[i - 1]);
    }
  });
});

// ---------------------------------------------------------------------------
// 4. Sticky CTA threshold: 480 px of scrollY.
// ---------------------------------------------------------------------------
describe("Home — sticky CTA threshold", () => {
  it("hides below 480 px of scroll, shows at and beyond", () => {
    const threshold = 480;
    const shouldShow = (y: number) => y > threshold;
    expect(shouldShow(0)).toBe(false);
    expect(shouldShow(479)).toBe(false);
    expect(shouldShow(480)).toBe(false);
    expect(shouldShow(481)).toBe(true);
    expect(shouldShow(2000)).toBe(true);
  });

  it("Home.tsx references the 480 px threshold literally", () => {
    expect(HOME_TSX).toMatch(/scrollY\s*>\s*480/);
  });
});

// ---------------------------------------------------------------------------
// 5. Section alternation (even = phone-left, odd = phone-right).
// ---------------------------------------------------------------------------
describe("Home — section alternation", () => {
  it("isLeft = index % 2 === 0 produces alternating sides for six sections", () => {
    const isLeft = (i: number) => i % 2 === 0;
    expect([0, 1, 2, 3, 4, 5].map(isLeft)).toEqual([
      true,
      false,
      true,
      false,
      true,
      false,
    ]);
  });
});
