import { useState, useEffect } from "react";
import { trpc } from "@/lib/trpc";
import { APP_VERSION } from "@shared/version";

/* -------------------------------------------------------------------------- */
/*  RELAY landing page (AR / EN) — light, unique, highly animated.             */
/*                                                                            */
/*  This file is the PUBLIC marketing page only. It never touches the in-app  */
/*  experience or any backend logic. Arabic flips the document to RTL.        */
/*                                                                            */
/*  Marketing copy was regenerated by an LLM and stored in                    */
/*  scripts/landing-copy.json, then inlined here for a zero-fetch render.      */
/* -------------------------------------------------------------------------- */

type Lang = "en" | "ar";

/* Real screenshots captured directly from the live RELAY app at
   your-chat.org/app. Asset URLs are tied to the project lifecycle and never
   expire. The "call" shot is the real in-call UI with two real faces composited
   into the video tiles (the rest of the interface is 100% the live product). */
const IMG = {
  call: "/manus-storage/relay-v2-call_7d2eafdd.jpg",
  dialer: "/manus-storage/relay-v2-dialer_299ac1a9.jpg",
  messages: "/manus-storage/relay-v2-messages_a863d696.jpg",
  contacts: "/manus-storage/relay-v2-contacts_bc1018a3.jpg",
  mobile: "/manus-storage/relay-v2-mobile_b0ee18b9.jpg",
};

const T = {
  en: {
    dir: "ltr" as const,
    nav_open: "Open RELAY",
    hero_kicker: "MEET RELAY",
    hero_title_1: "Share your number.",
    hero_title_2: "Hide yourself.",
    hero_sub:
      "Instant voice, video, and chat right in your browser. No sign-ups, no installs, and absolutely no personal data shared — just a disposable 6-digit code.",
    hero_note: "Zero setup. 100% free.",
    hero_cta: "Get Your Number",
    sticky_cta: "Open RELAY",
    stats_title: "RELAY by the numbers",
    stats_sub: "Fast, private connections happening everywhere, every second.",
    stat_registered: "Active numbers",
    stat_guests: "Quick guests",
    stat_total: "Total identities",
    stat_online: "Online now",
    privacy_kicker: "TOTAL PRIVACY",
    privacy_title: "Keep your real life truly private.",
    privacy_sub:
      "With RELAY, your real contacts, phone number, and email stay locked away. You get a unique 6-digit code to share. Anyone can call you on the web — but nobody can trace who you are.",
    privacy_points: [
      "Your real phone number is never exposed.",
      "No address book, no email, no tracking.",
      "Calls go directly, peer-to-peer, between devices.",
    ],
    blocks_kicker: "ONE APP, THREE WAYS",
    blocks_title: "Talk. Meet. Chat.",
    blocks_sub:
      "Everything RELAY does, grouped into three simple ways to connect — all from the same 6-digit number.",
    blocks: [
      {
        tag: "TALK",
        t: "Voice & video, one-to-one",
        d: "Connect directly with crystal-clear voice and video. Your private 6-digit number is all you need.",
        items: ["Private voice calls", "HD video chat", "Multi-device ring", "Full call history"],
      },
      {
        tag: "MEET",
        t: "Group rooms, your way",
        d: "Host group video sessions with a single link. Powerful host controls put you in charge of the room.",
        items: ["Invite by one link", "Host controls", "Mute everyone", "Active-speaker spotlight"],
      },
      {
        tag: "CHAT",
        t: "Rich messaging, private",
        d: "Send messages, share files, and record voice notes — all tied to your private 6-digit identity.",
        items: ["Text messaging", "File sharing", "Voice notes", "Image sharing"],
      },
    ],
    feat_kicker: "POWERFUL COMMUNICATOR",
    feat_title: "Everything you need, built for the web.",
    feat_sub:
      "Ditch the heavy apps. Experience high-quality calls, rich chats, and complete meeting control directly from any browser.",
    pillars: [
      {
        t: "Hide your identity",
        d: "Share your temporary 6-digit number — never your personal contacts or email.",
      },
      {
        t: "One-to-many rooms",
        d: "Launch full group video spaces with just one simple invite link.",
      },
      {
        t: "Fast & easy",
        d: "No downloads, no logins, zero installs. It works instantly in your browser.",
      },
      {
        t: "Free & unique",
        d: "A completely peer-to-peer connection that costs you absolutely nothing.",
      },
    ],
    features: [
      { t: "6-digit numbers", d: "Get a unique, instant code that keeps your real phone number hidden." },
      { t: "HD voice & video", d: "Crystal-clear one-on-one calling directly through your web browser." },
      { t: "Group rooms", d: "Host large video gatherings effortlessly with a single shareable link." },
      { t: "Host controls", d: "Mute everyone, spotlight speakers, transfer host duties, or pin users easily." },
      { t: "Rich messaging", d: "Share files, photos, and voice notes inside an active, private chat." },
      { t: "Screen share & PiP", d: "Present your screen or watch calls in Picture-in-Picture mode." },
      { t: "Smart audio routing", d: "Switch audio outputs seamlessly to Bluetooth or external speakers." },
      { t: "Call history", d: "Track past sessions and redial your contacts with a single tap." },
      { t: "100% peer-to-peer", d: "Your calls are direct, fast, highly private, and completely anonymous." },
    ],
    shots_kicker: "INSIDE RELAY",
    shots_title: "Clean. Fast. Frictionless.",
    shots_sub: "Take a look at how simple talking online should actually be.",
    shot_dialer_t: "The smart dialer",
    shot_dialer_d:
      "Just type a 6-digit code and hit call. No contact lists, no setup — it is that easy.",
    shot_chat_t: "Rich chat rooms",
    shot_chat_d:
      "Send files, images, and voice notes instantly, right while you are on a call.",
    shot_group_t: "One-link gathering",
    shot_group_d:
      "Host entire group video rooms with a single invite link. The active speaker takes center stage automatically.",
    shot_contacts_t: "Private contacts",
    shot_contacts_d:
      "Save people by their 6-digit code — no phone numbers, no emails, no address book ever leaves your device.",
    mobile_t: "Mobile-first design",
    mobile_d:
      "Open the website on any phone browser and it rings just like a normal call — no app required, even on the go.",
    faq_kicker: "GOOD TO KNOW",
    faq_title: "Questions, answered.",
    faqs: [
      {
        q: "Do I need to install anything or sign up?",
        a: "No. RELAY runs entirely in your web browser. Just open the page, get your number, and start connecting — no download, no account.",
      },
      {
        q: "How does the 6-digit number keep me private?",
        a: "You only ever share that 6-digit code. Your real phone number, email, and contacts stay hidden, so people reach you without ever knowing who you really are.",
      },
      {
        q: "Can I host a group call?",
        a: "Yes. Create a room and share one invite link. As host you get mute-all, active-speaker spotlight, and full control of the room.",
      },
      {
        q: "Is RELAY really free?",
        a: "Yes. One-to-one calls, group rooms, and messaging are all free — calls are peer-to-peer, straight between devices.",
      },
    ],
    cta_title: "Ready to claim your code?",
    cta_sub: "Start calling instantly. No emails. No passwords. No strings.",
    cta_btn: "Launch RELAY now",
    footer_tag: "Talk freely, stay hidden.",
    footer_rights: "All rights reserved.",
  },
  ar: {
    dir: "rtl" as const,
    nav_open: "افتح ريليه",
    hero_kicker: "تعرّف على ريليه",
    hero_title_1: "شارك رقمك فقط.",
    hero_title_2: "واحمِ هويتك.",
    hero_sub:
      "اتصالات صوتية وفيديو ومحادثات فورية من متصفحك مباشرة. بدون تسجيل، بدون تحميل، وبدون مشاركة أي بيانات شخصية — رمز من ٦ أرقام فقط.",
    hero_note: "بدون إعدادات. مجاني بالكامل.",
    hero_cta: "احصل على رقمك الآن",
    sticky_cta: "افتح ريليه",
    stats_title: "ريليه بالأرقام",
    stats_sub: "اتصالات سريعة وآمنة تحدث في كل مكان، وفي كل ثانية.",
    stat_registered: "الأرقام النشطة",
    stat_guests: "الضيوف السريعون",
    stat_total: "إجمالي الهويات",
    stat_online: "المتصلون الآن",
    privacy_kicker: "خصوصية مطلقة",
    privacy_title: "أبقِ حياتك الحقيقية سرّية تماماً.",
    privacy_sub:
      "مع ريليه، تبقى جهات اتصالك الحقيقية ورقم هاتفك وبريدك الإلكتروني مخفية تماماً. تحصل على رمز فريد من ٦ أرقام لمشاركته. يمكن لأي شخص الاتصال بك عبر الويب — لكن لا أحد يستطيع تتبّع هويتك.",
    privacy_points: [
      "رقم هاتفك الحقيقي لا يظهر إطلاقاً.",
      "لا دفتر عناوين، لا بريد إلكتروني، لا تتبّع.",
      "المكالمات تتم مباشرة من جهاز إلى جهاز.",
    ],
    blocks_kicker: "تطبيق واحد، ثلاث طرق",
    blocks_title: "تحدّث. اجتمع. دردش.",
    blocks_sub:
      "كل ما يفعله ريليه، مُجمّعاً في ثلاث طرق بسيطة للتواصل — كلها من نفس الرقم المكوّن من ٦ أرقام.",
    blocks: [
      {
        tag: "تحدّث",
        t: "صوت وفيديو، فرداً لفرد",
        d: "تواصل مباشرة بصوت وفيديو فائقي الوضوح. رقمك الخاص المكوّن من ٦ أرقام هو كل ما تحتاجه.",
        items: ["مكالمات صوتية خاصة", "فيديو عالي الدقة", "رنين متعدد الأجهزة", "سجل مكالمات كامل"],
      },
      {
        tag: "اجتمع",
        t: "غرف جماعية بطريقتك",
        d: "استضف جلسات فيديو جماعية برابط واحد. أدوات تحكّم قوية تضعك في قيادة الغرفة.",
        items: ["دعوة برابط واحد", "تحكّم المضيف", "كتم الجميع", "إبراز المتحدّث النشط"],
      },
      {
        tag: "دردش",
        t: "مراسلة غنية وخاصة",
        d: "أرسل الرسائل، شارك الملفات، وسجّل ملاحظات صوتية — كلها مرتبطة بهويتك الخاصة المكوّنة من ٦ أرقام.",
        items: ["رسائل نصية", "مشاركة الملفات", "ملاحظات صوتية", "مشاركة الصور"],
      },
    ],
    feat_kicker: "أداة تواصل قوية",
    feat_title: "كل ما تحتاجه، مصمّم للويب.",
    feat_sub:
      "تخلّص من التطبيقات الثقيلة. جرّب مكالمات عالية الجودة، ومحادثات غنية، وتحكّماً كاملاً بالاجتماعات مباشرة من أي متصفح.",
    pillars: [
      { t: "اخفِ هويتك", d: "شارك رقمك المؤقت المكوّن من ٦ أرقام، ولا تشارك جهات اتصالك أو بريدك أبداً." },
      { t: "غرف للجميع", d: "أنشئ مساحات فيديو جماعية كاملة برابط دعوة واحد وبسيط." },
      { t: "سريع وسهل", d: "بدون تنزيل أو تسجيل دخول. يعمل فوراً على متصفحك مباشرة." },
      { t: "مجاني وفريد", d: "اتصال مباشر بالكامل من جهاز لجهاز لا يكلّفك أي شيء مطلقاً." },
    ],
    features: [
      { t: "رقم من ٦ أرقام", d: "احصل على رمز فوري وفريد يحافظ على سرّية رقم هاتفك الحقيقي." },
      { t: "صوت وفيديو HD", d: "مكالمات ثنائية فائقة الوضوح مباشرة من خلال متصفح الويب." },
      { t: "غرف جماعية", d: "استضف اجتماعات فيديو جماعية كبيرة بسهولة عبر رابط واحد قابل للمشاركة." },
      { t: "تحكّم المضيف", d: "اكتم صوت الجميع، سلّط الضوء على المتحدثين، أو انقل صلاحية المضيف بسهولة." },
      { t: "مراسلة غنية", d: "شارك الملفات والصور والرسائل الصوتية داخل دردشة نشطة وآمنة." },
      { t: "مشاركة الشاشة و PiP", d: "اعرض شاشتك أو تابع مكالماتك في وضع صورة داخل صورة بسلاسة." },
      { t: "توجيه صوت ذكي", d: "بدّل مخرجات الصوت بسهولة إلى البلوتوث أو مكبّرات الصوت الخارجية." },
      { t: "سجل المكالمات", d: "تتبّع جلساتك السابقة وأعد الاتصال بجهات اتصالك بضغطة واحدة." },
      { t: "اتصال مباشر آمن", d: "مكالماتك مباشرة وسريعة وذات خصوصية تامة دون أي تتبّع لهويتك." },
    ],
    shots_kicker: "داخل ريليه",
    shots_title: "بساطة. سرعة. سلاسة.",
    shots_sub: "ألقِ نظرة على مدى السهولة التي يجب أن تكون عليها المحادثات عبر الإنترنت.",
    shot_dialer_t: "الطلب الذكي",
    shot_dialer_d:
      "اكتب الرمز المكوّن من ٦ أرقام واضغط اتصال. بلا قوائم جهات اتصال ولا إعدادات — بهذه البساطة.",
    shot_chat_t: "غرف دردشة غنية",
    shot_chat_d:
      "أرسل الملفات والصور والملاحظات الصوتية فوراً، حتى وأنت في مكالمة.",
    shot_group_t: "تجمّع برابط واحد",
    shot_group_d:
      "استضف غرف فيديو جماعية كاملة برابط دعوة واحد. ويركّز التطبيق تلقائياً على الشخص المتحدّث.",
    shot_contacts_t: "جهات اتصال خاصة",
    shot_contacts_d:
      "احفظ الأشخاص برمزهم المكوّن من ٦ أرقام — بلا أرقام هواتف ولا بريد، ولا تغادر دفتر عناوينك جهازك أبداً.",
    mobile_t: "تصميم للهواتف أولاً",
    mobile_d:
      "افتح الموقع من متصفح أي هاتف وسيرنّ تماماً كأي مكالمة عادية — دون أي تطبيق، حتى أثناء تنقّلك.",
    faq_kicker: "معلومات مفيدة",
    faq_title: "أسئلة، وإجاباتها.",
    faqs: [
      {
        q: "هل أحتاج إلى تثبيت أي شيء أو التسجيل؟",
        a: "لا. يعمل ريليه بالكامل في متصفحك. فقط افتح الصفحة، احصل على رقمك، وابدأ التواصل — بلا تحميل ولا حساب.",
      },
      {
        q: "كيف يحافظ الرقم المكوّن من ٦ أرقام على خصوصيتي؟",
        a: "أنت تشارك هذا الرمز المكوّن من ٦ أرقام فقط. يبقى رقم هاتفك الحقيقي وبريدك وجهات اتصالك مخفية، فيصل إليك الناس دون أن يعرفوا من أنت حقاً.",
      },
      {
        q: "هل يمكنني استضافة مكالمة جماعية؟",
        a: "نعم. أنشئ غرفة وشارك رابط دعوة واحداً. وبصفتك المضيف تحصل على كتم الجميع وإبراز المتحدّث والتحكّم الكامل بالغرفة.",
      },
      {
        q: "هل ريليه مجاني حقاً؟",
        a: "نعم. المكالمات الفردية والغرف الجماعية والمراسلة كلها مجانية — والمكالمات مباشرة من جهاز لجهاز.",
      },
    ],
    cta_title: "هل أنت جاهز لطلب رمزك؟",
    cta_sub: "ابدأ الاتصال فوراً. لا بريد إلكتروني، لا كلمات مرور، لا شروط.",
    cta_btn: "شغّل ريليه الآن",
    footer_tag: "تحدّث بحرية، وابقَ مخفياً.",
    footer_rights: "جميع الحقوق محفوظة.",
  },
};

/* Light, unique palette: warm paper background + deep ink text + an electric
   indigo→cyan accent. Distinct from the in-app dark theme on purpose. */
const PAGE_BG = "oklch(0.985 0.006 250)";
const ACCENT = "oklch(0.55 0.22 268)"; // electric indigo

/* Word-by-word reveal. Each word keeps a non-collapsing trailing space so the
   inline-block words never run together. Works in LTR and RTL. */
function WordReveal({
  text,
  className,
  wordClassName,
  wordStyle,
  baseDelay = 0,
  step = 55,
}: {
  text: string;
  className?: string;
  wordClassName?: string;
  wordStyle?: React.CSSProperties;
  baseDelay?: number;
  step?: number;
}) {
  const words = text.split(" ");
  return (
    <span className={className} data-reveal="words">
      {words.map((w, i) => (
        <span
          key={i}
          className={`word${wordClassName ? ` ${wordClassName}` : ""}`}
          style={{ "--wd": `${baseDelay + i * step}ms`, ...wordStyle } as React.CSSProperties}
        >
          {w}
          {i < words.length - 1 ? "\u00A0" : ""}
        </span>
      ))}
    </span>
  );
}

/* Reveal-on-scroll: adds `.is-in` to every [data-reveal] the first time it
   scrolls into view. One shared observer; honors prefers-reduced-motion in CSS. */
function useScrollReveal(deps: unknown[] = []) {
  useEffect(() => {
    const els = Array.from(
      document.querySelectorAll<HTMLElement>("[data-reveal]"),
    );
    if (els.length === 0) return;
    const io = new IntersectionObserver(
      (entries) => {
        for (const e of entries) {
          if (e.isIntersecting) {
            e.target.classList.add("is-in");
            io.unobserve(e.target);
          }
        }
      },
      { threshold: 0.14, rootMargin: "0px 0px -8% 0px" },
    );
    els.forEach((el) => io.observe(el));
    return () => io.disconnect();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, deps);
}

function useCountUp(target: number, run: boolean, duration = 1300) {
  const [value, setValue] = useState(0);
  useEffect(() => {
    if (!run) return;
    if (target <= 0) {
      setValue(0);
      return;
    }
    let raf = 0;
    const start = performance.now();
    const tick = (now: number) => {
      const p = Math.min(1, (now - start) / duration);
      const eased = 1 - Math.pow(1 - p, 3);
      setValue(Math.round(target * eased));
      if (p < 1) raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [target, run, duration]);
  return value;
}

/* Full-page scroll-linked motion. Writes CSS custom properties on <html>:
     --sp  = overall scroll progress 0..1   (progress bar width)
     --sy  = raw scrollY in px               (hero parallax)
     --hue = scroll-driven hue offset in deg (page-wide accent drift)
   rAF-throttled + passive; gated by prefers-reduced-motion. */
function useScrollMotion() {
  useEffect(() => {
    if (
      window.matchMedia &&
      window.matchMedia("(prefers-reduced-motion: reduce)").matches
    ) {
      return;
    }
    const root = document.documentElement;
    let raf = 0;
    const update = () => {
      raf = 0;
      const max = root.scrollHeight - window.innerHeight;
      const sp = max > 0 ? Math.min(1, window.scrollY / max) : 0;
      root.style.setProperty("--sp", String(sp));
      root.style.setProperty("--sy", String(window.scrollY));
      // Drift the accent through an indigo→violet→cyan arc as you scroll.
      root.style.setProperty("--hue", String(Math.round(sp * 70)));
    };
    const onScroll = () => {
      if (!raf) raf = requestAnimationFrame(update);
    };
    update();
    window.addEventListener("scroll", onScroll, { passive: true });
    window.addEventListener("resize", onScroll, { passive: true });
    return () => {
      window.removeEventListener("scroll", onScroll);
      window.removeEventListener("resize", onScroll);
      if (raf) cancelAnimationFrame(raf);
      root.style.removeProperty("--sp");
      root.style.removeProperty("--sy");
      root.style.removeProperty("--hue");
    };
  }, []);
}

export default function Home() {
  const [lang, setLang] = useState<Lang>("en");
  const [statsVisible, setStatsVisible] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const t = T[lang];
  const isAr = lang === "ar";

  const { data: stats } = trpc.stats.public.useQuery(undefined, {
    refetchInterval: 30_000,
    staleTime: 15_000,
  });

  // Reflect language on <html> for correct RTL rendering.
  useEffect(() => {
    const html = document.documentElement;
    const prevDir = html.getAttribute("dir");
    const prevLang = html.getAttribute("lang");
    html.setAttribute("dir", t.dir);
    html.setAttribute("lang", lang);
    return () => {
      if (prevDir) html.setAttribute("dir", prevDir);
      else html.removeAttribute("dir");
      if (prevLang) html.setAttribute("lang", prevLang);
      else html.removeAttribute("lang");
    };
  }, [lang, t.dir]);

  // Paint <html>/<body> with the page background so any rubber-band overscroll
  // matches the page instead of revealing the app's dark body color. Restored
  // on unmount so in-app routes keep their own background.
  useEffect(() => {
    const html = document.documentElement;
    const body = document.body;
    const prev = {
      htmlBg: html.style.backgroundColor,
      bodyBg: body.style.backgroundColor,
      overscroll: html.style.overscrollBehaviorY,
    };
    html.style.backgroundColor = PAGE_BG;
    body.style.backgroundColor = PAGE_BG;
    html.style.overscrollBehaviorY = "none";
    return () => {
      html.style.backgroundColor = prev.htmlBg;
      body.style.backgroundColor = prev.bodyBg;
      html.style.overscrollBehaviorY = prev.overscroll;
    };
  }, []);

  // Show the sticky floating "Open RELAY" button after the user scrolls past
  // the hero so it stays with them all the way down.
  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 520);
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  useScrollReveal([lang]);
  useScrollMotion();

  // Trigger count-up once the stats band scrolls into view.
  useEffect(() => {
    const el = document.getElementById("stats-band");
    if (!el) return;
    const io = new IntersectionObserver(
      (entries) => {
        if (entries.some((e) => e.isIntersecting)) {
          setStatsVisible(true);
          io.disconnect();
        }
      },
      { threshold: 0.3 },
    );
    io.observe(el);
    return () => io.disconnect();
  }, []);

  const registered = useCountUp(stats?.registeredUsers ?? 0, statsVisible);
  const guests = useCountUp(stats?.guestsServed ?? 0, statsVisible);
  const total = useCountUp(stats?.totalParties ?? 0, statsVisible);
  const online = stats?.onlineNow ?? 0;

  const fmt = (n: number) =>
    new Intl.NumberFormat(isAr ? "ar-EG" : "en-US").format(n);

  return (
    <div
      dir={t.dir}
      className="min-h-screen overflow-x-hidden relative font-sans selection:bg-[oklch(0.55_0.22_268)] selection:text-white"
      style={{ backgroundColor: PAGE_BG, color: "oklch(0.22 0.03 265)" }}
    >
      <style>{`
        :root{ --accent: ${ACCENT}; }

        /* Page-wide accent that drifts with scroll (--hue from useScrollMotion). */
        @media (prefers-reduced-motion: no-preference){
          .accent-shift{ filter: hue-rotate(calc(var(--hue, 0) * 1deg)); }
        }

        /* Subtle dotted grid on the light paper background. */
        .dot-bg{
          background-image: radial-gradient(oklch(0.55 0.22 268 / 0.07) 1px, transparent 1px);
          background-size: 26px 26px;
        }

        /* Top scroll-progress bar driven by --sp. */
        .scroll-progress{
          position:fixed;top:0;left:0;right:0;height:3px;z-index:60;
          transform-origin:0 50%;
          transform:scaleX(var(--sp, 0));
          background:linear-gradient(90deg, ${ACCENT}, oklch(0.72 0.16 210));
        }
        @media (prefers-reduced-motion: no-preference){
          .scroll-progress{ filter: hue-rotate(calc(var(--hue, 0) * 1deg)); }
        }
        [dir="rtl"] .scroll-progress{transform-origin:100% 50%;}

        /* Soft floating blobs behind the page — light, airy, very low opacity. */
        @keyframes blob-drift {
          0%   { transform: translate3d(-6%, -4%, 0) rotate(0deg) scale(1); }
          50%  { transform: translate3d(6%, 5%, 0) rotate(180deg) scale(1.1); }
          100% { transform: translate3d(-6%, -4%, 0) rotate(360deg) scale(1); }
        }
        .blobs{
          position:fixed;inset:-25%;z-index:0;pointer-events:none;
          background:
            radial-gradient(38% 38% at 22% 26%, oklch(0.6 0.22 268 / 0.16), transparent 70%),
            radial-gradient(42% 42% at 78% 72%, oklch(0.72 0.16 210 / 0.16), transparent 70%),
            radial-gradient(30% 30% at 60% 12%, oklch(0.7 0.2 330 / 0.10), transparent 70%);
          filter:blur(18px);
        }
        @media (prefers-reduced-motion: no-preference){
          .blobs{ animation:blob-drift 40s linear infinite; filter:blur(18px) hue-rotate(calc(var(--hue, 0) * 1.2deg)); }
        }

        /* Hero parallax + fade. */
        @media (prefers-reduced-motion: no-preference){
          .hero-img{ transform: translate3d(0, calc(var(--sy, 0) * -0.05px), 0); }
          .hero-fade{ opacity: clamp(0, calc(1 - var(--sy, 0) * 0.0016), 1); }
          .float-soft{ animation: float-soft 7s ease-in-out infinite; }
          @keyframes float-soft { 0%,100%{ transform: translateY(0) } 50%{ transform: translateY(-12px) } }
        }

        @keyframes pulse-glow { 0%,100%{opacity:.2;transform:scale(1)} 50%{opacity:.4;transform:scale(1.06)} }
        .animate-pulse-glow{animation:pulse-glow 7s infinite ease-in-out}

        /* Sticky floating CTA: pops in once the user scrolls past the hero. */
        .sticky-cta{
          opacity:0; transform: translateY(18px) scale(0.96);
          transition: opacity .3s cubic-bezier(0.23,1,0.32,1), transform .3s cubic-bezier(0.23,1,0.32,1);
          pointer-events:none;
        }
        .sticky-cta.show{ opacity:1; transform: translateY(0) scale(1); pointer-events:auto; }
        .sticky-cta:active{ transform: scale(0.96); }

        /* Scroll-reveal base. transform + opacity only (GPU-friendly). */
        [data-reveal]{ opacity:1;transform:none; }
        @media (prefers-reduced-motion: no-preference){
          [data-reveal]{
            opacity:0;
            transform:translateY(34px) scale(0.985);
            transition:opacity .7s cubic-bezier(0.23,1,0.32,1),
                       transform .7s cubic-bezier(0.23,1,0.32,1);
            transition-delay:var(--d, 0ms);
            will-change:opacity, transform;
          }
          [data-reveal="left"]{transform:translateX(-44px)}
          [data-reveal="right"]{transform:translateX(44px)}
          [data-reveal="words"]{ opacity:1;transform:none; }
          .word{
            display:inline-block;
            opacity:0;
            transform:translateY(0.55em);
            transition:opacity .55s cubic-bezier(0.23,1,0.32,1),
                       transform .55s cubic-bezier(0.23,1,0.32,1);
          }
          [data-reveal="words"].is-in .word{
            opacity:1; transform:none; transition-delay:var(--wd, 0ms);
          }
          [data-reveal].is-in{ opacity:1;transform:none; }
        }

        .card-hover{ transition: transform .2s cubic-bezier(0.23,1,0.32,1), box-shadow .2s cubic-bezier(0.23,1,0.32,1); }
        .card-hover:hover{ transform: translateY(-6px); }
        .shot-shadow{ box-shadow: 0 40px 80px -30px oklch(0.4 0.12 268 / 0.45); }
      `}</style>

      <div className="scroll-progress" aria-hidden="true" />
      <div className="blobs" aria-hidden="true" />
      <div className="absolute inset-0 dot-bg pointer-events-none z-0" />

      {/* ---------------------------------------------------------------- */}
      {/* Header */}
      {/* ---------------------------------------------------------------- */}
      <header className="fixed top-0 inset-x-0 h-20 z-50 flex items-center justify-between px-5 md:px-12 pointer-events-none">
        <div className="flex items-center gap-2.5 bg-white/70 backdrop-blur-md px-4 py-2 rounded-full border border-black/5 pointer-events-auto shadow-sm">
          <span
            className="w-2.5 h-2.5 rounded-full accent-shift"
            style={{ backgroundColor: ACCENT, boxShadow: `0 0 10px ${ACCENT}` }}
          />
          <span className="font-extrabold tracking-[0.18em] text-sm" style={{ color: "oklch(0.25 0.04 265)" }}>
            RELAY
          </span>
        </div>

        <div className="flex items-center gap-2 pointer-events-auto">
          <div className="flex items-center rounded-full bg-white/70 backdrop-blur-md border border-black/5 p-0.5 text-xs font-semibold shadow-sm">
            <button
              onClick={() => setLang("en")}
              className={`px-3 py-1.5 rounded-full transition-all duration-200 ${
                lang === "en" ? "text-white" : "text-slate-500 hover:text-slate-800"
              }`}
              style={lang === "en" ? { backgroundColor: ACCENT } : undefined}
              aria-pressed={lang === "en"}
            >
              EN
            </button>
            <button
              onClick={() => setLang("ar")}
              className={`px-3 py-1.5 rounded-full transition-all duration-200 ${
                lang === "ar" ? "text-white" : "text-slate-500 hover:text-slate-800"
              }`}
              style={lang === "ar" ? { backgroundColor: ACCENT } : undefined}
              aria-pressed={lang === "ar"}
            >
              ع
            </button>
          </div>
          <a
            href="/app"
            className="hidden sm:inline-flex items-center justify-center px-5 py-2.5 rounded-full text-sm font-semibold text-white transition-all active:scale-[0.97] accent-shift"
            style={{ backgroundColor: ACCENT, boxShadow: "0 8px 24px -6px oklch(0.55 0.22 268 / 0.6)" }}
          >
            {t.nav_open}
          </a>
        </div>
      </header>

      {/* ---------------------------------------------------------------- */}
      {/* Sticky floating CTA — stays with the user all the way down */}
      {/* ---------------------------------------------------------------- */}
      <a
        href="/app"
        className={`sticky-cta ${scrolled ? "show" : ""} accent-shift fixed bottom-6 z-[55] inline-flex items-center gap-2 px-6 py-3.5 rounded-full text-sm font-bold text-white ${
          isAr ? "left-5 md:left-8" : "right-5 md:right-8"
        }`}
        style={{ backgroundColor: ACCENT, boxShadow: "0 16px 40px -10px oklch(0.55 0.22 268 / 0.7)" }}
        aria-label={t.sticky_cta}
      >
        <span
          className="w-2 h-2 rounded-full bg-white/90 animate-pulse"
          aria-hidden="true"
        />
        {t.sticky_cta} {isAr ? "←" : "→"}
      </a>

      {/* ---------------------------------------------------------------- */}
      {/* Hero */}
      {/* ---------------------------------------------------------------- */}
      <section className="relative z-10 px-6 pt-32 pb-12 md:pt-40 md:pb-16">
        <div className="max-w-6xl mx-auto grid lg:grid-cols-12 gap-10 lg:gap-8 items-center">
          <div className={`lg:col-span-6 text-center lg:text-start hero-fade ${isAr ? "lg:order-last" : ""}`}>
            <span
              className="inline-block text-[11px] md:text-xs font-bold tracking-[0.28em] uppercase mb-5 px-3 py-1.5 rounded-full accent-shift"
              style={{ color: ACCENT, backgroundColor: "oklch(0.55 0.22 268 / 0.10)" }}
            >
              {t.hero_kicker}
            </span>
            <h1 className="text-[2.6rem] sm:text-5xl md:text-[3.4rem] lg:text-[3.6rem] font-extrabold tracking-tight leading-[1.06] mb-6" style={{ color: "oklch(0.2 0.03 265)" }}>
              <WordReveal text={t.hero_title_1} />
              <br />
              <WordReveal
                text={t.hero_title_2}
                wordClassName="text-transparent bg-clip-text accent-shift"
                wordStyle={{ backgroundImage: `linear-gradient(90deg, ${ACCENT}, oklch(0.62 0.18 210))` }}
                baseDelay={t.hero_title_1.split(" ").length * 55}
              />
            </h1>
            <p className="text-lg md:text-xl text-slate-600 max-w-xl mx-auto lg:mx-0 leading-relaxed mb-8">
              {t.hero_sub}
            </p>
            <div className="flex flex-col sm:flex-row items-center lg:items-start gap-4 sm:gap-3 justify-center lg:justify-start">
              <a
                href="/app"
                className="inline-flex items-center justify-center px-8 py-4 rounded-full text-base font-bold text-white transition-all active:scale-[0.97] accent-shift w-full sm:w-auto"
                style={{ backgroundColor: ACCENT, boxShadow: "0 16px 40px -10px oklch(0.55 0.22 268 / 0.7)" }}
              >
                {t.hero_cta} {isAr ? "←" : "→"}
              </a>
              <span className="text-sm font-semibold text-slate-500 px-2">{t.hero_note}</span>
            </div>
          </div>

          {/* Hero visual: the real in-call screen */}
          <div className={`lg:col-span-6 hero-fade ${isAr ? "lg:order-first" : ""}`} data-reveal={isAr ? "left" : "right"}>
            <div className="relative float-soft">
              <div
                className="absolute -inset-6 blur-3xl opacity-40 -z-10 accent-shift rounded-[2rem]"
                style={{ backgroundColor: "oklch(0.6 0.22 268 / 0.5)" }}
              />
              <div className="relative rounded-2xl overflow-hidden border border-black/5 shot-shadow hero-img bg-white">
                <img
                  src={IMG.call}
                  alt={isAr ? "مكالمة فيديو حقيقية في ريليه" : "A real RELAY video call"}
                  className="w-full h-auto block"
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* Live stats band */}
      {/* ---------------------------------------------------------------- */}
      <section id="stats-band" className="relative z-10 px-6 py-14 md:py-20">
        <div className="max-w-5xl mx-auto text-center mb-10">
          <h2 className="text-2xl sm:text-3xl font-extrabold mb-3" style={{ color: "oklch(0.22 0.03 265)" }} data-reveal="words">
            {t.stats_title.split(" ").map((w, i, arr) => (
              <span key={i} className="word" style={{ "--wd": `${i * 60}ms` } as React.CSSProperties}>
                {w}
                {i < arr.length - 1 ? "\u00A0" : ""}
              </span>
            ))}
          </h2>
          <p className="text-slate-500" data-reveal style={{ "--d": "120ms" } as React.CSSProperties}>
            {t.stats_sub}
          </p>
        </div>
        <div className="max-w-5xl mx-auto grid grid-cols-2 lg:grid-cols-4 gap-4 md:gap-6">
          {[
            { label: t.stat_registered, value: fmt(registered), live: false },
            { label: t.stat_guests, value: fmt(guests), live: false },
            { label: t.stat_total, value: fmt(total), live: false },
            { label: t.stat_online, value: fmt(online), live: true },
          ].map((s, i) => (
            <div
              key={i}
              data-reveal
              style={{ "--d": `${i * 90}ms` } as React.CSSProperties}
              className="relative rounded-2xl border border-black/5 bg-white shadow-sm card-hover p-5 md:p-7 text-center overflow-hidden flex flex-col items-center justify-center min-h-[140px]"
            >
              <div
                className="absolute -top-8 left-1/2 -translate-x-1/2 w-24 h-24 rounded-full blur-2xl opacity-20 accent-shift"
                style={{ backgroundColor: ACCENT }}
              />
              <div className="relative w-full">
                {s.live && (
                  <span className="inline-flex items-center gap-1.5 mb-1.5 text-[10px] font-bold tracking-wider uppercase" style={{ color: "oklch(0.6 0.18 150)" }}>
                    <span className="w-1.5 h-1.5 rounded-full animate-pulse" style={{ backgroundColor: "oklch(0.6 0.18 150)" }} />
                    LIVE
                  </span>
                )}
                <div
                  className="font-extrabold tabular-nums leading-none break-words text-[clamp(1.6rem,7vw,2.8rem)]"
                  style={{ color: s.live ? "oklch(0.55 0.16 150)" : "oklch(0.25 0.05 265)" }}
                >
                  {s.value}
                </div>
                <div className="mt-2 text-xs md:text-sm text-slate-500 leading-tight">{s.label}</div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* Privacy — hide your identity */}
      {/* ---------------------------------------------------------------- */}
      <section className="relative z-10 px-6 py-16 md:py-24">
        <div
          className="max-w-6xl mx-auto rounded-3xl border border-black/5 shadow-sm overflow-hidden relative"
          style={{ background: "linear-gradient(135deg, oklch(0.97 0.02 268), oklch(0.96 0.03 210))" }}
          data-reveal
        >
          <div className="grid lg:grid-cols-12 gap-10 p-8 md:p-14 items-center">
            <div className={`lg:col-span-7 ${isAr ? "lg:order-last" : ""}`}>
              <span className="text-xs font-bold tracking-[0.22em] uppercase block mb-4 accent-shift" style={{ color: ACCENT }}>
                {t.privacy_kicker}
              </span>
              <h2 className="text-3xl sm:text-4xl md:text-5xl font-extrabold tracking-tight mb-5" style={{ color: "oklch(0.2 0.03 265)" }}>
                {t.privacy_title}
              </h2>
              <p className="text-slate-600 text-lg leading-relaxed mb-7">{t.privacy_sub}</p>
              <ul className="space-y-3">
                {t.privacy_points.map((p, i) => (
                  <li key={i} className="flex items-start gap-3">
                    <span
                      className="mt-1 w-5 h-5 rounded-full flex items-center justify-center text-white text-[11px] font-bold accent-shift flex-shrink-0"
                      style={{ backgroundColor: ACCENT }}
                    >
                      ✓
                    </span>
                    <span className="text-slate-700">{p}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div className="lg:col-span-5 flex justify-center">
              <div className="relative w-full max-w-[260px] float-soft">
                <div className="absolute -inset-8 blur-3xl opacity-30 -z-10 rounded-full accent-shift" style={{ backgroundColor: ACCENT }} />
                <img
                  src={IMG.mobile}
                  alt={isAr ? "رقم مجهول الهوية في ريليه" : "Your anonymous RELAY number"}
                  loading="lazy"
                  className="w-full h-auto block rounded-2xl border border-black/5 shot-shadow"
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* Four pillars */}
      {/* ---------------------------------------------------------------- */}
      <section className="relative z-10 px-6 pb-4">
        <div className="max-w-6xl mx-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
          {t.pillars.map((p, i) => (
            <div
              key={i}
              data-reveal
              style={{ "--d": `${i * 90}ms` } as React.CSSProperties}
              className="rounded-2xl border border-black/5 bg-white shadow-sm card-hover p-6"
            >
              <div
                className="w-11 h-11 rounded-xl flex items-center justify-center mb-4 text-white font-extrabold accent-shift"
                style={{ backgroundColor: ACCENT }}
              >
                {i + 1}
              </div>
              <h3 className="text-lg font-bold mb-2" style={{ color: "oklch(0.24 0.04 265)" }}>{p.t}</h3>
              <p className="text-sm text-slate-500 leading-relaxed">{p.d}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* Product-style capability blocks — TALK / MEET / CHAT */}
      {/* Inspired by a modern multi-product layout; every claim is a real   */}
      {/* RELAY capability (no classroom / streaming / hardware / AI).       */}
      {/* ---------------------------------------------------------------- */}
      <section className="relative z-10 px-6 py-16 md:py-24">
        <div className="max-w-3xl mx-auto text-center mb-14">
          <span className="text-xs font-bold tracking-[0.2em] uppercase block mb-3 accent-shift" style={{ color: ACCENT }} data-reveal>
            {t.blocks_kicker}
          </span>
          <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight mb-4" style={{ color: "oklch(0.22 0.03 265)" }} data-reveal="words">
            {t.blocks_title.split(" ").map((w, i, arr) => (
              <span key={i} className="word" style={{ "--wd": `${i * 55}ms` } as React.CSSProperties}>
                {w}
                {i < arr.length - 1 ? "\u00A0" : ""}
              </span>
            ))}
          </h2>
          <p className="text-slate-500 text-lg leading-relaxed" data-reveal style={{ "--d": "120ms" } as React.CSSProperties}>
            {t.blocks_sub}
          </p>
        </div>
        <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-6">
          {t.blocks.map((b, i) => (
            <div
              key={i}
              data-reveal
              style={{ "--d": `${i * 110}ms` } as React.CSSProperties}
              className="relative rounded-3xl border border-black/5 bg-white shadow-sm card-hover p-7 overflow-hidden flex flex-col"
            >
              <div
                className="absolute -top-10 -right-10 w-32 h-32 rounded-full blur-3xl opacity-20 accent-shift"
                style={{ backgroundColor: ACCENT }}
                aria-hidden="true"
              />
              <span
                className="relative inline-flex self-start items-center px-3 py-1 rounded-full text-[11px] font-extrabold tracking-[0.2em] mb-5 accent-shift"
                style={{ color: ACCENT, backgroundColor: "oklch(0.55 0.22 268 / 0.10)" }}
              >
                {b.tag}
              </span>
              <h3 className="relative text-xl font-extrabold mb-3" style={{ color: "oklch(0.22 0.03 265)" }}>
                {b.t}
              </h3>
              <p className="relative text-sm text-slate-500 leading-relaxed mb-6">{b.d}</p>
              <ul className="relative mt-auto space-y-2.5">
                {b.items.map((it, j) => (
                  <li key={j} className="flex items-center gap-2.5 text-sm text-slate-700">
                    <span
                      className="w-4 h-4 rounded-full flex items-center justify-center text-white text-[9px] font-bold accent-shift flex-shrink-0"
                      style={{ backgroundColor: ACCENT }}
                      aria-hidden="true"
                    >
                      ✓
                    </span>
                    {it}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* Features grid */}
      {/* ---------------------------------------------------------------- */}
      <section className="relative z-10 px-6 py-16 md:py-24">
        <div className="max-w-3xl mx-auto text-center mb-14">
          <span className="text-xs font-bold tracking-[0.2em] uppercase block mb-3 accent-shift" style={{ color: ACCENT }} data-reveal>
            {t.feat_kicker}
          </span>
          <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight mb-4" style={{ color: "oklch(0.22 0.03 265)" }} data-reveal="words">
            {t.feat_title.split(" ").map((w, i, arr) => (
              <span key={i} className="word" style={{ "--wd": `${i * 55}ms` } as React.CSSProperties}>
                {w}
                {i < arr.length - 1 ? "\u00A0" : ""}
              </span>
            ))}
          </h2>
          <p className="text-slate-500 text-lg leading-relaxed" data-reveal style={{ "--d": "120ms" } as React.CSSProperties}>
            {t.feat_sub}
          </p>
        </div>
        <div className="max-w-6xl mx-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
          {t.features.map((f, i) => (
            <div
              key={i}
              data-reveal
              style={{ "--d": `${(i % 3) * 80}ms` } as React.CSSProperties}
              className="group rounded-2xl border border-black/5 bg-white shadow-sm card-hover p-6"
            >
              <div
                className="w-10 h-10 rounded-xl flex items-center justify-center mb-4 font-bold text-white text-sm accent-shift"
                style={{ backgroundColor: ACCENT }}
              >
                {String(i + 1).padStart(2, "0")}
              </div>
              <h3 className="text-lg font-bold mb-2" style={{ color: "oklch(0.24 0.04 265)" }}>{f.t}</h3>
              <p className="text-sm text-slate-500 leading-relaxed">{f.d}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* Screenshot showcase — real app screens with explanations */}
      {/* ---------------------------------------------------------------- */}
      <section className="relative z-10 px-6 py-12 md:py-20">
        <div className="max-w-3xl mx-auto text-center mb-16">
          <span className="text-xs font-bold tracking-[0.2em] uppercase block mb-3 accent-shift" style={{ color: ACCENT }} data-reveal>
            {t.shots_kicker}
          </span>
          <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight mb-4" style={{ color: "oklch(0.22 0.03 265)" }} data-reveal="words">
            {t.shots_title.split(" ").map((w, i, arr) => (
              <span key={i} className="word" style={{ "--wd": `${i * 55}ms` } as React.CSSProperties}>
                {w}
                {i < arr.length - 1 ? "\u00A0" : ""}
              </span>
            ))}
          </h2>
          <p className="text-slate-500 text-lg" data-reveal style={{ "--d": "120ms" } as React.CSSProperties}>
            {t.shots_sub}
          </p>
        </div>

        <div className="max-w-6xl mx-auto space-y-20 lg:space-y-28">
          {[
            { img: IMG.dialer, title: t.shot_dialer_t, desc: t.shot_dialer_d },
            { img: IMG.messages, title: t.shot_chat_t, desc: t.shot_chat_d },
            { img: IMG.call, title: t.shot_group_t, desc: t.shot_group_d },
            { img: IMG.contacts, title: t.shot_contacts_t, desc: t.shot_contacts_d },
          ].map((s, i) => {
            const flip = i % 2 === 1;
            return (
              <div key={i} className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-14 items-center">
                <div data-reveal={flip ? "right" : "left"} className={`lg:col-span-7 ${flip ? "lg:order-last" : ""}`}>
                  <div className="relative rounded-2xl overflow-hidden border border-black/5 shot-shadow bg-white">
                    <div className="absolute -inset-8 blur-3xl opacity-20 -z-10 accent-shift" style={{ backgroundColor: ACCENT }} />
                    <img src={s.img} alt={s.title} loading="lazy" className="w-full h-auto block" />
                  </div>
                </div>
                <div className="lg:col-span-5" data-reveal={flip ? "left" : "right"} style={{ "--d": "120ms" } as React.CSSProperties}>
                  <h3 className="text-2xl sm:text-3xl font-extrabold mb-4" style={{ color: "oklch(0.22 0.03 265)" }}>{s.title}</h3>
                  <p className="text-slate-600 text-base sm:text-lg leading-relaxed">{s.desc}</p>
                </div>
              </div>
            );
          })}
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* Mobile */}
      {/* ---------------------------------------------------------------- */}
      <section className="relative z-10 px-6 py-16 md:py-24">
        <div className="max-w-5xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
          <div className={isAr ? "lg:order-last" : ""} data-reveal={isAr ? "right" : "left"}>
            <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight mb-5" style={{ color: "oklch(0.22 0.03 265)" }}>
              {t.mobile_t}
            </h2>
            <p className="text-slate-600 text-lg leading-relaxed">{t.mobile_d}</p>
            <a
              href="/app"
              className="mt-8 inline-flex items-center justify-center px-6 py-3 rounded-full text-sm font-bold text-white transition-all active:scale-[0.97] accent-shift"
              style={{ backgroundColor: ACCENT, boxShadow: "0 12px 32px -8px oklch(0.55 0.22 268 / 0.6)" }}
            >
              {t.nav_open} {isAr ? "←" : "→"}
            </a>
          </div>
          <div className="flex justify-center" data-reveal={isAr ? "left" : "right"} style={{ "--d": "120ms" } as React.CSSProperties}>
            <div className="relative w-full max-w-[300px] float-soft">
              <div className="absolute -inset-10 blur-3xl opacity-25 -z-10 rounded-full accent-shift" style={{ backgroundColor: ACCENT }} />
              <img
                src={IMG.mobile}
                alt={t.mobile_t}
                loading="lazy"
                className="w-full h-auto block rounded-2xl border border-black/5 shot-shadow"
              />
            </div>
          </div>
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* FAQ */}
      {/* ---------------------------------------------------------------- */}
      <section className="relative z-10 px-6 py-12 md:py-20">
        <div className="max-w-3xl mx-auto text-center mb-12">
          <span className="text-xs font-bold tracking-[0.2em] uppercase block mb-3 accent-shift" style={{ color: ACCENT }} data-reveal>
            {t.faq_kicker}
          </span>
          <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight" style={{ color: "oklch(0.22 0.03 265)" }} data-reveal="words">
            {t.faq_title.split(" ").map((w, i, arr) => (
              <span key={i} className="word" style={{ "--wd": `${i * 55}ms` } as React.CSSProperties}>
                {w}
                {i < arr.length - 1 ? "\u00A0" : ""}
              </span>
            ))}
          </h2>
        </div>
        <div className="max-w-3xl mx-auto grid grid-cols-1 gap-4">
          {t.faqs.map((f, i) => (
            <details
              key={i}
              data-reveal
              style={{ "--d": `${i * 80}ms` } as React.CSSProperties}
              className="group rounded-2xl border border-black/5 bg-white shadow-sm card-hover px-6 py-1 open:shadow-md"
            >
              <summary className="flex items-center justify-between gap-4 cursor-pointer list-none py-5 font-bold select-none" style={{ color: "oklch(0.24 0.04 265)" }}>
                <span>{f.q}</span>
                <span
                  className="w-7 h-7 flex-shrink-0 rounded-full flex items-center justify-center text-white text-lg leading-none accent-shift transition-transform duration-200 group-open:rotate-45"
                  style={{ backgroundColor: ACCENT }}
                  aria-hidden="true"
                >
                  +
                </span>
              </summary>
              <p className="text-slate-600 leading-relaxed pb-5 -mt-1">{f.a}</p>
            </details>
          ))}
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* Final CTA */}
      {/* ---------------------------------------------------------------- */}
      <section className="relative z-10 px-6 py-20 md:py-28">
        <div
          className="max-w-4xl mx-auto text-center relative rounded-3xl border border-black/5 shadow-sm px-8 py-16 overflow-hidden"
          style={{ background: "linear-gradient(135deg, oklch(0.55 0.22 268), oklch(0.5 0.2 290))" }}
          data-reveal
        >
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[420px] h-[420px] rounded-full blur-[100px] opacity-30 animate-pulse-glow pointer-events-none" style={{ backgroundColor: "oklch(0.72 0.16 210)" }} />
          <h2 className="relative text-3xl sm:text-5xl font-extrabold tracking-tight mb-5 text-white" data-reveal="words">
            {t.cta_title.split(" ").map((w, i, arr) => (
              <span key={i} className="word" style={{ "--wd": `${i * 50}ms` } as React.CSSProperties}>
                {w}
                {i < arr.length - 1 ? "\u00A0" : ""}
              </span>
            ))}
          </h2>
          <p className="relative text-white/85 text-lg mb-9">{t.cta_sub}</p>
          <a
            href="/app"
            className="relative inline-flex items-center justify-center px-9 py-4 rounded-full text-base font-bold transition-all active:scale-[0.97] bg-white"
            style={{ color: "oklch(0.45 0.22 268)" }}
          >
            {t.cta_btn} {isAr ? "←" : "→"}
          </a>
        </div>
      </section>

      {/* ---------------------------------------------------------------- */}
      {/* Footer */}
      {/* ---------------------------------------------------------------- */}
      <footer className="relative z-10 border-t border-black/5 px-6 py-10">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4 text-center md:text-start">
          <div className="flex items-center gap-3">
            <span className="w-2.5 h-2.5 rounded-full accent-shift" style={{ backgroundColor: ACCENT, boxShadow: `0 0 10px ${ACCENT}` }} />
            <div>
              <div className="font-extrabold tracking-[0.16em] text-sm" style={{ color: "oklch(0.25 0.04 265)" }}>RELAY</div>
              <div className="text-xs text-slate-500">{t.footer_tag}</div>
            </div>
          </div>
          <div className="text-xs text-slate-400 flex flex-col md:items-end gap-1">
            <span>© {new Date().getFullYear()} RELAY · {t.footer_rights}</span>
            <span>v{APP_VERSION}</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
