// Auto-generated by scripts/gen-landing-copy.mjs via gemini-3.5-flash. Do not edit by hand.
// Multilingual RELAY landing copy (en, ar, es, fr, de, hi).
export const LANDING_COPY = {
  "en": {
    "lang_name": "English",
    "hero_kicker": "THE NEW ERA OF BROWSER COMMUNICATION",
    "hero_title_1": "Connect Instantly.",
    "hero_title_2": "Stay Fully Private.",
    "hero_sub": "Get your instant 6-digit number. Start voice, video, or group chats directly in your browser. No installs, no accounts, no trace.",
    "hero_note": "No phone number required. Free forever.",
    "hero_cta": "Get My Number",
    "sticky_cta": "Open RELAY",
    "stats_title": "Active Connections",
    "stats_sub": "People worldwide communicating on their own terms.",
    "stat_registered": "6-Digit Numbers Claimed",
    "stat_guests": "Active Callers",
    "stat_total": "Total Conversations",
    "stat_online": "Currently Online",
    "privacy_kicker": "ZERO IDENTITY EXPOSURE",
    "privacy_title": "Your real identity stays completely hidden.",
    "privacy_sub": "Stop giving away your phone number and email. RELAY uses a temporary 6-digit key to keep your private life private.",
    "group_kicker": "GROUP VIDEO CONFERENCES",
    "group_title": "Bring the team together. No sign-ups needed.",
    "group_sub": "Host dynamic video conferences with up to 10 people. Share a single link and control the room with professional host tools.",
    "group_badge": "Up to 10 people",
    "feat_kicker": "BUILT FOR SPEED",
    "feat_title": "Powering modern conversations.",
    "feat_sub": "Everything you need from a high-end calling app, right inside your web browser.",
    "shots_kicker": "PRODUCT SHOWCASE",
    "shots_title": "Take a look inside RELAY.",
    "shots_sub": "Clean, elegant, and blazing fast on any device.",
    "shot_dialer_t": "The Instant Dialer",
    "shot_dialer_d": "Type a name, claim your 6-digit number, and dial out instantly.",
    "shot_chat_t": "Rich Multimedia Chat",
    "shot_chat_d": "Share files, voice notes, and images securely without leaving your browser.",
    "shot_group_t": "10-Person Video Grid",
    "shot_group_d": "Crisp multi-screen video with active-speaker spotlight and full host controls.",
    "shot_contacts_t": "One-Tap History",
    "shot_contacts_d": "Quickly redial recent contacts from your local, secure call history.",
    "mobile_t": "Goes wherever you go.",
    "mobile_d": "Fully responsive on mobile and desktop browsers. No app store downloads required.",
    "cta_title": "Ready to go off-grid?",
    "cta_sub": "Claim your 6-digit number in 3 seconds and start talking.",
    "cta_btn": "Start Now - It's Free",
    "footer_tag": "RELAY - Private Browser Calls",
    "footer_rights": "© 2025 RELAY. All rights reserved. Peer-to-peer, secure, and instant.",
    "privacy_points": [
      "No real phone number or email required",
      "Connections are peer-to-peer for maximum security",
      "No chat history saved on any cloud database"
    ],
    "group_points": [
      "Host up to 10 people in a single room",
      "Multi-screen video grid with active-speaker spotlight",
      "Full host controls: mute-all, pin/remove, transfer host",
      "One single invite link for instant access"
    ],
    "pillars": [
      {
        "t": "Hide Your Identity",
        "d": "Never share your real phone number or email again."
      },
      {
        "t": "Host Up to 10",
        "d": "Run group video meetings easily with a single shareable link."
      },
      {
        "t": "Zero Setup",
        "d": "Runs entirely in your web browser with absolutely nothing to install."
      },
      {
        "t": "Free & Unique",
        "d": "Get your personal 6-digit number free of charge, instantly."
      }
    ],
    "blocks": [
      {
        "tag": "TALK",
        "title": "Instant Browser Calling",
        "desc": "Start crystal-clear 1-on-1 voice and video calls with anyone directly in the browser.",
        "items": [
          "One-Tap Redial",
          "Bluetooth Support",
          "Multi-Device Ringing",
          "Zero Account Setup"
        ]
      },
      {
        "tag": "MEET",
        "title": "Powerful Group Conferences",
        "desc": "Gather up to 10 people with a single, secure invite link. Take full control of your rooms.",
        "items": [
          "Up to 10 People",
          "Mute-All & Spotlight",
          "Multi-Screen Grid",
          "Host Transfer"
        ]
      },
      {
        "tag": "CHAT",
        "title": "Rich Messaging & Sharing",
        "desc": "Send files, images, and voice notes securely. Share your screen or use Picture-in-Picture mode.",
        "items": [
          "File & Image Sharing",
          "Voice Notes",
          "Screen Sharing",
          "Picture-in-Picture"
        ]
      }
    ],
    "features": [
      {
        "t": "Instant 6-Digit Key",
        "d": "Claim a random code instantly to start receiving calls without exposing your real info."
      },
      {
        "t": "HD Voice & Video",
        "d": "Enjoy ultra-clear, low-latency browser-to-browser calls built on modern WebRTC."
      },
      {
        "t": "10-Person Group Rooms",
        "d": "Bring up to ten participants together into a single, high-fidelity video space."
      },
      {
        "t": "Advanced Host Controls",
        "d": "Mute everyone, spotlight the current speaker, transfer host permissions, or remove guests instantly."
      },
      {
        "t": "Rich Private Chat",
        "d": "Exchange files, images, and voice recordings directly within your secure communication session."
      },
      {
        "t": "Screen & Picture-in-Picture",
        "d": "Present your desktop or watch video feeds in a floating window while browsing other tabs."
      },
      {
        "t": "Smart Audio Routing",
        "d": "Switch seamlessly between your speakers, headphones, or connected Bluetooth devices."
      },
      {
        "t": "Local Call History",
        "d": "See your recent incoming and outgoing calls and dial back with a single click."
      },
      {
        "t": "100% Identity Shield",
        "d": "No tracking, no address book syncing, and no sneaky background databases."
      }
    ],
    "faqs": [
      {
        "q": "Do I need to install an app or create an account?",
        "a": "No. RELAY works entirely inside your mobile or desktop web browser. There are no downloads, sign-ups, or passwords."
      },
      {
        "q": "How does the 6-digit number protect my privacy?",
        "a": "Instead of sharing your phone number or email, you give out your temporary 6-digit RELAY key. Your real identity and contacts stay hidden."
      },
      {
        "q": "Can I host a group video call?",
        "a": "Yes! You can host up to 10 people in a single video conference. Just share the invite link, and guests can join instantly without any account."
      },
      {
        "q": "Is RELAY really free?",
        "a": "Yes, RELAY is completely free. There are no premium paywalls or hidden costs for any of our features."
      }
    ]
  },
  "ar": {
    "lang_name": "العربية",
    "hero_kicker": "عهد جديد للتواصل عبر المتصفح",
    "hero_title_1": "تواصل فوراً.",
    "hero_title_2": "وحافظ على خصوصيتك.",
    "hero_sub": "احصل على رقمك الخاص المكون من 6 أرقام فوراً. ابدأ مكالمات صوتية ومرئية ومحادثات جماعية مباشرة من متصفحك. بدون تثبيت وبدون حساب.",
    "hero_note": "لا يتطلب رقم هاتف. مجاني بالكامل.",
    "hero_cta": "احصل على رقمك",
    "sticky_cta": "افتح RELAY",
    "stats_title": "الاتصالات النشطة",
    "stats_sub": "أشخاص من جميع أنحاء العالم يتواصلون بشروطهم الخاصة.",
    "stat_registered": "أرقام تم حجزها",
    "stat_guests": "متصلون نشطون",
    "stat_total": "إجمالي المحادثات",
    "stat_online": "متصل الآن",
    "privacy_kicker": "خصوصية مطلقة بدون كشف الهوية",
    "privacy_title": "تظل هويتك الحقيقية مخفية تماماً.",
    "privacy_sub": "توقف عن مشاركة رقم هاتفك وبريدك الإلكتروني. يستخدم RELAY رمزاً مؤقتاً من 6 أرقام للحفاظ على خصوصيتك كاملة.",
    "group_kicker": "مؤتمرات فيديو جماعية",
    "group_title": "اجمع فريقك معاً. دون الحاجة للتسجيل.",
    "group_sub": "استضف مؤتمرات فيديو ديناميكية مع ما يصل إلى 10 أشخاص. شارك رابطاً واحداً وتحكم في الغرفة باستخدام أدوات إشراف احترافية.",
    "group_badge": "حتى 10 أشخاص",
    "feat_kicker": "صُمم للسرعة",
    "feat_title": "قوة التواصل الحديث.",
    "feat_sub": "كل ما تحتاجه في تطبيق مكالمات متطور، مباشرة داخل متصفح الويب الخاص بك.",
    "shots_kicker": "معرض المنتج",
    "shots_title": "ألقِ نظرة داخل RELAY.",
    "shots_sub": "بسيط، أنيق، وسريع للغاية على أي جهاز.",
    "shot_dialer_t": "المتصل الفوري",
    "shot_dialer_d": "اكتب اسماً، واحصل على رقمك المكون من 6 أرقام، واتصل فوراً.",
    "shot_chat_t": "محادثة وسائط غنية",
    "shot_chat_d": "شارك الملفات، والملاحظات الصوتية، والصور بأمان دون مغادرة المتصفح.",
    "shot_group_t": "شبكة فيديو لـ 10 أشخاص",
    "shot_group_d": "فيديو جماعي واضح مع تسليط الضوء على المتحدث النشط وتحكم كامل للمضيف.",
    "shot_contacts_t": "تاريخ المكالمات بلمسة واحدة",
    "shot_contacts_d": "أعد الاتصال سريعاً بجهات الاتصال الأخيرة من سجل مكالماتك المحلي الآمن.",
    "mobile_t": "يعمل أينما كنت.",
    "mobile_d": "متوافق بالكامل مع متصفحات الهاتف والكمبيوتر. لا يتطلب أي تنزيل من متاجر التطبيقات.",
    "cta_title": "هل أنت مستعد لتأمين خصوصيتك؟",
    "cta_sub": "احصل على رقمك المكون من 6 أرقام في 3 ثوانٍ وابدأ التحدث الآن.",
    "cta_btn": "ابدأ الآن - مجاناً",
    "footer_tag": "RELAY - مكالمات متصفح آمنة",
    "footer_rights": "© 2025 RELAY. جميع الحقوق محفوظة. اتصال مباشر، آمن، وفوري.",
    "privacy_points": [
      "لا يتطلب رقم هاتف حقيقي أو بريد إلكتروني",
      "اتصالات مباشرة بين الأطراف لأقصى درجات الأمان",
      "لا يتم حفظ سجلات المحادثات في أي قاعدة بيانات سحابية"
    ],
    "group_points": [
      "استضافة ما يصل إلى 10 أشخاص في غرفة واحدة",
      "شبكة فيديو متعددة الشاشات مع تسليط الضوء على المتحدث النشط",
      "تحكم كامل للمضيف: كتم الصوت للجميع، التثبيت، ونقل الملكية",
      "رابط دعوة واحد وموحد للدخول الفوري"
    ],
    "pillars": [
      {
        "t": "إخفاء هويتك",
        "d": "لا تشارك رقم هاتفك أو بريدك الإلكتروني الحقيقي بعد اليوم."
      },
      {
        "t": "مجموعات حتى 10",
        "d": "أدر اجتماعات الفيديو الجماعية بسهولة عبر رابط واحد قابل للمشاركة."
      },
      {
        "t": "بدون إعدادات",
        "d": "يعمل بالكامل داخل متصفح الويب الخاص بك دون الحاجة لتثبيت أي شيء."
      },
      {
        "t": "مجاني وفريد",
        "d": "احصل على رقمك الشخصي المكون من 6 أرقام مجاناً وبشكل فوري."
      }
    ],
    "blocks": [
      {
        "tag": "TALK",
        "title": "مكالمات فورية عبر المتصفح",
        "desc": "ابدأ مكالمات صوتية ومرئية ثنائية فائقة الوضوح مع أي شخص مباشرة من المتصفح.",
        "items": [
          "إعادة الاتصال بنقرة واحدة",
          "دعم البلوتوث",
          "رنين على أجهزة متعددة",
          "بدون إعداد حساب"
        ]
      },
      {
        "tag": "MEET",
        "title": "مؤتمرات جماعية قوية",
        "desc": "اجمع ما يصل إلى 10 أشخاص برابط دعوة واحد وآمن. تحكم في الغرفة بالكامل.",
        "items": [
          "حتى 10 أشخاص",
          "كتم الجميع والتركيز",
          "شبكة شاشات متعددة",
          "نقل المضيف"
        ]
      },
      {
        "tag": "CHAT",
        "title": "مراسلة ومشاركة غنية",
        "desc": "أرسل الملفات والصور والملاحظات الصوتية بأمان. شارك شاشتك أو استخدم وضع صورة داخل صورة.",
        "items": [
          "مشاركة الملفات والصور",
          "ملاحظات صوتية",
          "مشاركة الشاشة",
          "صورة داخل صورة"
        ]
      }
    ],
    "features": [
      {
        "t": "مفتاح فوري من 6 أرقام",
        "d": "احصل على رمز عشوائي فوراً لتلقي المكالمات دون كشف بياناتك الحقيقية."
      },
      {
        "t": "صوت وصورة عالي الدقة",
        "d": "استمتع بمكالمات واضحة للغاية وزمن انتقال منخفض تعتمد على تقنية WebRTC الحديثة."
      },
      {
        "t": "غرف جماعية لـ 10 أشخاص",
        "d": "اجمع ما يصل إلى عشرة مشاركين معاً في مساحة فيديو واحدة عالية الجودة."
      },
      {
        "t": "أدوات تحكم متقدمة للمضيف",
        "d": "اكتم صوت الجميع، ركز على المتحدث الحالي، انقل الصلاحيات، أو أزل الضيوف فوراً."
      },
      {
        "t": "محادثة خاصة غنية",
        "d": "تبادل الملفات والصور والتسجيلات الصوتية مباشرة داخل جلسة الاتصال الآمنة."
      },
      {
        "t": "مشاركة الشاشة وصورة داخل صورة",
        "d": "اعرض سطح مكتبك أو شاهد بث الفيديو في نافذة عائمة أثناء تصفح التبويبات الأخرى."
      },
      {
        "t": "توجيه ذكي للصوت",
        "d": "تنقل بسلاسة بين مكبرات الصوت أو سماعات الرأس أو أجهزة البلوتوث المتصلة."
      },
      {
        "t": "سجل مكالمات محلي",
        "d": "شاهد مكالماتك الصادرة والواردة الأخيرة وأعد الاتصال بنقرة واحدة."
      },
      {
        "t": "درع خصوصية 100%",
        "d": "لا تتبع، لا مزامنة لدفتر العناوين، ولا قواعد بيانات خفية."
      }
    ],
    "faqs": [
      {
        "q": "هل أحتاج إلى تثبيت تطبيق أو إنشاء حساب؟",
        "a": "لا. يعمل RELAY بالكامل داخل متصفح الويب على الهاتف أو الكمبيوتر. لا توجد تنزيلات أو تسجيلات أو كلمات مرور."
      },
      {
        "q": "كيف يحمي الرقم المكون من 6 أرقام خصوصيتي؟",
        "a": "بدلاً من مشاركة رقم هاتفك أو بريدك الإلكتروني، فإنك تشارك رمز RELAY المكون من 6 أرقام فقط. تظل هويتك الحقيقية وجهات اتصالك مخفية تماماً."
      },
      {
        "q": "هل يمكنني استضافة مكالمة فيديو جماعية؟",
        "a": "نعم! يمكنك استضافة ما يصل إلى 10 أشخاص في مؤتمر فيديو واحد. ما عليك سوى مشاركة رابط الدعوة، ويمكن للضيوف الانضمام فوراً بدون حساب."
      },
      {
        "q": "هل RELAY مجاني حقاً؟",
        "a": "نعم، RELAY مجاني تماماً. لا توجد اشتراكات مدفوعة أو تكاليف مخفية لأي من ميزاتنا."
      }
    ]
  },
  "es": {
    "lang_name": "Español",
    "hero_kicker": "LA NUEVA ERA DE LA COMUNICACIÓN EN EL NAVEGADOR",
    "hero_title_1": "Conéctate al instante.",
    "hero_title_2": "Mantén tu privacidad.",
    "hero_sub": "Obtén tu número de 6 dígitos al instante. Inicia llamadas de voz, video o chats grupales directamente en tu navegador. Sin instalaciones ni cuentas.",
    "hero_note": "Sin número de teléfono. Gratis para siempre.",
    "hero_cta": "Obtener mi número",
    "sticky_cta": "Abrir RELAY",
    "stats_title": "Conexiones activas",
    "stats_sub": "Gente de todo el mundo comunicándose bajo sus propias reglas.",
    "stat_registered": "Números de 6 dígitos creados",
    "stat_guests": "Llamadas activas",
    "stat_total": "Conversaciones totales",
    "stat_online": "En línea ahora",
    "privacy_kicker": "CERO EXPOSICIÓN DE IDENTIDAD",
    "privacy_title": "Tu identidad real se mantiene completamente oculta.",
    "privacy_sub": "Deja de compartir tu número de teléfono y correo. RELAY usa una clave temporal de 6 dígitos para mantener tu vida privada a salvo.",
    "group_kicker": "VIDEOCONFERENCIAS GRUPALES",
    "group_title": "Reúne al equipo. Sin necesidad de registrarse.",
    "group_sub": "Organiza videoconferencias dinámicas con hasta 10 personas. Comparte un único enlace y controla la sala con herramientas de moderación profesional.",
    "group_badge": "Hasta 10 personas",
    "feat_kicker": "CREADO PARA LA VELOCIDAD",
    "feat_title": "Impulsando las conversaciones modernas.",
    "feat_sub": "Todo lo que necesitas de una aplicación de llamadas de primer nivel, directamente en tu navegador.",
    "shots_kicker": "MUESTRA DEL PRODUCTO",
    "shots_title": "Echa un vistazo dentro de RELAY.",
    "shots_sub": "Limpio, elegante y rápido en cualquier dispositivo.",
    "shot_dialer_t": "Marcador instantáneo",
    "shot_dialer_d": "Escribe un nombre, obtén tu número de 6 dígitos y llama al instante.",
    "shot_chat_t": "Chat multimedia rico",
    "shot_chat_d": "Comparte archivos, notas de voz e imágenes de forma segura sin salir de la pestaña.",
    "shot_group_t": "Mosaico de video para 10 personas",
    "shot_group_d": "Video multipantalla nítido con foco en el hablante activo y controles completos.",
    "shot_contacts_t": "Historial en un toque",
    "shot_contacts_d": "Vuelve a llamar rápidamente a tus contactos recientes desde tu historial local seguro.",
    "mobile_t": "Va contigo a donde sea.",
    "mobile_d": "Totalmente optimizado para navegadores móviles y de escritorio. Sin descargas de tiendas de apps.",
    "cta_title": "¿Listo para salir del radar?",
    "cta_sub": "Consigue tu número de 6 dígitos en 3 segundos y empieza a hablar.",
    "cta_btn": "Empezar ahora - Gratis",
    "footer_tag": "RELAY - Llamadas privadas en navegador",
    "footer_rights": "© 2025 RELAY. Todos los derechos reservados. Conexión directa, segura e instantánea.",
    "privacy_points": [
      "No requiere número de teléfono real ni correo electrónico",
      "Conexiones peer-to-peer directas para máxima seguridad",
      "No se guarda historial de chat en bases de datos en la nube"
    ],
    "group_points": [
      "Aloja hasta 10 personas en una sola sala",
      "Cuadrícula de video multipantalla con enfoque en el hablante activo",
      "Controles completos de anfitrión: silenciar a todos, fijar/eliminar, transferir",
      "Un único enlace de invitación para acceso instantáneo"
    ],
    "pillars": [
      {
        "t": "Oculta tu identidad",
        "d": "No vuelvas a compartir tu número de teléfono ni correo real."
      },
      {
        "t": "Grupos de hasta 10",
        "d": "Organiza reuniones de video grupales fácilmente con un enlace para compartir."
      },
      {
        "t": "Sin configuración",
        "d": "Funciona totalmente en tu navegador web sin instalar absolutamente nada."
      },
      {
        "t": "Gratis y único",
        "d": "Consigue tu número personal de 6 dígitos gratis y al instante."
      }
    ],
    "blocks": [
      {
        "tag": "TALK",
        "title": "Llamadas instantáneas",
        "desc": "Inicia llamadas de voz y video 1 a 1 ultranítidas con cualquiera directamente en el navegador.",
        "items": [
          "Remarcado rápido",
          "Soporte Bluetooth",
          "Timbre multidispositivo",
          "Sin crear cuenta"
        ]
      },
      {
        "tag": "MEET",
        "title": "Videoconferencias potentes",
        "desc": "Reúne hasta 10 personas con un único enlace seguro. Toma el control de tus salas.",
        "items": [
          "Hasta 10 personas",
          "Silenciar a todos",
          "Cuadrícula multipantalla",
          "Transferir anfitrión"
        ]
      },
      {
        "tag": "CHAT",
        "title": "Mensajería enriquecida",
        "desc": "Envía archivos, imágenes y notas de voz de forma segura. Comparte pantalla o usa Picture-in-Picture.",
        "items": [
          "Compartir archivos",
          "Notas de voz",
          "Compartir pantalla",
          "Picture-in-Picture"
        ]
      }
    ],
    "features": [
      {
        "t": "Clave de 6 dígitos al instante",
        "d": "Consigue un código aleatorio al instante para recibir llamadas sin revelar tus datos reales."
      },
      {
        "t": "Voz y video en HD",
        "d": "Disfruta de llamadas nítidas y de baja latencia basadas en la tecnología moderna WebRTC."
      },
      {
        "t": "Salas para 10 personas",
        "d": "Reúne hasta diez participantes en un espacio de video único de alta fidelidad."
      },
      {
        "t": "Controles avanzados",
        "d": "Silencia a todos, destaca al hablante, transfiere el control o elimina invitados al instante."
      },
      {
        "t": "Chat privado enriquecido",
        "d": "Intercambia archivos, imágenes y grabaciones de voz de forma segura dentro de tu sesión de llamada."
      },
      {
        "t": "Pantalla y Picture-in-Picture",
        "d": "Presenta tu escritorio o mira los videos en una ventana flotante mientras navegas por otras pestañas."
      },
      {
        "t": "Audio inteligente",
        "d": "Cambia sin problemas entre tus altavoces, auriculares o dispositivos Bluetooth conectados."
      },
      {
        "t": "Historial local de llamadas",
        "d": "Mira tus llamadas recientes y vuelve a marcar con un solo clic."
      },
      {
        "t": "Escudo de privacidad total",
        "d": "Sin rastreo, sin sincronización de contactos y sin bases de datos ocultas."
      }
    ],
    "faqs": [
      {
        "q": "¿Tengo que instalar una app o registrarme?",
        "a": "No. RELAY funciona totalmente en tu navegador móvil o de escritorio. Sin descargas, sin registros ni contraseñas."
      },
      {
        "q": "¿Cómo me protege el número de 6 dígitos?",
        "a": "En lugar de dar tu número o email, compartes tu clave RELAY de 6 dígitos. Tu identidad real y tus contactos permanecen ocultos."
      },
      {
        "q": "¿Puedo hacer llamadas grupales?",
        "a": "¡Sí! Puedes hospedar hasta 10 personas en una videoconferencia. Comparte el enlace y tus invitados se unirán al instante sin cuenta."
      },
      {
        "q": "¿Es RELAY realmente gratis?",
        "a": "Sí, RELAY es completamente gratis. No hay opciones de pago ni costes ocultos para ninguna función."
      }
    ]
  },
  "fr": {
    "lang_name": "Français",
    "hero_kicker": "L'ÈRE NOUVELLE DES COMMUNICATIONS SUR NAVIGATEUR",
    "hero_title_1": "Connectez-vous instantanément.",
    "hero_title_2": "Restez anonyme.",
    "hero_sub": "Obtenez un numéro unique à 6 chiffres. Lancez des appels vocaux, vidéo ou des réunions de groupe directement depuis votre navigateur. Sans installation ni compte.",
    "hero_note": "Aucun numéro requis. Gratuit à vie.",
    "hero_cta": "Obtenir mon numéro",
    "sticky_cta": "Ouvrir RELAY",
    "stats_title": "Connexions actives",
    "stats_sub": "Des personnes du monde entier communiquent selon leurs propres règles.",
    "stat_registered": "Numéros à 6 chiffres générés",
    "stat_guests": "Appels en cours",
    "stat_total": "Total des échanges",
    "stat_online": "En ligne actuellement",
    "privacy_kicker": "ANONYMAT TOTAL",
    "privacy_title": "Votre identité réelle reste totalement secrète.",
    "privacy_sub": "Cessez de divulguer votre numéro ou votre e-mail. RELAY génère une clé temporaire à 6 chiffres pour protéger votre vie privée.",
    "group_kicker": "VIDÉOCONFÉRENCES DE GROUPE",
    "group_title": "Rassemblez votre équipe. Sans inscription préalable.",
    "group_sub": "Hébergez des réunions vidéo dynamiques jusqu'à 10 personnes. Partagez un lien unique et modérez la salle grâce aux fonctions d'hôte.",
    "group_badge": "Jusqu'à 10 personnes",
    "feat_kicker": "CONÇU POUR LA VITESSE",
    "feat_title": "Propulser les échanges modernes.",
    "feat_sub": "Tout le confort d'un outil d'appel haut de gamme, directement dans votre navigateur web.",
    "shots_kicker": "Aperçu du produit",
    "shots_title": "Découvrez l'interface de RELAY.",
    "shots_sub": "Épurée, élégante et ultra-rapide sur tous les écrans.",
    "shot_dialer_t": "Le clavier instantané",
    "shot_dialer_d": "Saisissez un nom, réservez votre numéro à 6 chiffres et passez un appel.",
    "shot_chat_t": "Chat multimédia riche",
    "shot_chat_d": "Partagez des fichiers, des mémos vocaux et des images sans jamais quitter le navigateur.",
    "shot_group_t": "Vidéos en grille à 10",
    "shot_group_d": "Affichage fluide avec mise en valeur de l'orateur et contrôles d'administration complets.",
    "shot_contacts_t": "Rappel en un clic",
    "shot_contacts_d": "Consultez l'historique d'appels local et sécurisé pour rappeler rapidement.",
    "mobile_t": "S'adapte à tous vos déplacements.",
    "mobile_d": "Entièrement réactif sur mobiles et ordinateurs. Aucun téléchargement d'application requis.",
    "cta_title": "Prêt à protéger vos données ?",
    "cta_sub": "Obtenez votre numéro à 6 chiffres en 3 secondes et commencez à discuter.",
    "cta_btn": "Démarrer - C'est Gratuit",
    "footer_tag": "RELAY - Appels privés sur navigateur",
    "footer_rights": "© 2025 RELAY. Tous droits réservés. Connexions peer-to-peer privées et instantanées.",
    "privacy_points": [
      "Aucun vrai numéro de téléphone ou e-mail requis",
      "Connexions directes peer-to-peer pour une sécurité maximale",
      "Aucun historique de chat enregistré sur des serveurs cloud"
    ],
    "group_points": [
      "Accueillez jusqu'à 10 personnes dans un seul salon",
      "Grille vidéo multi-écrans avec focus sur l'orateur actif",
      "Contrôles d'hôte complets : couper le micro, épingler/exclure, transférer",
      "Un seul lien d'invitation pour un accès instantané"
    ],
    "pillars": [
      {
        "t": "Masquez votre identité",
        "d": "Ne partagez plus jamais votre vrai numéro de téléphone ou e-mail."
      },
      {
        "t": "Groupes jusqu'à 10",
        "d": "Organisez facilement des réunions vidéo de groupe avec un simple lien."
      },
      {
        "t": "Aucune installation",
        "d": "Fonctionne entièrement dans votre navigateur sans rien installer."
      },
      {
        "t": "Gratuit et unique",
        "d": "Obtenez votre numéro personnel à 6 chiffres gratuitement et instantanément."
      }
    ],
    "blocks": [
      {
        "tag": "TALK",
        "title": "Appels instantanés sur navigateur",
        "desc": "Lancez des appels voix et vidéo 1-à-1 ultra-clairs directement depuis votre navigateur.",
        "items": [
          "Rappel rapide",
          "Support Bluetooth",
          "Sonnerie multi-appareils",
          "Sans création de compte"
        ]
      },
      {
        "tag": "MEET",
        "title": "Vidéoconférences puissantes",
        "desc": "Rassemblez jusqu'à 10 personnes via un lien d'invitation sécurisé. Prenez le contrôle total.",
        "items": [
          "Jusqu'à 10 personnes",
          "Couper les micros",
          "Grille multi-écrans",
          "Transférer l'hôte"
        ]
      },
      {
        "tag": "CHAT",
        "title": "Messagerie enrichie",
        "desc": "Envoyez des fichiers, des images et des notes vocales en toute sécurité. Partagez votre écran ou utilisez le Picture-in-Picture.",
        "items": [
          "Partage de fichiers",
          "Notes vocales",
          "Partage d'écran",
          "Picture-in-Picture"
        ]
      }
    ],
    "features": [
      {
        "t": "Code instantané à 6 chiffres",
        "d": "Obtenez un code aléatoire instantanément pour recevoir des appels sans dévoiler vos données."
      },
      {
        "t": "Voix & Vidéo HD",
        "d": "Profitez d'appels nets et à faible latence grâce à la technologie WebRTC moderne."
      },
      {
        "t": "Salons pour 10 personnes",
        "d": "Rassemblez jusqu'à dix participants dans un espace vidéo unique de haute qualité."
      },
      {
        "t": "Contrôles d'hôte avancés",
        "d": "Coupez tous les micros, mettez en avant l'orateur, transférez les droits ou excluez des invités."
      },
      {
        "t": "Chat privé enrichi",
        "d": "Échangez des fichiers, des images et des enregistrements audio directement au cours de votre appel."
      },
      {
        "t": "Partage & Picture-in-Picture",
        "d": "Présentez votre écran ou suivez la vidéo dans une fenêtre flottante tout en naviguant."
      },
      {
        "t": "Routage audio intelligent",
        "d": "Basculez facilement entre vos haut-parleurs, écouteurs ou appareils Bluetooth connectés."
      },
      {
        "t": "Historique d'appels local",
        "d": "Consultez vos appels récents et rappelez vos correspondants en un seul clic."
      },
      {
        "t": "Bouclier de confidentialité total",
        "d": "Pas de suivi, pas de synchronisation de carnet d'adresses, pas de bases de données cachées."
      }
    ],
    "faqs": [
      {
        "q": "Dois-je installer une application ou créer un compte ?",
        "a": "Non. RELAY fonctionne entièrement dans votre navigateur web mobile ou de bureau. Pas de téléchargement, pas d'inscription."
      },
      {
        "q": "Comment le numéro à 6 chiffres protège-t-il ma vie privée ?",
        "a": "Au lieu de donner votre numéro de téléphone ou e-mail, vous partagez votre code RELAY à 6 chiffres. Vos coordonnées réelles restent privées."
      },
      {
        "q": "Puis-je organiser un appel vidéo de groupe ?",
        "a": "Oui ! Vous pouvez accueillir jusqu'à 10 personnes dans une visioconférence. Partagez le lien d'invitation et vos invités rejoignent instantanément sans compte."
      },
      {
        "q": "Est-ce que RELAY est vraiment gratuit ?",
        "a": "Oui, RELAY est entièrement gratuit. Il n'y a pas d'options payantes ni de frais cachés pour nos fonctionnalités."
      }
    ]
  },
  "de": {
    "lang_name": "Deutsch",
    "hero_kicker": "DIE NEUE ÄRA DER BROWSER-KOMMUNIKATION",
    "hero_title_1": "Sofort verbinden.",
    "hero_title_2": "Völlig privat bleiben.",
    "hero_sub": "Hol dir sofort deine 6-stellige Nummer. Starte Sprach-, Video- oder Gruppen-Chats direkt im Browser. Keine Installation, kein Account.",
    "hero_note": "Keine Telefonnummer nötig. Für immer kostenlos.",
    "hero_cta": "Nummer holen",
    "sticky_cta": "RELAY öffnen",
    "stats_title": "Aktive Verbindungen",
    "stats_sub": "Menschen weltweit kommunizieren nach ihren eigenen Regeln.",
    "stat_registered": "Vergebene 6-stellige Nummern",
    "stat_guests": "Aktive Anrufer",
    "stat_total": "Gespräche insgesamt",
    "stat_online": "Gerade online",
    "privacy_kicker": "NULL IDENTITÄTS-EXPOSITION",
    "privacy_title": "Deine echte Identität bleibt absolut geheim.",
    "privacy_sub": "Schluss mit der Weitergabe von Telefonnummer und E-Mail. RELAY nutzt eine temporäre 6-stellige Kennung, um deine Privatsphäre zu schützen.",
    "group_kicker": "GRUPPEN-VIDEOKONFERENZEN",
    "group_title": "Bringe das Team zusammen. Ohne Registrierung.",
    "group_sub": "Veranstalte lebendige Videokonferenzen mit bis zu 10 Personen. Teile einen Link und steuere den Raum mit professionellen Tools.",
    "group_badge": "Bis zu 10 Personen",
    "feat_kicker": "FÜR SPEED ENTWICKELT",
    "feat_title": "Moderne Kommunikation neu definiert.",
    "feat_sub": "Alles, was du von einer Premium-Calling-App erwartest, direkt in deinem Webbrowser.",
    "shots_kicker": "PRODUKT-VORSCHAU",
    "shots_title": "Ein Blick in RELAY.",
    "shots_sub": "Klar, elegant und pfeilschnell auf jedem Gerät.",
    "shot_dialer_t": "Der Direkt-Wähler",
    "shot_dialer_d": "Namen eingeben, 6-stellige Nummer sichern und sofort lostelefonieren.",
    "shot_chat_t": "Multimedialer Chat",
    "shot_chat_d": "Teile Dateien, Sprachnachrichten und Bilder sicher, ohne deinen Browser-Tab zu verlassen.",
    "shot_group_t": "10-Personen Video-Raster",
    "shot_group_d": "Gestochen scharfes Video mit aktivem Sprecherfokus und voller Moderationskontrolle.",
    "shot_contacts_t": "Verlauf per Fingertipp",
    "shot_contacts_d": "Wähle Kontakte aus deinem lokalen, geschützten Anrufverlauf schnell wieder an.",
    "mobile_t": "Immer an deiner Seite.",
    "mobile_d": "Komplett optimiert für mobile und Desktop-Browser. Kein Download aus App-Stores nötig.",
    "cta_title": "Bereit für echte Privatsphäre?",
    "cta_sub": "Sichere dir in 3 Sekunden deine 6-stellige Nummer und sprich los.",
    "cta_btn": "Jetzt starten - Kostenlos",
    "footer_tag": "RELAY - Private Browser-Anrufe",
    "footer_rights": "© 2025 RELAY. Alle Rechte vorbehalten. Peer-to-peer, sicher und sofort.",
    "privacy_points": [
      "Keine echte Telefonnummer oder E-Mail erforderlich",
      "Direkte Peer-to-peer-Verbindungen für maximale Sicherheit",
      "Keine Chat-Verläufe in einer Cloud-Datenbank gespeichert"
    ],
    "group_points": [
      "Bis zu 10 Personen in einem Raum hosten",
      "Multi-Screen-Videoraster mit Fokus auf den aktiven Sprecher",
      "Volle Host-Kontrolle: Alle stummschalten, anpinnen/entfernen, Host übertragen",
      "Ein einziger Einladungslink für sofortigen Beitritt"
    ],
    "pillars": [
      {
        "t": "Identität schützen",
        "d": "Teile nie wieder deine echte Telefonnummer oder E-Mail-Adresse."
      },
      {
        "t": "Gruppen bis zu 10",
        "d": "Veranstalte ganz einfach Gruppen-Videomeetings über einen einzigen Link."
      },
      {
        "t": "Kein Setup",
        "d": "Läuft komplett in deinem Webbrowser, absolut ohne Installation."
      },
      {
        "t": "Kostenlos & Einzigartig",
        "d": "Sichere dir sofort und kostenlos deine persönliche 6-stellige Nummer."
      }
    ],
    "blocks": [
      {
        "tag": "TALK",
        "title": "Sofortige Browser-Anrufe",
        "desc": "Starte kristallklare 1-zu-1-Sprach- und Videoanrufe mit jedem direkt im Browser.",
        "items": [
          "Schnelles Wahlwiederholen",
          "Bluetooth-Unterstützung",
          "Klingeln auf mehreren Geräten",
          "Keine Registrierung"
        ]
      },
      {
        "tag": "MEET",
        "title": "Starke Gruppen-Meetings",
        "desc": "Bringe bis zu 10 Personen über einen sicheren Einladungslink zusammen. Behalte die volle Kontrolle.",
        "items": [
          "Bis zu 10 Personen",
          "Alle stummschalten",
          "Multi-Screen-Raster",
          "Host übertragen"
        ]
      },
      {
        "tag": "CHAT",
        "title": "Vielseitiges Messaging",
        "desc": "Sende Dateien, Bilder und Sprachnachrichten sicher. Nutze Screen-Sharing oder Picture-in-Picture.",
        "items": [
          "Datei- & Bildfreigabe",
          "Sprachnachrichten",
          "Bildschirmfreigabe",
          "Picture-in-Picture"
        ]
      }
    ],
    "features": [
      {
        "t": "Sofortiger 6-stelliger Code",
        "d": "Erhalte sofort einen zufälligen Code, um Anrufe zu empfangen, ohne private Daten preiszugeben."
      },
      {
        "t": "HD Sprach- & Videoqualität",
        "d": "Genieße glasklare Browser-zu-Browser-Anrufe mit minimaler Latenz dank WebRTC-Technologie."
      },
      {
        "t": "Gruppenräume für 10 Personen",
        "d": "Bringe bis zu zehn Teilnehmer in einem hochauflösenden Videoraum zusammen."
      },
      {
        "t": "Erweiterte Host-Kontrollen",
        "d": "Schalte alle stumm, rücke aktive Sprecher in den Fokus, übertrage Host-Rechte oder entferne Gäste."
      },
      {
        "t": "Sicherer privater Chat",
        "d": "Teile Dateien, Fotos und Sprachaufnahmen direkt während deines laufenden Anrufs."
      },
      {
        "t": "Screen-Sharing & PiP",
        "d": "Präsentiere deinen Desktop oder verfolge den Video-Feed in einem schwebenden Fenster."
      },
      {
        "t": "Smartes Audio-Routing",
        "d": "Wechsle nahtlos zwischen Lautsprechern, Kopfhörern oder gekoppelten Bluetooth-Geräten."
      },
      {
        "t": "Lokaler Anrufverlauf",
        "d": "Sieh dir deine letzten Anrufe an und wähle Kontakte mit nur einem Klick erneut."
      },
      {
        "t": "100% Datenschutz-Schild",
        "d": "Kein Tracking, kein Abgleich von Kontaktdaten und keine versteckten Datenbanken im Hintergrund."
      }
    ],
    "faqs": [
      {
        "q": "Muss ich eine App installieren oder ein Konto erstellen?",
        "a": "Nein. RELAY läuft komplett in deinem mobilen oder Desktop-Webbrowser. Es gibt keine Downloads, Registrierungen oder Passwörter."
      },
      {
        "q": "Wie schützt die 6-stellige Nummer meine Privatsphäre?",
        "a": "Statt deiner Telefonnummer oder E-Mail teilst du nur deine 6-stellige RELAY-Nummer. Deine echte Identität bleibt absolut geschützt."
      },
      {
        "q": "Kann ich ein Gruppen-Videomeeting veranstalten?",
        "a": "Ja! Du kannst bis zu 10 Personen in einer Videokonferenz hosten. Teile einfach den Einladungslink, und Gäste können ohne Account beitreten."
      },
      {
        "q": "Ist RELAY wirklich kostenlos?",
        "a": "Ja, RELAY ist vollkommen kostenlos. Es gibt keine Premium-Schranken oder versteckten Kosten für unsere Funktionen."
      }
    ]
  },
  "hi": {
    "lang_name": "हिन्दी",
    "hero_kicker": "ब्राउज़र संचार का नया युग",
    "hero_title_1": "तुरंत जुड़ें।",
    "hero_title_2": "पूरी तरह सुरक्षित रहें।",
    "hero_sub": "तुरंत अपना 6-अंकीय नंबर पाएं। सीधे अपने ब्राउज़र में वॉयस, वीडियो या ग्रुप चैट शुरू करें। कोई इंस्टॉलेशन नहीं, कोई अकाउंट नहीं।",
    "hero_note": "किसी फोन नंबर की आवश्यकता नहीं। हमेशा के लिए मुफ्त।",
    "hero_cta": "अपना नंबर पाएं",
    "sticky_cta": "RELAY खोलें",
    "stats_title": "सक्रिय कनेक्शन",
    "stats_sub": "दुनिया भर के लोग अपनी शर्तों पर बातचीत कर रहे हैं।",
    "stat_registered": "6-अंकीय कोड जनरेट हुए",
    "stat_guests": "सक्रिय कॉलर्स",
    "stat_total": "कुल बातचीत",
    "stat_online": "अभी ऑनलाइन",
    "privacy_kicker": "शून्य पहचान प्रकटीकरण",
    "privacy_title": "आपकी वास्तविक पहचान पूरी तरह से छिपी रहती है।",
    "privacy_sub": "अपना फोन नंबर और ईमेल साझा करना बंद करें। RELAY आपकी निजी जिंदगी को सुरक्षित रखने के लिए एक अस्थायी 6-अंकीय कोड का उपयोग करता है।",
    "group_kicker": "ग्रुप वीडियो कॉन्फ्रेंस",
    "group_title": "टीम को एक साथ लाएं। बिना किसी साइन-अप के।",
    "group_sub": "10 लोगों तक के साथ लाइव वीडियो कॉन्फ्रेंस होस्ट करें। एक सिंगल लिंक साझा करें और पेशेवर होस्ट टूल्स के साथ मीटिंग को नियंत्रित करें।",
    "group_badge": "10 लोगों तक",
    "feat_kicker": "तेज़ गति के लिए निर्मित",
    "feat_title": "आधुनिक संचार को सशक्त बनाना।",
    "feat_sub": "एक प्रीमियम कॉलिंग ऐप की हर ज़रूरत, सीधे आपके वेब ब्राउज़र के अंदर।",
    "shots_kicker": "प्रोडक्ट शोकेस",
    "shots_title": "RELAY के अंदर का दृश्य देखें।",
    "shots_sub": "साफ़, सुंदर और हर डिवाइस पर बेहद तेज़।",
    "shot_dialer_t": "इंस्टेंट डायलर",
    "shot_dialer_d": "एक नाम टाइप करें, अपना 6-अंकीय नंबर पाएं और तुरंत डायल करें।",
    "shot_chat_t": "रिच मल्टीमीडिया चैट",
    "shot_chat_d": "ब्राउज़र छोड़े बिना फ़ाइलें, वॉयस नोट्स और चित्र सुरक्षित रूप से साझा करें।",
    "shot_group_t": "10-व्यक्ति वीडियो ग्रिड",
    "shot_group_d": "एक्टिव-स्पीकर स्पॉटलाइट और पूर्ण होस्ट नियंत्रण के साथ स्पष्ट वीडियो ग्रिड।",
    "shot_contacts_t": "वन-टैप इतिहास",
    "shot_contacts_d": "अपने स्थानीय, सुरक्षित कॉल इतिहास से हाल के संपर्कों को तुरंत पुनः डायल करें।",
    "mobile_t": "जहां भी आप जाएं, साथ चले।",
    "mobile_d": "मोबाइल और डेस्कटॉप ब्राउज़र पर पूरी तरह से उत्तरदायी। किसी ऐप स्टोर डाउनलोड की आवश्यकता नहीं है।",
    "cta_title": "गोपनीयता के लिए तैयार हैं?",
    "cta_sub": "3 सेकंड में अपना 6-अंकीय नंबर पाएं और बात करना शुरू करें।",
    "cta_btn": "अभी शुरू करें - यह मुफ़्त है",
    "footer_tag": "RELAY - निजी ब्राउज़र कॉल्स",
    "footer_rights": "© 2025 RELAY. सर्वाधिकार सुरक्षित। पीयर-टू-पीयर, सुरक्षित और त्वरित।",
    "privacy_points": [
      "कोई वास्तविक फोन नंबर या ईमेल आवश्यक नहीं है",
      "अधिकतम सुरक्षा के लिए सीधे पीयर-टू-पीयर कनेक्शन",
      "किसी भी क्लाउड डेटाबेस पर कोई चैट इतिहास सहेजा नहीं जाता"
    ],
    "group_points": [
      "एक ही कमरे में अधिकतम 10 लोगों को होस्ट करें",
      "एक्टिव-स्पीकर स्पॉटलाइट के साथ मल्टी-स्क्रीन वीडियो ग्रिड",
      "पूर्ण होस्ट नियंत्रण: सभी को म्यूट करें, पिन/रिमूव करें, होस्ट ट्रांसफर करें",
      "तुरंत शामिल होने के लिए एक सिंगल आमंत्रण लिंक"
    ],
    "pillars": [
      {
        "t": "अपनी पहचान छुपाएं",
        "d": "फिर कभी अपना असली फोन नंबर या ईमेल साझा न करें।"
      },
      {
        "t": "10 लोगों तक ग्रुप",
        "d": "एक सिंगल शेयर करने योग्य लिंक के साथ आसानी से ग्रुप वीडियो मीटिंग होस्ट करें।"
      },
      {
        "t": "कोई सेटअप नहीं",
        "d": "बिना कुछ इंस्टॉल किए पूरी तरह से आपके वेब ब्राउज़र में चलता है।"
      },
      {
        "t": "मुफ्त और अनूठा",
        "d": "बिना किसी शुल्क के तुरंत अपना व्यक्तिगत 6-अंकीय नंबर प्राप्त करें।"
      }
    ],
    "blocks": [
      {
        "tag": "TALK",
        "title": "तुरंत ब्राउज़र कॉलिंग",
        "desc": "सीधे ब्राउज़र में किसी के भी साथ स्पष्ट 1-ऑन-1 वॉयस और वीडियो कॉल शुरू करें।",
        "items": [
          "एक-टैप रीडायल",
          "ब्लूटूथ सपोर्ट",
          "मल्टी-डिवाइस रिंगिंग",
          "बिना अकाउंट सेटअप"
        ]
      },
      {
        "tag": "MEET",
        "title": "शक्तिशाली ग्रुप कॉन्फ्रेंस",
        "desc": "एक सुरक्षित इनवाइट लिंक के साथ 10 लोगों को एक साथ लाएं। अपने रूम पर पूरा नियंत्रण रखें।",
        "items": [
          "10 लोगों तक",
          "सभी को म्यूट करें",
          "मल्टी-स्क्रीन ग्रिड",
          "होस्ट ट्रांसफर"
        ]
      },
      {
        "tag": "CHAT",
        "title": "समृद्ध मैसेजिंग और शेयरिंग",
        "desc": "फाइलें, चित्र और वॉयस नोट्स सुरक्षित रूप से भेजें। स्क्रीन शेयर करें या पिक्चर-इन-पिक्चर का उपयोग करें।",
        "items": [
          "फाइल और इमेज शेयरिंग",
          "वॉयस नोट्स",
          "स्क्रीन शेयरिंग",
          "पिक्चर-इन-पिक्चर"
        ]
      }
    ],
    "features": [
      {
        "t": "तुरंत 6-अंकीय कुंजी",
        "d": "अपनी वास्तविक जानकारी को उजागर किए बिना कॉल प्राप्त करने के लिए तुरंत एक कोड प्राप्त करें।"
      },
      {
        "t": "एचडी वॉयस और वीडियो",
        "d": "आधुनिक WebRTC पर निर्मित स्पष्ट, कम-लेटेंसी वाली ब्राउज़र-टू-ब्राउज़र कॉल का आनंद लें।"
      },
      {
        "t": "10-व्यक्ति ग्रुप रूम",
        "d": "एक ही उच्च-गुणवत्ता वाले वीडियो स्पेस में दस प्रतिभागियों को एक साथ लाएं।"
      },
      {
        "t": "उन्नत होस्ट नियंत्रण",
        "d": "सभी को म्यूट करें, वर्तमान वक्ता को स्पॉटलाइट करें, होस्ट अनुमतियां स्थानांतरित करें, या मेहमानों को तुरंत हटाएं।"
      },
      {
        "t": "रिच प्राइवेट चैट",
        "d": "अपने सुरक्षित कॉल सत्र के भीतर सीधे फाइलें, चित्र और वॉयस रिकॉर्डिंग साझा करें।"
      },
      {
        "t": "स्क्रीन और पिक्चर-इन-पिक्चर",
        "d": "अन्य टैब ब्राउज़ करते समय अपना डेस्कटॉप प्रस्तुत करें या फ़्लोटिंग विंडो में वीडियो फ़ीड देखें।"
      },
      {
        "t": "स्मार्ट ऑडियो रूटिंग",
        "d": "अपने स्पीकर, हेडफ़ोन या कनेक्टेड ब्लूटूथ डिवाइस के बीच आसानी से स्विच करें।"
      },
      {
        "t": "स्थानीय कॉल इतिहास",
        "d": "अपनी हाल की इनकमिंग और आउटगोइंग कॉल देखें और एक सिंगल क्लिक के साथ वापस डायल करें।"
      },
      {
        "t": "100% गोपनीयता शील्ड",
        "d": "कोई ट्रैकिंग नहीं, कोई एड्रेस बुक सिंकिंग नहीं, और कोई गुप्त डेटाबेस नहीं।"
      }
    ],
    "faqs": [
      {
        "q": "क्या मुझे ऐप इंस्टॉल करने या अकाउंट बनाने की आवश्यकता है?",
        "a": "नहीं। RELAY पूरी तरह से आपके मोबाइल या डेस्कटॉप वेब ब्राउज़र के भीतर काम करता है। कोई डाउनलोड, साइन-अप या पासवर्ड नहीं है।"
      },
      {
        "q": "6-अंकों का नंबर मेरी गोपनीयता की रक्षा कैसे करता है?",
        "a": "अपना असली फोन नंबर या ईमेल साझा करने के बजाय, आप अपना 6-अंकों का RELAY कोड देते हैं। आपकी वास्तविक पहचान और संपर्क पूरी तरह छिपे रहते हैं।"
      },
      {
        "q": "क्या मैं ग्रुप वीडियो कॉल होस्ट कर सकता हूँ?",
        "a": "हाँ! आप एक वीडियो कॉन्फ्रेंस में 10 लोगों तक को होस्ट कर सकते हैं। बस इनवाइट लिंक साझा करें, और मेहमान बिना किसी अकाउंट के तुरंत शामिल हो सकते हैं।"
      },
      {
        "q": "क्या RELAY वास्तव में मुफ्त है?",
        "a": "हाँ, RELAY पूरी तरह से मुफ्त है। हमारी किसी भी सुविधा के लिए कोई प्रीमियम शुल्क या छिपी हुई लागत नहीं है।"
      }
    ]
  }
} as const;

export type LangCode = keyof typeof LANDING_COPY;
export type Copy = (typeof LANDING_COPY)[LangCode];
